use utf8;
# 22 arkadaş - her biri gerçek bir insan gibi tutarlı bir hayata sahip.
# Buradaki her alan diyaloglara "slot" olarak girer, bu yüzden bir karakterin
# cevapları asla birbiriyle çelişmez.
[
{
  id=>'jack', name=>'Jack', full=>'Jack Miller', emoji=>'☕', color=>'#c0703a', age=>27,
  level=>'A2', voice=>'en-GB', city=>'London', cityTr=>'Londra',
  job=>'a barista', jobTr=>'barista', work=>'Bean Street Café', workTr=>'Bean Street Kafe',
  team=>'Arsenal', player=>'Bukayo Saka',
  drink=>'a flat white', drinkTr=>'sütlü kahve', food=>'fish and chips', foodTr=>'balık ve patates',
  breakfast=>'toast with jam', breakfastTr=>'reçelli tost',
  pet=>'no pet, only a plant called Kevin', petTr=>'evcil hayvanı yok, sadece Kevin adında bir bitkisi var',
  family=>'a younger sister called Mia', familyTr=>'Mia adında bir küçük kız kardeşi',
  hobby=>'skateboarding', hobbyTr=>'kaykay',
  music=>'Oasis', musicTr=>'Oasis', film=>'The Dark Knight', series=>'Peaky Blinders',
  dream=>'to open my own coffee shop', dreamTr=>'kendi kahve dükkanını açmak',
  place=>'Japan', placeTr=>'Japonya', lastHol=>'Barcelona', lastHolTr=>'Barselona',
  transport=>'the tube', transportTr=>'metro', weather=>'rainy afternoons', weatherTr=>'yağmurlu öğleden sonraları',
  phrase=>'Cheers, mate!', phraseTr=>'Sağ ol dostum!', style=>'mate',
  bio=>'Londra\'da kafe işleten, esprili ve rahat bir arkadaş. Basit ve günlük İngilizce konuşur.'
},
{
  id=>'emily', name=>'Emily', full=>'Emily Carter', emoji=>'🩺', color=>'#4aa3a0', age=>24,
  level=>'A2', voice=>'en-GB', city=>'Manchester', cityTr=>'Manchester',
  job=>'a nurse', jobTr=>'hemşire', work=>'City Hospital', workTr=>'Şehir Hastanesi',
  team=>'Manchester City', player=>'Erling Haaland',
  drink=>'tea with milk', drinkTr=>'sütlü çay', food=>'chicken curry', foodTr=>'tavuklu köri',
  breakfast=>'porridge', breakfastTr=>'yulaf lapası',
  pet=>'a cat called Biscuit', petTr=>'Biscuit adında bir kedisi',
  family=>'a big brother called Josh', familyTr=>'Josh adında bir ağabeyi',
  hobby=>'baking cakes', hobbyTr=>'kek yapmak',
  music=>'Adele', musicTr=>'Adele', film=>'Notting Hill', series=>"Grey's Anatomy",
  dream=>'to work in New Zealand for a year', dreamTr=>'bir yıl Yeni Zelanda\'da çalışmak',
  place=>'New Zealand', placeTr=>'Yeni Zelanda', lastHol=>'Cornwall', lastHolTr=>'Cornwall',
  transport=>'my old bike', transportTr=>'eski bisikleti', weather=>'sunny mornings', weatherTr=>'güneşli sabahlar',
  phrase=>'Oh, bless!', phraseTr=>'Ay, ne tatlı!', style=>'soft',
  bio=>'Hastanede çalışan, çok şefkatli ve konuşkan bir hemşire. Yorucu vardiyalardan bahseder.'
},
{
  id=>'leo', name=>'Leo', full=>'Leo Rossi', emoji=>'🍝', color=>'#b3452f', age=>30,
  level=>'B1', voice=>'en-US', city=>'New York', cityTr=>'New York',
  job=>'a chef', jobTr=>'aşçı', work=>"Rossi's Kitchen", workTr=>'Rossi Mutfağı',
  team=>'Inter Milan', player=>'Lautaro Martínez',
  drink=>'an espresso', drinkTr=>'espresso', food=>'lasagna', foodTr=>'lazanya',
  breakfast=>'a cornetto and coffee', breakfastTr=>'kruvasan ve kahve',
  pet=>'a dog called Pepe', petTr=>'Pepe adında bir köpeği',
  family=>'a huge family - four cousins on the same street', familyTr=>'kalabalık bir ailesi, aynı sokakta dört kuzeni',
  hobby=>'cooking for my friends', hobbyTr=>'arkadaşlarına yemek yapmak',
  music=>'Italian rock', musicTr=>'İtalyan rock', film=>'Goodfellas', series=>'The Bear',
  dream=>'to open a small trattoria in Brooklyn', dreamTr=>'Brooklyn\'de küçük bir lokanta açmak',
  place=>'Sicily', placeTr=>'Sicilya', lastHol=>'Naples', lastHolTr=>'Napoli',
  transport=>'my old Vespa', transportTr=>'eski Vespa\'sı', weather=>'hot summer nights', weatherTr=>'sıcak yaz geceleri',
  phrase=>'Mamma mia!', phraseTr=>'Aman Tanrım!', style=>'loud',
  bio=>'İtalyan asıllı New Yorklu aşçı. Yüksek sesle, elleriyle konuşur; yemek ve aile onun her şeyi.'
},
{
  id=>'sophie', name=>'Sophie', full=>'Sophie Bennett', emoji=>'🎨', color=>'#8a6fc4', age=>22,
  level=>'B1', voice=>'en-GB', city=>'Brighton', cityTr=>'Brighton',
  job=>'a psychology student', jobTr=>'psikoloji öğrencisi', work=>'Sussex University', workTr=>'Sussex Üniversitesi',
  team=>'Brighton', player=>'Kaoru Mitoma',
  drink=>'an iced latte', drinkTr=>'buzlu latte', food=>'a veggie burger', foodTr=>'sebzeli burger',
  breakfast=>'granola with yoghurt', breakfastTr=>'yoğurtlu granola',
  pet=>'a goldfish called Freud', petTr=>'Freud adında bir japon balığı',
  family=>'a twin brother called Sam', familyTr=>'Sam adında ikiz kardeşi',
  hobby=>'painting', hobbyTr=>'resim yapmak',
  music=>'Arctic Monkeys', musicTr=>'Arctic Monkeys', film=>'Amélie', series=>'Sex Education',
  dream=>'to become a therapist', dreamTr=>'terapist olmak',
  place=>'Iceland', placeTr=>'İzlanda', lastHol=>'Lisbon', lastHolTr=>'Lizbon',
  transport=>'the bus', transportTr=>'otobüs', weather=>'windy beach days', weatherTr=>'rüzgarlı sahil günleri',
  phrase=>'Honestly, same.', phraseTr=>'Cidden, ben de.', style=>'thoughtful',
  bio=>'Sahil kasabasında yaşayan psikoloji öğrencisi. İnsanları merak eder, çok soru sorar.'
},
{
  id=>'marcus', name=>'Marcus', full=>'Marcus Reed', emoji=>'🚕', color=>'#d8a12a', age=>35,
  level=>'A2', voice=>'en-US', city=>'Chicago', cityTr=>'Chicago',
  job=>'a taxi driver', jobTr=>'taksi şoförü', work=>'Windy City Taxi', workTr=>'Windy City Taksi',
  team=>'Chicago Fire', player=>'Lionel Messi',
  drink=>'black coffee', drinkTr=>'sade kahve', food=>'deep dish pizza', foodTr=>'kalın hamurlu pizza',
  breakfast=>'bacon and eggs', breakfastTr=>'yumurta ve pastırma',
  pet=>q{no pet, my flat is too small}, petTr=>'evcil hayvanı yok, evi çok küçük',
  family=>q{a daughter called Zoe}, familyTr=>q{Zoe adında bir kızı},
  hobby=>'fixing old cars', hobbyTr=>'eski araba tamir etmek',
  music=>'blues', musicTr=>'blues', film=>'Taxi Driver', series=>'Breaking Bad',
  dream=>'to buy a food truck', dreamTr=>'bir yemek kamyonu almak',
  place=>'Alaska', placeTr=>'Alaska', lastHol=>'Las Vegas', lastHolTr=>'Las Vegas',
  transport=>'my yellow cab', transportTr=>'sarı taksisi', weather=>'cold windy days', weatherTr=>'soğuk rüzgarlı günler',
  phrase=>'Tell me about it.', phraseTr=>'Bana anlatma sen!', style=>'blunt',
  bio=>'Günde 12 saat taksi süren, dobra ve biraz yorgun bir adam. Futbolu pek anlamaz, şaka konusu olur.'
},
{
  id=>'aisha', name=>'Aisha', full=>'Aisha Khan', emoji=>'💻', color=>'#3f7fd4', age=>28,
  level=>'B2', voice=>'en-GB', city=>'Birmingham', cityTr=>'Birmingham',
  job=>'a software developer', jobTr=>'yazılım geliştirici', work=>'a startup called Cloudberry', workTr=>'Cloudberry adında bir girişim',
  team=>'Liverpool', player=>'Mohamed Salah',
  drink=>'green tea', drinkTr=>'yeşil çay', food=>'biryani', foodTr=>'biryani',
  breakfast=>'avocado toast', breakfastTr=>'avokadolu tost',
  pet=>'a cat called Pixel', petTr=>'Pixel adında bir kedisi',
  family=>'two little brothers', familyTr=>'iki küçük erkek kardeşi',
  hobby=>'video games', hobbyTr=>'video oyunları',
  music=>'lo-fi beats', musicTr=>'lo-fi müzik', film=>'Inception', series=>'Black Mirror',
  dream=>'to work remotely from Bali', dreamTr=>'Bali\'den uzaktan çalışmak',
  place=>'Bali', placeTr=>'Bali', lastHol=>'Istanbul', lastHolTr=>'İstanbul',
  transport=>'the train', transportTr=>'tren', weather=>'quiet cloudy days', weatherTr=>'sakin bulutlu günler',
  phrase=>'Makes sense.', phraseTr=>'Mantıklı.', style=>'precise',
  bio=>'Yazılımcı, sakin ve mantıklı. En zor İngilizceyi o konuşur (B2), teknoloji haberlerini takip eder.'
},
{
  id=>'tom', name=>'Tom', full=>'Tom Hayes', emoji=>'🔧', color=>'#4f8f52', age=>41,
  level=>'A2', voice=>'en-GB', city=>'Dublin', cityTr=>'Dublin',
  job=>'a plumber', jobTr=>'tesisatçı', work=>'Hayes Plumbing', workTr=>'Hayes Tesisat',
  team=>'Celtic', player=>'Roy Keane',
  drink=>'a pint of Guinness', drinkTr=>'bir bardak Guinness', food=>'Irish stew', foodTr=>'İrlanda güveci',
  breakfast=>'a full Irish breakfast', breakfastTr=>'tam İrlanda kahvaltısı',
  pet=>'a dog called Rusty', petTr=>'Rusty adında bir köpeği',
  family=>'three kids - Sean, Katie and baby Mark', familyTr=>'üç çocuğu: Sean, Katie ve bebek Mark',
  hobby=>'fishing', hobbyTr=>'balık tutmak',
  music=>'The Cranberries', musicTr=>'The Cranberries', film=>'The Commitments', series=>'Derry Girls',
  dream=>'to sleep for one whole weekend', dreamTr=>'bütün bir hafta sonu uyumak',
  place=>'Portugal', placeTr=>'Portekiz', lastHol=>'Galway', lastHolTr=>'Galway',
  transport=>'my white van', transportTr=>'beyaz kamyoneti', weather=>'a dry day', weatherTr=>'yağmursuz bir gün',
  phrase=>'Ah, sure look.', phraseTr=>'Eh işte, ne yapalım.', style=>'dry',
  bio=>'Üç çocuk babası İrlandalı tesisatçı. Yorgun ama esprili; her şeyi şakaya vurur.'
},
{
  id=>'grace', name=>'Grace', full=>'Grace Nolan', emoji=>'🧘', color=>'#59a86b', age=>33,
  level=>'B1', voice=>'en-AU', city=>'Melbourne', cityTr=>'Melbourne',
  job=>'a yoga teacher', jobTr=>'yoga eğitmeni', work=>'Sunrise Yoga Studio', workTr=>'Sunrise Yoga Stüdyosu',
  team=>'Melbourne Victory', player=>'Sam Kerr',
  drink=>'ginger tea', drinkTr=>'zencefil çayı', food=>'a poke bowl', foodTr=>'poke kase',
  breakfast=>'a smoothie bowl', breakfastTr=>'smoothie kase',
  pet=>'a dog called Luna', petTr=>'Luna adında bir köpeği',
  family=>q{my mum, who lives next door}, familyTr=>'yan kapıda oturan annesi',
  hobby=>'surfing', hobbyTr=>'sörf',
  music=>'acoustic guitar music', musicTr=>'akustik gitar müziği', film=>'Eat Pray Love', series=>"Chef's Table",
  dream=>'to run a retreat in Bali', dreamTr=>'Bali\'de bir inziva kampı açmak',
  place=>'India', placeTr=>'Hindistan', lastHol=>'Byron Bay', lastHolTr=>'Byron Bay',
  transport=>q{the tram}, transportTr=>q{tramvay}, weather=>'warm mornings', weatherTr=>'ılık sabahlar',
  phrase=>'Take a deep breath.', phraseTr=>'Derin bir nefes al.', style=>'calm',
  bio=>'Avustralyalı yoga eğitmeni. Sakin, pozitif; sağlık, uyku ve nefes üzerine konuşmayı sever.'
},
{
  id=>'daniel', name=>'Daniel', full=>'Daniel Osei', emoji=>'⚽', color=>'#2f7ac4', age=>26,
  level=>'A2', voice=>'en-GB', city=>'London', cityTr=>'Londra',
  job=>'a semi-pro footballer and coach', jobTr=>'yarı profesyonel futbolcu ve antrenör', work=>'Southwark FC', workTr=>'Southwark FC',
  team=>'Chelsea', player=>'Cole Palmer',
  drink=>'a protein shake', drinkTr=>'protein içeceği', food=>'jollof rice', foodTr=>'jollof pilavı',
  breakfast=>'oats and banana', breakfastTr=>'yulaf ve muz',
  pet=>q{no pet, I travel too much}, petTr=>q{evcil hayvanım yok, çok seyahat ediyorum},
  family=>q{my mum and two sisters in Accra}, familyTr=>'Accra\'daki annesi ve iki kız kardeşi',
  hobby=>'training every day', hobbyTr=>'her gün antrenman',
  music=>'afrobeats', musicTr=>'afrobeats', film=>'Coach Carter', series=>'Ted Lasso',
  dream=>'to play in the Premier League', dreamTr=>'Premier Lig\'de oynamak',
  place=>'Ghana', placeTr=>'Gana', lastHol=>'Accra', lastHolTr=>'Accra',
  transport=>'the bus to training', transportTr=>'antrenmana giden otobüs', weather=>'warm dry days', weatherTr=>'sıcak ve kuru günler',
  phrase=>"Let's go!", phraseTr=>'Hadi bakalım!', style=>'energetic',
  bio=>'Gana kökenli, Londra\'da futbol oynayan enerjik bir arkadaş. Konu döner dolaşır futbola gelir.'
},
{
  id=>'nina', name=>'Nina', full=>'Nina Petrova', emoji=>'🦷', color=>'#c45f8f', age=>29,
  level=>'B2', voice=>'en-US', city=>'Toronto', cityTr=>'Toronto',
  job=>'a dentist', jobTr=>'diş hekimi', work=>'Bright Smile Clinic', workTr=>'Bright Smile Kliniği',
  team=>'Toronto FC', player=>'Lorenzo Insigne',
  drink=>'black coffee', drinkTr=>'sade kahve', food=>'sushi', foodTr=>'suşi',
  breakfast=>'yoghurt and berries', breakfastTr=>'yoğurt ve meyve',
  pet=>'a cat called Mishka', petTr=>'Mishka adında bir kedisi',
  family=>q{my parents in Vancouver}, familyTr=>'Vancouver\'daki annesi ve babası',
  hobby=>'travelling', hobbyTr=>'seyahat etmek',
  music=>'jazz', musicTr=>'caz', film=>'Interstellar', series=>'Friends',
  dream=>'to visit every continent', dreamTr=>'bütün kıtaları görmek',
  place=>'Patagonia', placeTr=>'Patagonya', lastHol=>'Mexico', lastHolTr=>'Meksika',
  transport=>'my car', transportTr=>'arabası', weather=>'snowy evenings', weatherTr=>'karlı akşamlar',
  phrase=>'To be honest,', phraseTr=>'Açıkçası,', style=>'direct',
  bio=>'Torontolu diş hekimi. Dobra, planlı, gezmeye bayılır. İleri seviye İngilizce konuşur.'
},
{
  id=>'oliver', name=>'Oliver', full=>'Oliver Wright', emoji=>'🎮', color=>'#6b6bd8', age=>19,
  level=>'A1', voice=>'en-GB', city=>'Leeds', cityTr=>'Leeds',
  job=>'a student with a supermarket job', jobTr=>'markette çalışan öğrenci', work=>'FreshMart', workTr=>'FreshMart marketi',
  team=>'Leeds United', player=>'Patrick Bamford',
  drink=>'an energy drink', drinkTr=>'enerji içeceği', food=>'chicken nuggets', foodTr=>'tavuk nugget',
  breakfast=>'cereal', breakfastTr=>'mısır gevreği',
  pet=>'a hamster called Bolt', petTr=>'Bolt adında bir hamsteri',
  family=>q{my mum and my gran}, familyTr=>'annesi ve babaannesi',
  hobby=>'gaming', hobbyTr=>'oyun oynamak',
  music=>'rap', musicTr=>'rap', film=>'Spider-Man', series=>'Stranger Things',
  dream=>'to be a streamer', dreamTr=>'yayıncı olmak',
  place=>'Tokyo', placeTr=>'Tokyo', lastHol=>'Scarborough', lastHolTr=>'Scarborough',
  transport=>'my bike', transportTr=>'bisikleti', weather=>'snow days', weatherTr=>'karlı günler',
  phrase=>'Dunno, really.', phraseTr=>'Bilmem ki.', style=>'shy',
  bio=>'19 yaşında utangaç bir öğrenci. En basit İngilizceyi (A1) o konuşur, başlangıç için ideal.'
},
{
  id=>'maria', name=>'Maria', full=>'Maria Santos', emoji=>'📚', color=>'#c98a3a', age=>38,
  level=>'B1', voice=>'en-US', city=>'Boston', cityTr=>'Boston',
  job=>'a teacher', jobTr=>'öğretmen', work=>'Lincoln Middle School', workTr=>'Lincoln Ortaokulu',
  team=>'Benfica', player=>'Cristiano Ronaldo',
  drink=>'a milky coffee', drinkTr=>'sütlü kahve', food=>'bacalhau', foodTr=>'kurutulmuş morina',
  breakfast=>'a custard tart', breakfastTr=>'muhallebili tart',
  pet=>q{no pet, but a lot of plants}, petTr=>'evcil hayvanı yok ama bir sürü bitkisi var',
  family=>q{my husband Pedro and daughter Ines}, familyTr=>'eşi Pedro ve kızı Ines',
  hobby=>'gardening', hobbyTr=>'bahçe işleri',
  music=>'fado', musicTr=>'fado', film=>'The Sound of Music', series=>'The Crown',
  dream=>'to retire by the sea in Portugal', dreamTr=>'Portekiz\'de deniz kenarında emekli olmak',
  place=>'the Azores', placeTr=>'Azor Adaları', lastHol=>'Lisbon', lastHolTr=>'Lizbon',
  transport=>'the subway', transportTr=>'metro', weather=>'warm spring days', weatherTr=>'ılık bahar günleri',
  phrase=>'My goodness!', phraseTr=>'Aman Allahım!', style=>'warm',
  bio=>'Portekiz asıllı Amerikalı öğretmen. Sabırlı, açıklayıcı; öğrencilerinden ve ailesinden bahseder.'
},
{
  id=>'ryan', name=>'Ryan', full=>'Ryan Cole', emoji=>'🏋️', color=>'#d1502f', age=>31,
  level=>'A2', voice=>'en-GB', city=>'Cardiff', cityTr=>'Cardiff',
  job=>'a personal trainer', jobTr=>'kişisel antrenör', work=>'IronHouse Gym', workTr=>'IronHouse Spor Salonu',
  team=>'Cardiff City', player=>'Gareth Bale',
  drink=>'a protein shake', drinkTr=>'protein içeceği', food=>'grilled chicken and rice', foodTr=>'ızgara tavuk ve pilav',
  breakfast=>'eggs and spinach', breakfastTr=>'yumurta ve ıspanak',
  pet=>'a dog called Rocky', petTr=>'Rocky adında bir köpeği',
  family=>q{my girlfriend Megan}, familyTr=>'kız arkadaşı Megan',
  hobby=>'lifting weights', hobbyTr=>'ağırlık çalışmak',
  music=>'rock', musicTr=>'rock', film=>'Rocky', series=>'The Last Dance',
  dream=>'to open my own gym', dreamTr=>'kendi spor salonunu açmak',
  place=>'Thailand', placeTr=>'Tayland', lastHol=>'Tenerife', lastHolTr=>'Tenerife',
  transport=>'my van', transportTr=>'kamyoneti', weather=>'cold mornings for running', weatherTr=>'koşu için soğuk sabahlar',
  phrase=>'No excuses!', phraseTr=>'Bahane yok!', style=>'motivating',
  bio=>'Galli spor eğitmeni. Motive edici, disiplinli; spor, beslenme ve hedeflerden konuşur.'
},
{
  id=>'chloe', name=>'Chloe', full=>'Chloe Adams', emoji=>'🐱', color=>'#a05fc4', age=>25,
  level=>'B1', voice=>'en-GB', city=>'Bristol', cityTr=>'Bristol',
  job=>'a graphic designer', jobTr=>'grafik tasarımcı', work=>'a studio called Inkwell', workTr=>'Inkwell adında bir stüdyo',
  team=>'Bristol City', player=>'Jack Grealish',
  drink=>'an oat milk latte', drinkTr=>'yulaf sütlü latte', food=>'mac and cheese', foodTr=>'peynirli makarna',
  breakfast=>'just coffee, honestly', breakfastTr=>'açıkçası sadece kahve',
  pet=>'two cats, Mochi and Miso', petTr=>'Mochi ve Miso adında iki kedisi',
  family=>'an older sister called Ruby', familyTr=>'Ruby adında bir ablası',
  hobby=>'drawing comics', hobbyTr=>'çizgi roman çizmek',
  music=>'Taylor Swift', musicTr=>'Taylor Swift', film=>'The Grand Budapest Hotel', series=>'The Office',
  dream=>'to publish my own comic book', dreamTr=>'kendi çizgi romanını yayınlamak',
  place=>'Seoul', placeTr=>'Seul', lastHol=>'Amsterdam', lastHolTr=>'Amsterdam',
  transport=>q{the bus}, transportTr=>q{otobüs},
  weather=>'rainy days at home', weatherTr=>'evde geçen yağmurlu günler',
  phrase=>'Wow. Amazing.', phraseTr=>'Vay. Harika. (alaycı)', style=>'sarcastic',
  bio=>'Alaycı ama tatlı bir grafik tasarımcı. İki kedisi ve keskin bir mizah anlayışı var.'
},
{
  id=>'hassan', name=>'Hassan', full=>'Hassan Ali', emoji=>'📰', color=>'#4a7d6e', age=>45,
  level=>'B2', voice=>'en-GB', city=>'Dubai', cityTr=>'Dubai',
  job=>'a businessman', jobTr=>'iş insanı', work=>'Nile Trading', workTr=>'Nile Trading şirketi',
  team=>'Al Ahly', player=>'Mohamed Salah',
  drink=>'mint tea', drinkTr=>'naneli çay', food=>'koshari', foodTr=>'koshari',
  breakfast=>'foul and falafel', breakfastTr=>'ful ve falafel',
  pet=>q{no pet, but my son wants a cat}, petTr=>q{evcil hayvanım yok ama oğlum kedi istiyor},
  family=>q{my wife Layla and three children}, familyTr=>'eşi Layla ve üç çocuğu',
  hobby=>'reading the news', hobbyTr=>'haber okumak',
  music=>'classical Arabic music', musicTr=>'klasik Arap müziği', film=>'The Godfather', series=>'history documentaries',
  dream=>'to build a school in Cairo', dreamTr=>'Kahire\'de bir okul yaptırmak',
  place=>'Japan', placeTr=>'Japonya', lastHol=>'Cairo', lastHolTr=>'Kahire',
  transport=>'my car', transportTr=>'arabası', weather=>'cool desert evenings', weatherTr=>'serin çöl akşamları',
  phrase=>'Indeed.', phraseTr=>'Kesinlikle.', style=>'formal',
  bio=>'Mısır asıllı, Dubai\'de yaşayan iş insanı. Resmi ve düzgün İngilizce konuşur, haberleri kaçırmaz.'
},
{
  id=>'lucy', name=>'Lucy', full=>'Lucy Turner', emoji=>'💇', color=>'#d4568c', age=>36,
  level=>'A2', voice=>'en-GB', city=>'Liverpool', cityTr=>'Liverpool',
  job=>'a hairdresser', jobTr=>'kuaför', work=>'Curl Up Salon', workTr=>'Curl Up Kuaför',
  team=>'Everton', player=>'Dominic Calvert-Lewin',
  drink=>'a glass of prosecco', drinkTr=>'bir kadeh prosecco', food=>'a Sunday roast', foodTr=>'pazar kızartması',
  breakfast=>'toast and tea', breakfastTr=>'tost ve çay',
  pet=>'a little dog called Coco', petTr=>'Coco adında küçük bir köpeği',
  family=>'two teenage daughters', familyTr=>'iki ergen kızı',
  hobby=>'dancing', hobbyTr=>'dans etmek',
  music=>'pop music', musicTr=>'pop müzik', film=>'Dirty Dancing', series=>'Love Island',
  dream=>'to open my own salon in the city centre', dreamTr=>'şehir merkezinde kendi kuaförünü açmak',
  place=>'Ibiza', placeTr=>'İbiza', lastHol=>'Benidorm', lastHolTr=>'Benidorm',
  transport=>'my little red car', transportTr=>'küçük kırmızı arabası', weather=>'sunny Saturdays', weatherTr=>'güneşli cumartesiler',
  phrase=>"You'll never guess what!", phraseTr=>'Ne olduğunu asla tahmin edemezsin!', style=>'chatty',
  bio=>'Liverpoollu kuaför. Çenesi hiç durmaz, herkesin haberini bilir; Everton\'ın acısını çeker.'
},
{
  id=>'ben', name=>'Ben', full=>'Ben Foster', emoji=>'🌳', color=>'#6b8f3f', age=>52,
  level=>'B2', voice=>'en-GB', city=>'Newcastle', cityTr=>'Newcastle',
  job=>q{a museum guide}, jobTr=>q{müze rehberi}, work=>q{the city museum}, workTr=>q{şehir müzesi},
  team=>'Newcastle United', player=>'Alan Shearer',
  drink=>'a strong cup of tea', drinkTr=>'demli bir fincan çay', food=>'steak pie', foodTr=>'etli börek',
  breakfast=>'porridge, every single day', breakfastTr=>'her gün yulaf lapası',
  pet=>'an old dog called Duke', petTr=>'Duke adında yaşlı bir köpeği',
  family=>q{my wife Carol and two grown-up sons}, familyTr=>'eşi Carol ve yetişkin iki oğlu',
  hobby=>'gardening and history books', hobbyTr=>'bahçe işleri ve tarih kitapları',
  music=>'The Beatles', musicTr=>'The Beatles', film=>'Casablanca', series=>'documentaries',
  dream=>'to write a book about my city', dreamTr=>'şehri hakkında bir kitap yazmak',
  place=>'Scotland', placeTr=>'İskoçya', lastHol=>'the Lake District', lastHolTr=>'Göller Bölgesi',
  transport=>'my old Land Rover', transportTr=>'eski Land Rover\'ı', weather=>'crisp autumn mornings', weatherTr=>'serin sonbahar sabahları',
  phrase=>'Back in my day...', phraseTr=>'Bizim zamanımızda...', style=>'storyteller',
  bio=>'Emekli tarih öğretmeni. Hikaye anlatmayı sever, haberleri yorumlar, zengin bir İngilizcesi var.'
},
{
  id=>'yuki', name=>'Yuki', full=>'Yuki Tanaka', emoji=>'📷', color=>'#5f9bc4', age=>27,
  level=>'B1', voice=>'en-US', city=>'Vancouver', cityTr=>'Vancouver',
  job=>'a photographer', jobTr=>'fotoğrafçı', work=>q{a small photo studio}, workTr=>q{küçük bir fotoğraf stüdyosu},
  team=>'Vancouver Whitecaps', player=>'Takefusa Kubo',
  drink=>'matcha', drinkTr=>'matcha', food=>'ramen', foodTr=>'ramen',
  breakfast=>'rice and miso soup', breakfastTr=>'pirinç ve miso çorbası',
  pet=>q{no pet, I am away too often}, petTr=>q{evcil hayvanım yok, çok sık seyahatteyim},
  family=>q{my grandmother in Kyoto}, familyTr=>'Kyoto\'daki babaannesi',
  hobby=>'hiking with my camera', hobbyTr=>'fotoğraf makinesiyle doğa yürüyüşü',
  music=>'piano music', musicTr=>'piyano müziği', film=>'Spirited Away', series=>'nature documentaries',
  dream=>'to publish a photo book', dreamTr=>'bir fotoğraf kitabı yayınlamak',
  place=>'Iceland', placeTr=>'İzlanda', lastHol=>'Kyoto', lastHolTr=>'Kyoto',
  transport=>'the ferry and my bike', transportTr=>'vapur ve bisikleti', weather=>'foggy mornings', weatherTr=>'sisli sabahlar',
  phrase=>"That's beautiful.", phraseTr=>'Bu çok güzel.', style=>'quiet',
  bio=>'Japon asıllı Kanadalı fotoğrafçı. Sessiz, gözlemci; doğa, ışık ve seyahatten konuşur.'
},
{
  id=>'sam', name=>'Sam', full=>'Sam Okoro', emoji=>'🎧', color=>'#c4a02f', age=>23,
  level=>'A2', voice=>'en-GB', city=>'Manchester', cityTr=>'Manchester',
  job=>'a DJ and music producer', jobTr=>'DJ ve müzik yapımcısı', work=>'clubs around the city', workTr=>'şehirdeki kulüpler',
  team=>'Manchester United', player=>'Marcus Rashford',
  drink=>'bubble tea', drinkTr=>'bubble tea', food=>'suya', foodTr=>'baharatlı ızgara et (suya)',
  breakfast=>'plantain and eggs', breakfastTr=>'muz ve yumurta',
  pet=>q{no pet, but my cousin wants a dog}, petTr=>q{evcil hayvanım yok ama kuzenim köpek istiyor},
  family=>q{my cousin Tunde, who lives with me}, familyTr=>'onunla yaşayan kuzeni Tunde',
  hobby=>'making beats at night', hobbyTr=>'geceleri müzik yapmak',
  music=>'afrobeats and house', musicTr=>'afrobeats ve house', film=>'Black Panther', series=>'Top Boy',
  dream=>'to play at a big festival', dreamTr=>'büyük bir festivalde çalmak',
  place=>'Lagos', placeTr=>'Lagos', lastHol=>'Ibiza', lastHolTr=>'İbiza',
  transport=>'an Uber, always late', transportTr=>'Uber, hep geç kalır', weather=>'warm summer nights', weatherTr=>'sıcak yaz geceleri',
  phrase=>"That's mad, bro.", phraseTr=>'Bu çılgınca, kanka.', style=>'slang',
  bio=>'Nijerya asıllı genç DJ. Sokak ağzı ve günlük kısaltmalarla konuşur, geceleri çalışır.'
},
{
  id=>'hannah', name=>'Hannah', full=>'Hannah Brooks', emoji=>'🐶', color=>'#4a9c8c', age=>30,
  level=>'B1', voice=>'en-GB', city=>'Edinburgh', cityTr=>'Edinburgh',
  job=>'a vet', jobTr=>'veteriner', work=>'Old Town Vets', workTr=>'Old Town Veteriner Kliniği',
  team=>'Scotland', player=>'Andy Robertson',
  drink=>'hot chocolate', drinkTr=>'sıcak çikolata', food=>'haggis', foodTr=>'haggis',
  breakfast=>'eggs on toast', breakfastTr=>'tost üstünde yumurta',
  pet=>'three dogs and a rabbit', petTr=>'üç köpeği ve bir tavşanı',
  family=>q{my flatmate Rosie}, familyTr=>'ev arkadaşı Rosie',
  hobby=>'hiking in the Highlands', hobbyTr=>'dağlarda yürüyüş',
  music=>'folk music', musicTr=>'folk müzik', film=>'Braveheart', series=>'All Creatures Great and Small',
  dream=>'to open an animal shelter', dreamTr=>'bir hayvan barınağı açmak',
  place=>'Norway', placeTr=>'Norveç', lastHol=>'the Isle of Skye', lastHolTr=>'Skye Adası',
  transport=>'my muddy jeep', transportTr=>'çamurlu ciparanı', weather=>'cold clear mornings', weatherTr=>'soğuk ve açık sabahlar',
  phrase=>'Aye, definitely.', phraseTr=>'Evet, kesinlikle.', style=>'friendly',
  bio=>'İskoç veteriner. Hayvanlar, doğa yürüyüşleri ve soğuk havalar hakkında konuşur.'
},
{
  id=>'diego', name=>'Diego', full=>'Diego Alvarez', emoji=>'🥘', color=>'#d47a2f', age=>34,
  level=>'A2', voice=>'en-US', city=>'Miami', cityTr=>'Miami',
  job=>'a restaurant owner', jobTr=>'restoran sahibi', work=>'Casa Diego', workTr=>'Casa Diego restoranı',
  team=>'Real Madrid', player=>'Vinícius Júnior',
  drink=>'café con leche', drinkTr=>'sütlü kahve', food=>'paella', foodTr=>'paella',
  breakfast=>'toast with tomato', breakfastTr=>'domatesli tost',
  pet=>'a dog called Toro', petTr=>'Toro adında bir köpeği',
  family=>q{my brother Javi, who works with me}, familyTr=>'onunla çalışan kardeşi Javi',
  hobby=>'dancing salsa', hobbyTr=>'salsa dansı',
  music=>'reggaeton', musicTr=>'reggaeton', film=>'Fast & Furious', series=>'Money Heist',
  dream=>'to open a second restaurant', dreamTr=>'ikinci bir restoran açmak',
  place=>'Cuba', placeTr=>'Küba', lastHol=>'Madrid', lastHolTr=>'Madrid',
  transport=>'my motorbike', transportTr=>'motosikleti', weather=>'hot beach days', weatherTr=>'sıcak sahil günleri',
  phrase=>'Vamos!', phraseTr=>'Hadi!', style=>'passionate',
  bio=>'İspanyol asıllı Miamili restoran sahibi. Ateşli, misafirperver; yemek ve futbol için yaşar.'
},
{
  id=>'ella', name=>'Ella', full=>'Ella Fisher', emoji=>'🎒', color=>'#3fa8b8', age=>21,
  level=>'A2', voice=>'en-AU', city=>'Auckland', cityTr=>'Auckland',
  job=>'a backpacker and part-time waitress', jobTr=>'sırt çantalı gezgin ve yarı zamanlı garson', work=>'hostels and cafés', workTr=>'hosteller ve kafeler',
  team=>'Auckland FC', player=>'Kylian Mbappé',
  drink=>'fresh orange juice', drinkTr=>'taze portakal suyu', food=>'fish tacos', foodTr=>'balıklı taco',
  breakfast=>'banana pancakes', breakfastTr=>'muzlu krep',
  pet=>q{no pet, I am always moving}, petTr=>q{evcil hayvanım yok, sürekli yollardayım},
  family=>q{my parents in Wellington}, familyTr=>'Wellington\'daki ailesi',
  hobby=>'surfing', hobbyTr=>'sörf',
  music=>'reggae', musicTr=>'reggae', film=>'Into the Wild', series=>'travel vlogs',
  dream=>'to travel for two more years', dreamTr=>'iki yıl daha gezmek',
  place=>'Peru', placeTr=>'Peru', lastHol=>'Bali', lastHolTr=>'Bali',
  transport=>q{night buses}, transportTr=>q{gece otobüsleri}, weather=>'sunny beach days', weatherTr=>'güneşli sahil günleri',
  phrase=>'No worries!', phraseTr=>'Sorun değil!', style=>'easygoing',
  bio=>'Yeni Zelandalı gezgin. Dünyayı dolaşıyor, her hafta başka bir şehirden yazıyor.'
}
]
