use utf8;
[
{
 id=>"hotel", title=>"Tatilde otelde", emoji=>"🏖️", cat=>"Tatil ve Seyahat",
 intro=>"{name} ile tatildesiniz, otelde ilk gün.",
 beats=>[
  { f=>[ ["We are here! Look at the sea from the window!","Geldik! Pencereden denize bak!"],
         ["We made it. Come here and look at this view, it was worth every hour of travel.","Başardık. Gel şu manzaraya bak, yolculuğun her saatine değdi."] ],
    o=>[ [ ["Wow! It is beautiful!","Vay! Çok güzel!"], ["This view is amazing.","Bu manzara harika."] ],
         [ ["I am so tired from the journey.","Yolculuktan çok yoruldum."], ["I need a shower first.","Önce duşa ihtiyacım var."] ],
         [ ["Which bed is mine?","Hangi yatak benim?"], ["Where do I put my suitcase?","Valizimi nereye koyayım?"] ] ] },
  { f=>[ ["Breakfast is at eight. Do not be late!","Kahvaltı sekizde. Geç kalma!"],
         ["Breakfast finishes at ten, but the good things go by half past eight.","Kahvaltı onda bitiyor ama güzel şeyler sekiz buçukta tükeniyor."] ],
    o=>[ [ ["Okay, I will wake up early.","Tamam, erken kalkacağım."], ["Eight is fine for me.","Sekiz bana uyar."] ],
         [ ["Eight is too early on holiday!","Tatilde sekiz çok erken!"], ["I want to sleep late.","Geç uyumak istiyorum."] ],
         [ ["Please wake me up.","Lütfen beni uyandır."], ["I will set an alarm.","Alarm kuracağım."] ] ] },
  { f=>[ ["What do you want to do first? Beach or town?","Önce ne yapmak istersin? Sahil mi kasaba mı?"],
         ["We have the whole afternoon. Beach first, or should we explore the town?","Bütün öğleden sonra bizim. Önce sahil mi, yoksa kasabayı mı gezelim?"] ],
    o=>[ [ ["Beach! I want to swim.","Sahil! Yüzmek istiyorum."], ["Straight to the water, please.","Direkt suya, lütfen."] ],
         [ ["Let us see the town first.","Önce kasabayı görelim."], ["I want to walk around.","Etrafta dolaşmak istiyorum."] ],
         [ ["Can we eat first?","Önce yemek yiyebilir miyiz?"], ["I am hungry, honestly.","Açıkçası açım."] ] ] },
  { f=>[ ["Did you bring sun cream? The sun is strong here.","Güneş kremi getirdin mi? Buranın güneşi güçlü."],
         ["Please tell me you brought sun cream. The sun here is much stronger than at home.","Lütfen güneş kremi getirdiğini söyle. Buranın güneşi evdekinden çok daha güçlü."] ],
    o=>[ [ ["Yes, I brought some.","Evet, getirdim."], ["Of course, it is in my bag.","Tabii, çantamda."] ],
         [ ["No, I forgot it!","Hayır, unuttum!"], ["I need to buy some.","Almam lazım."] ],
         [ ["Can I use yours?","Seninkini kullanabilir miyim?"], ["Where can we buy some?","Nereden alabiliriz?"] ] ] },
  { f=>[ ["This place reminds me of {lastHol}.","Burası bana {lastHol} hatırlatıyor."],
         ["Something about this place really reminds me of {lastHol}, the light maybe.","Buranın bir yanı bana {lastHol} çok hatırlatıyor, belki ışığı."] ],
    o=>[ [ ["Was that place nice too?","Orası da güzel miydi?"], ["Which one do you prefer?","Hangisini tercih edersin?"] ],
         [ ["You travel a lot!","Çok seyahat ediyorsun!"], ["How many countries have you seen?","Kaç ülke gördün?"] ],
         [ ["This is my first time abroad.","Bu benim ilk yurt dışım."], ["I do not travel often.","Sık seyahat etmem."] ] ] },
  { f=>[ ["Let us try the local food tonight.","Bu akşam yerel yemekleri deneyelim."],
         ["Tonight we eat properly. No tourist restaurants, we find where the locals go.","Bu akşam adam gibi yiyeceğiz. Turist restoranı yok, yerlilerin gittiği yeri buluruz."] ],
    o=>[ [ ["Yes! I want to try everything.","Evet! Her şeyi denemek istiyorum."], ["I love trying new food.","Yeni yemek denemeye bayılırım."] ],
         [ ["I am a bit careful with food.","Yemek konusunda biraz dikkatliyim."], ["My stomach is sensitive.","Midem hassas."] ],
         [ ["Do you know a good place?","Güzel bir yer biliyor musun?"], ["Let us ask at reception.","Resepsiyona soralım."] ] ] },
  { f=>[ ["The water is warm. Are you coming in?","Su ılık. Geliyor musun?"],
         ["I have tested it, the water is perfect. Are you coming in or just watching?","Denedim, su mükemmel. Geliyor musun yoksa sadece izleyecek misin?"] ],
    o=>[ [ ["Yes, wait for me!","Evet, beni bekle!"], ["I am coming!","Geliyorum!"] ],
         [ ["I cannot swim well.","İyi yüzemiyorum."], ["I will stay near the beach.","Sahile yakın duracağım."] ],
         [ ["Later. I want to read now.","Sonra. Şimdi kitap okumak istiyorum."], ["I am enjoying the sun.","Güneşin tadını çıkarıyorum."] ] ] },
  { f=>[ ["Take a photo of me! Send it to {family}.","Fotoğrafımı çek! {family} gönder."],
         ["Quick, take a photo. I promised {family} that I would send pictures every day.","Çabuk, bir fotoğraf çek. {family} her gün fotoğraf göndereceğime söz verdim."] ],
    o=>[ [ ["Okay, smile!","Tamam, gülümse!"], ["Ready? One, two, three!","Hazır mısın? Bir, iki, üç!"] ],
         [ ["Take one of me too.","Benim de bir tane çek."], ["Let us take a photo together.","Birlikte fotoğraf çekilelim."] ],
         [ ["I hate photos of myself.","Kendi fotoğraflarımdan nefret ederim."], ["Do not put it on the internet!","Onu internete koyma!"] ] ] },
  { f=>[ ["I do not want to go home. Can we stay?","Eve gitmek istemiyorum. Kalabilir miyiz?"],
         ["Honestly, I could live here. Do we really have to go back on Sunday?","Cidden burada yaşayabilirim. Pazar günü gerçekten dönmek zorunda mıyız?"] ],
    o=>[ [ ["Me neither! It is so nice here.","Ben de istemiyorum! Burası çok güzel."], ["I wish we had more days.","Keşke daha çok günümüz olsa."] ],
         [ ["I miss my bed a bit.","Yatağımı biraz özledim."], ["Home is nice too.","Ev de güzel."] ],
         [ ["We can come back next year.","Gelecek yıl tekrar gelebiliriz."], ["Let us plan the next one!","Bir sonrakini planlayalım!"] ] ] },
  { f=>[ ["Thank you for coming with me. {phrase}","Benimle geldiğin için teşekkürler. {phrase}"],
         ["Seriously, thank you for coming. This trip would not have been the same alone. {phrase}","Cidden, geldiğin için sağ ol. Bu gezi yalnız aynı olmazdı. {phrase}"] ],
    o=>[ [ ["Thank you for inviting me!","Beni davet ettiğin için teşekkürler!"], ["I had the best time.","Harika vakit geçirdim."] ],
         [ ["We are a good travel team.","İyi bir seyahat ekibiyiz."], ["Same place next year?","Gelecek yıl aynı yer?"] ],
         [ ["I will never forget this.","Bunu asla unutmayacağım."], ["Best holiday of my life.","Hayatımın en güzel tatili."] ] ] }
 ]
},
{
 id=>"airport", title=>"Havaalanında", emoji=>"✈️", cat=>"Tatil ve Seyahat",
 intro=>"{name} ile havaalanında uçağı bekliyorsunuz.",
 beats=>[
  { f=>[ ["We are early. The flight is in three hours.","Erken geldik. Uçuş üç saat sonra."],
         ["We are ridiculously early, as usual. Three hours until boarding.","Her zamanki gibi saçma derecede erkenciyiz. Uçağa üç saat var."] ],
    o=>[ [ ["Better early than late!","Geç kalmaktansa erken olsun!"], ["I like being early.","Erken olmayı severim."] ],
         [ ["Three hours is too long!","Üç saat çok uzun!"], ["What do we do now?","Şimdi ne yapacağız?"] ],
         [ ["Let us find a café.","Bir kafe bulalım."], ["I need coffee.","Kahve lazım bana."] ] ] },
  { f=>[ ["Do you have your passport and ticket?","Pasaportun ve biletin yanında mı?"],
         ["Quick check before we go through: passport, ticket, phone, wallet?","Geçmeden önce hızlı kontrol: pasaport, bilet, telefon, cüzdan?"] ],
    o=>[ [ ["Yes, everything is here.","Evet, hepsi burada."], ["All in my bag.","Hepsi çantamda."] ],
         [ ["Wait, let me check!","Dur, bir bakayım!"], ["Oh no, where is my passport?","Eyvah, pasaportum nerede?"] ],
         [ ["My ticket is on my phone.","Biletim telefonumda."], ["I printed everything.","Her şeyi yazdırdım."] ] ] },
  { f=>[ ["My bag is too heavy. I always take too much.","Çantam çok ağır. Hep fazla eşya alıyorum."],
         ["My suitcase is definitely over the limit. I never learn.","Valizim kesin limitin üstünde. Hiç ders almıyorum."] ],
    o=>[ [ ["Mine is light. I packed little.","Benimki hafif. Az eşya koydum."], ["I only have hand luggage.","Sadece el bagajım var."] ],
         [ ["Do you want me to carry something?","Bir şey taşımamı ister misin?"], ["Put something in my bag.","Bir şeyleri benim çantama koy."] ],
         [ ["How much can we take?","Ne kadar alabiliyoruz?"], ["What is the weight limit?","Ağırlık limiti ne?"] ] ] },
  { f=>[ ["Do you like flying? I am always a bit nervous.","Uçmayı sever misin? Ben hep biraz gerginimdir."],
         ["Are you a nervous flyer? I pretend to be calm but I am not.","Uçakta gergin olur musun? Sakinmiş gibi yapıyorum ama değilim."] ],
    o=>[ [ ["I love flying!","Uçmaya bayılırım!"], ["No problem for me.","Benim için sorun değil."] ],
         [ ["I am scared of flying.","Uçmaktan korkarım."], ["I hate take off.","Kalkıştan nefret ederim."] ],
         [ ["I sleep on planes.","Uçakta uyurum."], ["I just listen to music.","Sadece müzik dinlerim."] ] ] },
  { f=>[ ["I usually listen to {music} on the plane.","Uçakta genelde {music} dinlerim."],
         ["My flight routine is simple: window seat, {music}, and no talking.","Uçuş rutinim basit: cam kenarı, {music} ve konuşmak yok."] ],
    o=>[ [ ["I like that music too.","Ben de o müziği severim."], ["Send me a song later.","Sonra bana bir şarkı gönder."] ],
         [ ["I prefer podcasts.","Ben podcast tercih ederim."], ["I read a book instead.","Ben onun yerine kitap okurum."] ],
         [ ["Window or aisle seat?","Cam kenarı mı koridor mu?"], ["I always want the window.","Hep cam kenarını isterim."] ] ] },
  { f=>[ ["Look, the flight is delayed. Thirty minutes.","Bak, uçuş rötarlı. Otuz dakika."],
         ["Of course. Delayed by thirty minutes, according to the board.","Tabii ki. Panoya göre otuz dakika rötarlı."] ],
    o=>[ [ ["Oh no! Not again.","Olamaz! Yine mi."], ["That is annoying.","Bu can sıkıcı."] ],
         [ ["It is only thirty minutes.","Sadece otuz dakika."], ["That is not too bad.","O kadar da kötü değil."] ],
         [ ["Let us get something to eat.","Bir şeyler yiyelim."], ["More time in the shops!","Mağazalarda daha çok zaman!"] ] ] },
  { f=>[ ["Airport food is so expensive!","Havaalanı yemekleri çok pahalı!"],
         ["Have you seen these prices? Airport food costs three times more.","Şu fiyatları gördün mü? Havaalanı yemeği üç kat pahalı."] ],
    o=>[ [ ["You are right. It is crazy.","Haklısın. Delilik."], ["Everything costs double.","Her şey iki katı."] ],
         [ ["I brought sandwiches!","Ben sandviç getirdim!"], ["I have snacks in my bag.","Çantamda atıştırmalık var."] ],
         [ ["I will wait until the plane.","Uçağa kadar bekleyeceğim."], ["Do they feed us on board?","Uçakta yemek veriyorlar mı?"] ] ] },
  { f=>[ ["What is the first thing you want to do there?","Orada ilk ne yapmak istersin?"],
         ["When we land, what is the very first thing you want to do?","İndiğimizde ilk yapmak istediğin şey ne?"] ],
    o=>[ [ ["Eat! Definitely eat.","Yemek! Kesinlikle yemek."], ["Find a restaurant.","Bir restoran bulmak."] ],
         [ ["Sleep for two hours.","İki saat uyumak."], ["Go to the hotel and rest.","Otele gidip dinlenmek."] ],
         [ ["Walk around the city.","Şehirde dolaşmak."], ["See the sea!","Denizi görmek!"] ] ] },
  { f=>[ ["They are calling our gate. Come on!","Kapımızı çağırıyorlar. Hadi!"],
         ["That is us, gate twelve. Grab your things, let us go.","Bu biziz, on ikinci kapı. Eşyalarını al, gidelim."] ],
    o=>[ [ ["Finally! Let us go.","Nihayet! Gidelim."], ["I am ready.","Hazırım."] ],
         [ ["Wait, I need the toilet!","Dur, tuvalete gitmem lazım!"], ["Give me two minutes.","Bana iki dakika ver."] ],
         [ ["Where is my boarding pass?","Biniş kartım nerede?"], ["Which gate did you say?","Hangi kapı demiştin?"] ] ] },
  { f=>[ ["Sit next to me. It is more fun. {phrase}","Yanıma otur. Daha eğlenceli olur. {phrase}"],
         ["Swap with someone so we can sit together, the flight goes faster. {phrase}","Biriyle yer değiş de yan yana oturalım, uçuş daha hızlı geçer. {phrase}"] ],
    o=>[ [ ["Okay, I will ask someone.","Tamam, birine sorarım."], ["Good idea!","İyi fikir!"] ],
         [ ["My seat is 14B. And yours?","Benim koltuğum 14B. Seninki?"], ["Are we close to each other?","Birbirimize yakın mıyız?"] ],
         [ ["I want to sleep on the flight.","Uçuşta uyumak istiyorum."], ["Let us talk the whole way!","Bütün yol boyunca konuşalım!"] ] ] }
 ]
},
{
 id=>"matchday", title=>"Maç izlerken", emoji=>"⚽", cat=>"Futbol",
 intro=>"{name} ile futbol maçı izliyorsunuz.",
 beats=>[
  { f=>[ ["The match starts in ten minutes! Sit down.","Maça on dakika var! Otur."],
         ["Right, kick off in ten minutes. Phones away, this is important.","Tamam, on dakikaya başlıyor. Telefonlar bir kenara, bu önemli."] ],
    o=>[ [ ["Who is playing?","Kimler oynuyor?"], ["Which teams are they?","Hangi takımlar?"] ],
         [ ["I am ready!","Hazırım!"], ["Let us watch!","İzleyelim!"] ],
         [ ["I do not know much about football.","Futboldan pek anlamam."], ["Explain the rules to me.","Bana kuralları anlat."] ] ] },
  { f=>[ ["{team} is my team. I have supported them since I was a child.","{team} benim takımım. Çocukluğumdan beri tutuyorum."],
         ["I support {team}, and I have done since I was about six years old.","{team} tutuyorum, altı yaşımdan beri de öyle."] ],
    o=>[ [ ["Are they a good team?","İyi bir takım mı?"], ["Are they top of the league?","Ligde birinci mi?"] ],
         [ ["Why that team?","Neden o takım?"], ["Who made you support them?","Kim seni onlara tutturdu?"] ],
         [ ["I support a different team.","Ben başka bir takım tutuyorum."], ["My team is Galatasaray.","Benim takımım Galatasaray."] ] ] },
  { f=>[ ["{player} is the best player. Watch that number ten.","{player} en iyi oyuncu. Şu on numarayı izle."],
         ["Keep your eye on {player}. When that player is good, we win. It is that simple.","Gözün {player} üzerinde olsun. O oyuncu iyiyse kazanırız. Bu kadar basit."] ],
    o=>[ [ ["Is that player fast?","O oyuncu hızlı mı?"], ["What position is that?","O hangi mevki?"] ],
         [ ["I have heard that name!","O ismi duydum!"], ["That player is famous, right?","O oyuncu ünlü, değil mi?"] ],
         [ ["I prefer another player.","Ben başka bir oyuncuyu tercih ederim."], ["Messi is the best for me.","Bana göre en iyisi Messi."] ] ] },
  { f=>[ ["Goal! Did you see that? What a goal!","Gol! Gördün mü? Ne gol ama!"],
         ["GOAL! Get in! Did you see that shot? Unbelievable!","GOOOL! İşte bu! O şutu gördün mü? İnanılmaz!"] ],
    o=>[ [ ["Yes! That was great!","Evet! Harikaydı!"], ["Amazing goal!","Muhteşem gol!"] ],
         [ ["I missed it! Show me again.","Kaçırdım! Tekrar göster."], ["Is there a replay?","Tekrarı var mı?"] ],
         [ ["Who scored?","Kim attı?"], ["What is the score now?","Skor kaç oldu?"] ] ] },
  { f=>[ ["The referee is terrible today!","Hakem bugün berbat!"],
         ["That referee is having a shocking game. That was never a foul.","Hakem berbat bir maç çıkarıyor. O asla faul değildi."] ],
    o=>[ [ ["I agree, that was not a foul.","Katılıyorum, faul değildi."], ["Bad decision!","Kötü karar!"] ],
         [ ["I think he was right.","Bence haklıydı."], ["It looked like a foul to me.","Bana faul gibi göründü."] ],
         [ ["Calm down!","Sakin ol!"], ["It is only a game.","Sadece bir oyun."] ] ] },
  { f=>[ ["Do you play football, or only watch?","Futbol oynuyor musun, yoksa sadece izliyor musun?"],
         ["Did you ever play yourself, or have you always been a watcher?","Hiç kendin oynadın mı, yoksa hep izleyici mi oldun?"] ],
    o=>[ [ ["I played at school.","Okulda oynardım."], ["I used to play a lot.","Eskiden çok oynardım."] ],
         [ ["I only watch.","Sadece izlerim."], ["I am too slow to play!","Oynamak için çok yavaşım!"] ],
         [ ["I play every week.","Her hafta oynarım."], ["I play with my friends.","Arkadaşlarımla oynuyorum."] ] ] },
  { f=>[ ["Have you been to a stadium? The feeling is different.","Hiç stada gittin mi? Hissi bambaşka."],
         ["Watching at home is fine, but a stadium is a completely different experience.","Evde izlemek iyi ama stat tamamen başka bir deneyim."] ],
    o=>[ [ ["Yes, once. It was loud!","Evet, bir kez. Çok gürültülüydü!"], ["I have been a few times.","Birkaç kez gittim."] ],
         [ ["No, never.","Hayır, hiç."], ["I want to go one day.","Bir gün gitmek istiyorum."] ],
         [ ["Take me to a match!","Beni bir maça götür!"], ["Are the tickets expensive?","Biletler pahalı mı?"] ] ] },
  { f=>[ ["Second half! We need one more goal.","İkinci yarı! Bir gole daha ihtiyacımız var."],
         ["Right, second half. One more goal and I can relax.","Tamam, ikinci yarı. Bir gol daha atarsak rahatlarım."] ],
    o=>[ [ ["I think you will win.","Bence kazanacaksınız."], ["You are playing well.","İyi oynuyorsunuz."] ],
         [ ["The other team is strong.","Diğer takım güçlü."], ["It will be difficult.","Zor olacak."] ],
         [ ["How long is left?","Ne kadar kaldı?"], ["What minute is it?","Kaçıncı dakika?"] ] ] },
  { f=>[ ["Full time! What a match!","Maç bitti! Ne maçtı ama!"],
         ["And that is full time. Honestly, what a game that was.","Ve maç bitti. Cidden, ne maçtı ama."] ],
    o=>[ [ ["Congratulations!","Tebrikler!"], ["Great result for you!","Senin için harika sonuç!"] ],
         [ ["Bad luck. Next time.","Şanssızlık. Sonraki sefere."] , ["Do not be sad.","Üzülme."] ],
         [ ["That was fun to watch!","İzlemesi eğlenceliydi!"], ["I enjoyed that.","Keyif aldım."] ] ] },
  { f=>[ ["Next match is on Sunday. Come again! {phrase}","Bir sonraki maç pazar. Yine gel! {phrase}"],
         ["Same time on Sunday for the next one? I will get the snacks in. {phrase}","Pazar günü aynı saatte bir sonraki maç? Atıştırmalıkları ben alırım. {phrase}"] ],
    o=>[ [ ["Yes, I will come!","Evet, geleceğim!"], ["Count me in.","Ben varım."] ],
         [ ["I am busy on Sunday.","Pazar meşgulüm."], ["Maybe the week after.","Belki bir sonraki hafta."] ],
         [ ["I will bring food this time.","Bu sefer yemeği ben getiririm."], ["Text me the time.","Saati bana yaz."] ] ] }
 ]
},
{
 id=>"footballtalk", title=>"Maç sonrası futbol muhabbeti", emoji=>"🏟️", cat=>"Futbol",
 intro=>"{name} futbol konuşmak istiyor.",
 beats=>[
  { f=>[ ["Did you see the game last night?","Dün geceki maçı gördün mü?"],
         ["Please tell me you watched the game last night. Everyone is talking about it.","Lütfen dün geceki maçı izlediğini söyle. Herkes onu konuşuyor."] ],
    o=>[ [ ["Yes, I watched it all.","Evet, hepsini izledim."], ["Of course I did!","Tabii ki izledim!"] ],
         [ ["No, I was working.","Hayır, çalışıyordum."], ["I missed it. What happened?","Kaçırdım. Ne oldu?"] ],
         [ ["I saw the goals online.","Golleri internette gördüm."], ["I only saw the score.","Sadece skoru gördüm."] ] ] },
  { f=>[ ["{team} played badly. I was angry all night.","{team} kötü oynadı. Bütün gece sinirliydim."],
         ["{team} were awful. I could not sleep afterwards, that is how bad it was.","{team} berbattı. Sonrasında uyuyamadım, o kadar kötüydü."] ],
    o=>[ [ ["What went wrong?","Ne ters gitti?"], ["Why did they play badly?","Neden kötü oynadılar?"] ],
         [ ["It is only one match.","Sadece bir maç."], ["Do not worry, next week is better.","Merak etme, haftaya daha iyi olur."] ],
         [ ["Football is not that important!","Futbol o kadar da önemli değil!"], ["It is just a game, {name}.","Sadece bir oyun {name}."] ] ] },
  { f=>[ ["I know it is only a game. But football is my life!","Biliyorum, sadece bir oyun. Ama futbol benim hayatım!"],
         ["I know, I know. It is only a game. But football is the most important unimportant thing in the world.","Biliyorum, biliyorum. Sadece bir oyun. Ama futbol dünyanın en önemli önemsiz şeyidir."] ],
    o=>[ [ ["I can see that!","Belli oluyor!"], ["You really love it.","Onu gerçekten seviyorsun."] ],
         [ ["I like football too, actually.","Aslında ben de futbolu severim."], ["I watch big matches only.","Sadece büyük maçları izlerim."] ],
         [ ["I prefer basketball.","Ben basketbolu tercih ederim."], ["Volleyball is my sport.","Benim sporum voleybol."] ] ] },
  { f=>[ ["{player} was the only good player.","Sadece {player} iyiydi."],
         ["The one player who came out of it well was {player}. Everyone else was hiding.","Maçtan yüzü ak çıkan tek oyuncu {player} oldu. Diğerleri saklandı."] ],
    o=>[ [ ["That player is really good.","O oyuncu gerçekten iyi."], ["I like watching that player.","O oyuncuyu izlemeyi seviyorum."] ],
         [ ["Was that player expensive?","O oyuncu pahalı mıydı?"], ["Will they stay at the club?","Kulüpte kalır mı?"] ],
         [ ["Who is the worst player then?","Peki en kötü oyuncu kim?"], ["Who should they sell?","Kimi satmalılar?"] ] ] },
  { f=>[ ["Who is the best player in the world for you?","Sana göre dünyanın en iyi oyuncusu kim?"],
         ["Settle this for me: who is the best player in the world right now?","Şunu bir karara bağla: şu an dünyanın en iyi oyuncusu kim?"] ],
    o=>[ [ ["Messi, for me.","Bana göre Messi."], ["It has to be Messi.","Messi olmalı."] ],
         [ ["Ronaldo, one hundred percent.","Yüzde yüz Ronaldo."], ["Ronaldo is the greatest.","En büyük Ronaldo."] ],
         [ ["A younger player, I think.","Bence daha genç bir oyuncu."], ["Mbappé or Haaland.","Mbappé ya da Haaland."] ] ] },
  { f=>[ ["Do you have a favourite team in your country?","Kendi ülkende favori bir takımın var mı?"],
         ["What about your own league? Do you have a team you follow at home?","Peki kendi liginiz? Ülkende takip ettiğin bir takım var mı?"] ],
    o=>[ [ ["Yes, I support Fenerbahçe.","Evet, Fenerbahçe tutuyorum."], ["I am a Galatasaray fan.","Galatasaray taraftarıyım."] ],
         [ ["Beşiktaş, since I was a kid.","Çocukluğumdan beri Beşiktaş."], ["Trabzonspor is my team.","Benim takımım Trabzonspor."] ],
         [ ["I do not follow a team.","Bir takım tutmuyorum."], ["I just watch the national team.","Sadece milli takımı izlerim."] ] ] },
  { f=>[ ["Turkish fans are famous. The atmosphere is crazy!","Türk taraftarlar meşhur. Atmosfer çılgın!"],
         ["I have seen videos of Turkish stadiums. The atmosphere looks absolutely incredible.","Türk statlarının videolarını gördüm. Atmosfer inanılmaz görünüyor."] ],
    o=>[ [ ["Yes, it is very loud!","Evet, çok gürültülü!"], ["The fans never stop singing.","Taraftarlar hiç susmaz."] ],
         [ ["You should come and see.","Gelip görmelisin."], ["I will take you one day.","Bir gün seni götürürüm."] ],
         [ ["Sometimes it is too much!","Bazen aşırı oluyor!"], ["It can be a bit crazy.","Biraz çılgın olabiliyor."] ] ] },
  { f=>[ ["Who will win the league this year?","Bu yıl ligi kim kazanır?"],
         ["Give me your prediction: who is winning the league this season?","Tahminini söyle: bu sezon ligi kim kazanır?"] ],
    o=>[ [ ["Your team, of course!","Tabii ki senin takımın!"], ["{team} will win it.","{team} kazanır."] ],
         [ ["I have no idea.","Hiçbir fikrim yok."], ["It is too early to say.","Söylemek için çok erken."] ],
         [ ["The rich clubs always win.","Hep zengin kulüpler kazanır."], ["Money decides everything now.","Artık her şeye para karar veriyor."] ] ] },
  { f=>[ ["We should play football together one day.","Bir gün beraber futbol oynamalıyız."],
         ["We should get a game together sometime. Nothing serious, just for fun.","Bir ara birlikte maç yapalım. Ciddi bir şey değil, sadece eğlence için."] ],
    o=>[ [ ["I would like that!","Bunu isterim!"], ["Yes, let us do it.","Evet, yapalım."] ],
         [ ["I am not good at football.","Futbolda iyi değilim."], ["I will be in goal!","Ben kaleye geçerim!"] ],
         [ ["Where do you play?","Nerede oynuyorsun?"], ["Which day do you play?","Hangi gün oynuyorsun?"] ] ] },
  { f=>[ ["Right, I have talked about football for an hour. Sorry! {phrase}","Tamam, bir saattir futbol konuşuyorum. Pardon! {phrase}"],
         ["I have just talked about football for an hour straight. You are a patient person. {phrase}","Tam bir saat durmadan futbol konuştum. Sen sabırlı bir insansın. {phrase}"] ],
    o=>[ [ ["It is okay, I enjoyed it.","Sorun değil, keyif aldım."], ["I learned a lot!","Çok şey öğrendim!"] ],
         [ ["Now teach me some football words.","Şimdi bana futbol kelimeleri öğret."], ["What is offside exactly?","Ofsayt tam olarak ne?"] ],
         [ ["Next time we talk about something else!","Bir dahaki sefere başka şey konuşuyoruz!"], ["My turn to choose the topic.","Sıra bende, konuyu ben seçiyorum."] ] ] }
 ]
},
{
 id=>"tvnews", title=>"TV haberleri", emoji=>"📺", cat=>"Haberler",
 intro=>"{name} ile televizyonda haberleri izliyorsunuz.",
 beats=>[
  { f=>[ ["Turn on the news. It starts now.","Haberleri aç. Şimdi başlıyor."],
         ["Put the news on, would you? It should be starting about now.","Haberleri açar mısın? Şu an başlıyor olmalı."] ],
    o=>[ [ ["Okay, which channel?","Tamam, hangi kanal?"], ["Where is the remote?","Kumanda nerede?"] ],
         [ ["Do you watch the news every day?","Her gün haber izler misin?"], ["You really like the news!","Haberleri gerçekten seviyorsun!"] ],
         [ ["I do not like the news.","Haberleri sevmiyorum."], ["The news is always bad.","Haberler hep kötü."] ] ] },
  { f=>[ ["I watch the news every morning. I like to know things.","Her sabah haberleri izlerim. Bilmeyi severim."],
         ["I have watched the news every morning for years. It is a habit now.","Yıllardır her sabah haberleri izliyorum. Artık alışkanlık."] ],
    o=>[ [ ["That is a good habit.","İyi bir alışkanlık."], ["I should do that too.","Ben de öyle yapmalıyım."] ],
         [ ["I read the news on my phone.","Haberleri telefonumdan okuyorum."], ["I only read headlines.","Sadece başlıkları okuyorum."] ],
         [ ["The news makes me sad.","Haberler beni üzüyor."], ["I stopped watching last year.","Geçen yıl izlemeyi bıraktım."] ] ] },
  { f=>[ ["Look, the weather report. Rain again tomorrow.","Bak, hava durumu. Yarın yine yağmur."],
         ["Here comes the weather. More rain tomorrow, apparently. What a surprise.","Hava durumu geliyor. Görünüşe göre yarın yine yağmur. Ne sürpriz ama."] ],
    o=>[ [ ["Oh no, more rain.","Olamaz, yine yağmur."], ["I hate rainy days.","Yağmurlu günlerden nefret ederim."] ],
         [ ["I like {weather}, actually.","Aslında {weather} severim."], ["Rain is fine for me.","Yağmur bana uyar."] ],
         [ ["What is the temperature?","Sıcaklık kaç derece?"], ["Will it be cold?","Soğuk olacak mı?"] ] ] },
  { f=>[ ["Prices are going up again. Everything is expensive.","Fiyatlar yine artıyor. Her şey pahalı."],
         ["They are talking about prices again. Everything costs more than last year.","Yine fiyatlardan bahsediyorlar. Her şey geçen yıldan pahalı."] ],
    o=>[ [ ["It is the same in my country.","Benim ülkemde de aynı."], ["Prices go up everywhere.","Fiyatlar her yerde artıyor."] ],
         [ ["Food is the worst.","En kötüsü gıda."], ["Rent is the big problem.","Asıl sorun kira."] ],
         [ ["How do you save money?","Nasıl para biriktiriyorsun?"], ["Do you have any tips?","Bir tavsiyen var mı?"] ] ] },
  { f=>[ ["I try to cook at home. It saves a lot.","Evde pişirmeye çalışıyorum. Çok tasarruf ettiriyor."],
         ["I cook at home much more now. It genuinely saves a surprising amount.","Artık evde çok daha fazla yemek yapıyorum. Cidden şaşırtıcı derecede tasarruf ettiriyor."] ],
    o=>[ [ ["That is a good idea.","İyi fikir."], ["I will try that.","Bunu deneyeceğim."] ],
         [ ["I do the same.","Ben de öyle yapıyorum."], ["I cook every evening.","Her akşam yemek yapıyorum."] ],
         [ ["I have no time to cook.","Yemek yapacak vaktim yok."], ["Cooking for one is hard.","Tek kişiye yemek yapmak zor."] ] ] },
  { f=>[ ["Now there is a story about football. Turn it up!","Şimdi futbolla ilgili bir haber var. Sesi aç!"],
         ["Ah, the sports section. Turn it up, this is the only part I really want.","Ah, spor bölümü. Sesi aç, tek istediğim kısım bu."] ],
    o=>[ [ ["Of course, football again!","Tabii ya, yine futbol!"], ["You never change.","Hiç değişmiyorsun."] ],
         [ ["What are they saying?","Ne diyorlar?"], ["Is it about {team}?","{team} ile mi ilgili?"] ],
         [ ["I want to hear this too.","Ben de bunu duymak istiyorum."], ["Turn it up, please.","Sesi aç lütfen."] ] ] },
  { f=>[ ["There is a big story about the environment today.","Bugün çevreyle ilgili büyük bir haber var."],
         ["They are covering the environment again. Summers here are hotter every year.","Yine çevreyi konuşuyorlar. Buradaki yazlar her yıl daha sıcak."] ],
    o=>[ [ ["It is warmer every year.","Her yıl daha sıcak."], ["Summers are too hot now.","Yazlar artık çok sıcak."] ],
         [ ["What can we do?","Ne yapabiliriz?"], ["Do you recycle at home?","Evde geri dönüşüm yapıyor musun?"] ],
         [ ["I do not know much about it.","Bu konuda pek bilgim yok."], ["Explain it to me.","Bana anlat."] ] ] },
  { f=>[ ["Do you read newspapers, or only the internet?","Gazete okur musun, yoksa sadece internet mi?"],
         ["Do you still read a physical newspaper, or is it all online for you?","Hâlâ kağıt gazete okuyor musun, yoksa her şey internetten mi?"] ],
    o=>[ [ ["Only the internet.","Sadece internet."], ["Everything on my phone.","Her şey telefonumda."] ],
         [ ["I like real newspapers.","Gerçek gazeteleri severim."], ["I buy one at the weekend.","Hafta sonu bir tane alırım."] ],
         [ ["I get news from social media.","Haberleri sosyal medyadan alıyorum."], ["Videos, mostly.","Çoğunlukla video."] ] ] },
  { f=>[ ["Be careful with social media news. It is not always true.","Sosyal medya haberlerine dikkat et. Her zaman doğru değil."],
         ["Be careful with news from social media. Half of it is not true at all.","Sosyal medya haberlerine dikkat et. Yarısı hiç doğru değil."] ],
    o=>[ [ ["You are right.","Haklısın."], ["That is true, sadly.","Ne yazık ki doğru."] ],
         [ ["How do you check a story?","Bir haberi nasıl kontrol ediyorsun?"], ["Which sources do you trust?","Hangi kaynaklara güveniyorsun?"] ],
         [ ["I never believe everything.","Ben her şeye inanmam."], ["I always check two places.","Hep iki yerden kontrol ederim."] ] ] },
  { f=>[ ["Enough news for one night. Let us watch something happy! {phrase}","Bir gece için yeterince haber. Neşeli bir şey izleyelim! {phrase}"],
         ["That is enough bad news for one evening. Shall we find something lighter? {phrase}","Bir akşam için yeterince kötü haber. Daha hafif bir şey bulalım mı? {phrase}"] ],
    o=>[ [ ["Yes please! Something funny.","Evet lütfen! Komik bir şey."], ["A comedy would be perfect.","Bir komedi harika olur."] ],
         [ ["Let us watch {series}.","{series} izleyelim."], ["Put on your favourite show.","En sevdiğin diziyi aç."] ],
         [ ["I should go home actually.","Aslında eve gitmeliyim."], ["It is late for me.","Benim için geç oldu."] ] ] }
 ]
}
]
