use utf8;
[
{
 id=>"technews", title=>"Teknoloji ve dünya haberleri", emoji=>"🌍", cat=>"Haberler",
 intro=>"{name} bugün okuduğu haberlerden bahsediyor.",
 beats=>[
  { f=>[ ["Did you read the news about the new phone?","Yeni telefonla ilgili haberi okudun mu?"],
         ["Have you seen the news about that new phone everyone is talking about?","Herkesin konuştuğu yeni telefonla ilgili haberi gördün mü?"] ],
    o=>[ [ ["No, tell me about it.","Hayır, anlat bakalım."], ["I have not seen it.","Görmedim."] ],
         [ ["Yes, it is very expensive!","Evet, çok pahalı!"], ["I saw the price. Crazy!","Fiyatını gördüm. Delilik!"] ],
         [ ["I do not change my phone often.","Telefonumu sık değiştirmem."], ["My phone is five years old.","Telefonum beş yaşında."] ] ] },
  { f=>[ ["Everyone talks about artificial intelligence now.","Şimdi herkes yapay zekadan bahsediyor."],
         ["Artificial intelligence is in every headline these days. It is hard to avoid.","Bugünlerde yapay zeka her manşette. Kaçmak zor."] ],
    o=>[ [ ["I use it for studying.","Ders çalışmak için kullanıyorum."], ["I practise English with it.","Onunla İngilizce pratiği yapıyorum."] ],
         [ ["Is it dangerous?","Tehlikeli mi?"], ["Will it take our jobs?","İşlerimizi alacak mı?"] ],
         [ ["I do not understand it well.","Onu pek anlamıyorum."], ["It is new for me.","Benim için yeni."] ] ] },
  { f=>[ ["I think it helps at work, but we must be careful.","Bence işte yardımcı oluyor ama dikkatli olmalıyız."],
         ["It certainly helps at work, though I think we should be careful with it.","İşte kesinlikle yardımcı oluyor ama bence dikkatli olmalıyız."] ],
    o=>[ [ ["That makes sense.","Mantıklı."], ["I think the same.","Ben de öyle düşünüyorum."] ],
         [ ["Do you use it at {work}?","{work} yerinde kullanıyor musun?"], ["Does it help your job?","İşine yardımcı oluyor mu?"] ],
         [ ["I prefer doing things myself.","Ben kendim yapmayı tercih ederim."], ["Old ways are better sometimes.","Bazen eski usul daha iyi."] ] ] },
  { f=>[ ["There was a big story from another country today.","Bugün başka bir ülkeden büyük bir haber vardı."],
         ["There was a serious story from abroad in the headlines today.","Bugün manşetlerde yurt dışından ciddi bir haber vardı."] ],
    o=>[ [ ["What happened?","Ne oldu?"], ["Tell me, I missed it.","Anlat, kaçırmışım."] ],
         [ ["I saw something about that.","Onunla ilgili bir şey gördüm."], ["It was everywhere online.","İnternette her yerdeydi."] ],
         [ ["I try not to read sad news.","Üzücü haberleri okumamaya çalışıyorum."], ["That kind of news worries me.","O tür haberler beni endişelendiriyor."] ] ] },
  { f=>[ ["Do you follow news from other countries?","Başka ülkelerin haberlerini takip eder misin?"],
         ["Do you follow international news, or mainly what happens at home?","Uluslararası haberleri takip eder misin, yoksa daha çok ülkendekileri mi?"] ],
    o=>[ [ ["Only big stories.","Sadece büyük haberleri."], ["Sometimes, not always.","Bazen, her zaman değil."] ],
         [ ["Yes, I read international news.","Evet, uluslararası haber okurum."], ["I follow BBC in English.","BBC'yi İngilizce takip ediyorum."] ],
         [ ["No, only local news.","Hayır, sadece yerel haberler."], ["I care about my city more.","Kendi şehrimi daha çok önemsiyorum."] ] ] },
  { f=>[ ["Reading news in English is good practice, you know.","Haberleri İngilizce okumak iyi bir pratik, biliyor musun?"],
         ["Reading the news in English is one of the best ways to learn, honestly.","Haberleri İngilizce okumak öğrenmenin en iyi yollarından biri, cidden."] ],
    o=>[ [ ["That is a good idea.","İyi fikir."], ["I will start doing that.","Bunu yapmaya başlayacağım."] ],
         [ ["The words are difficult.","Kelimeler zor."], ["News English is hard for me.","Haber İngilizcesi bana zor geliyor."] ],
         [ ["Which website do you recommend?","Hangi siteyi tavsiye edersin?"], ["Where should I start?","Nereden başlamalıyım?"] ] ] },
  { f=>[ ["Start with short articles. Five minutes a day is enough.","Kısa yazılarla başla. Günde beş dakika yeter."],
         ["Start small: one short article a day. Five minutes beats one long hour a month.","Küçük başla: günde bir kısa yazı. Beş dakika, ayda bir saatten iyidir."] ],
    o=>[ [ ["Okay, I will try.","Tamam, deneyeceğim."], ["Five minutes I can do.","Beş dakikayı yapabilirim."] ],
         [ ["Should I use a dictionary?","Sözlük kullanmalı mıyım?"], ["Do I need to know every word?","Her kelimeyi bilmem gerekiyor mu?"] ],
         [ ["I forget the new words.","Yeni kelimeleri unutuyorum."], ["How do you remember words?","Kelimeleri nasıl hatırlıyorsun?"] ] ] },
  { f=>[ ["Write them down. That is what {family} did.","Onları yaz. {family} böyle yaptı."],
         ["Write new words down by hand. That is exactly what {family} did and it worked.","Yeni kelimeleri elle yaz. {family} tam olarak bunu yaptı ve işe yaradı."] ],
    o=>[ [ ["I will buy a notebook.","Bir defter alacağım."], ["Good idea, I will write them.","İyi fikir, yazacağım."] ],
         [ ["I use an app for words.","Kelimeler için uygulama kullanıyorum."], ["My phone has a list.","Telefonumda bir liste var."] ],
         [ ["Ten new words a day?","Günde on yeni kelime?"], ["How many words a day?","Günde kaç kelime?"] ] ] },
  { f=>[ ["Do not rush. Slow and every day is better.","Acele etme. Yavaş ve her gün olması daha iyi."],
         ["Do not rush it. Consistency beats speed every single time.","Acele etme. Süreklilik her zaman hızdan üstündür."] ],
    o=>[ [ ["Thank you for the advice.","Tavsiye için teşekkürler."], ["That helps a lot.","Bu çok yardımcı oldu."] ],
         [ ["Sometimes I want to give up.","Bazen vazgeçmek istiyorum."], ["It is slow progress.","İlerleme yavaş."] ],
         [ ["How long did you learn?","Sen ne kadar sürede öğrendin?"], ["Was it hard for you too?","Senin için de zor muydu?"] ] ] },
  { f=>[ ["You are doing well. Keep going! {phrase}","İyi gidiyorsun. Devam et! {phrase}"],
         ["You are genuinely improving. Do not stop now, that is the important part. {phrase}","Gerçekten gelişiyorsun. Şimdi bırakma, önemli olan bu. {phrase}"] ],
    o=>[ [ ["Thank you, {name}!","Teşekkürler {name}!"], ["That means a lot.","Bu benim için çok değerli."] ],
         [ ["I will practise tomorrow too.","Yarın da pratik yapacağım."], ["Same time tomorrow?","Yarın aynı saatte?"] ],
         [ ["Talking to you helps.","Seninle konuşmak yardımcı oluyor."], ["You are a good teacher.","İyi bir öğretmensin."] ] ] }
 ]
},
{
 id=>"workday", title=>"İş günü", emoji=>"💼", cat=>"İş ve Okul",
 intro=>"{name} ile iş çıkışı konuşuyorsunuz.",
 beats=>[
  { f=>[ ["What a day! I am so tired.","Ne gündü ama! Çok yorgunum."],
         ["Honestly, what a day. I have been on my feet since seven this morning.","Cidden, ne gündü. Sabah yediden beri ayaktayım."] ],
    o=>[ [ ["Was it a busy day?","Yoğun bir gün müydü?"], ["What happened?","Ne oldu?"] ],
         [ ["Sit down and relax.","Otur ve dinlen."], ["You need a break.","Bir molaya ihtiyacın var."] ],
         [ ["My day was long too.","Benim günüm de uzundu."], ["I am tired as well.","Ben de yorgunum."] ] ] },
  { f=>[ ["I work as {job}. Some days are hard.","{job} olarak çalışıyorum. Bazı günler zor."],
         ["Working as {job} is rewarding, but some days really take everything out of you.","{job} olarak çalışmak tatmin edici ama bazı günler insanı tüketiyor."] ],
    o=>[ [ ["How many hours do you work?","Kaç saat çalışıyorsun?"], ["Is it a long day?","Gün uzun mu?"] ],
         [ ["Do you like your colleagues?","İş arkadaşlarını seviyor musun?"], ["Are the people nice there?","Oradaki insanlar iyi mi?"] ],
         [ ["What is the hardest part?","En zor kısmı ne?"], ["What do you like most?","En çok neyi seviyorsun?"] ] ] },
  { f=>[ ["The people at {work} are good. That helps.","{work} yerindeki insanlar iyi. Bu yardımcı oluyor."],
         ["The team at {work} makes a huge difference. Good colleagues change everything.","{work} yerindeki ekip çok fark yaratıyor. İyi iş arkadaşları her şeyi değiştirir."] ],
    o=>[ [ ["That is important.","Bu önemli."], ["Good people make a difference.","İyi insanlar fark yaratır."] ],
         [ ["My colleagues are okay.","Benim iş arkadaşlarım idare eder."], ["I work alone mostly.","Çoğunlukla yalnız çalışıyorum."] ],
         [ ["Do you see them outside work?","Onları iş dışında görüyor musun?"], ["Are they your friends too?","Aynı zamanda arkadaşın mılar?"] ] ] },
  { f=>[ ["What do you do for work?","Sen ne iş yapıyorsun?"],
         ["Tell me about your job. What do you actually do all day?","Bana işinden bahset. Gün boyu tam olarak ne yapıyorsun?"] ],
    o=>[ [ ["I work in an office.","Bir ofiste çalışıyorum."], ["I am a student.","Öğrenciyim."] ],
         [ ["I work with computers.","Bilgisayarlarla çalışıyorum."], ["I work in a shop.","Bir mağazada çalışıyorum."] ],
         [ ["I am looking for a job.","İş arıyorum."], ["I am between jobs right now.","Şu an işsizim."] ] ] },
  { f=>[ ["Do you like it? That is the important question.","Seviyor musun? Asıl önemli soru bu."],
         ["But do you actually enjoy it? That is the question nobody asks.","Ama gerçekten seviyor musun? Kimsenin sormadığı soru bu."] ],
    o=>[ [ ["Yes, most days.","Evet, çoğu gün."], ["I like it, yes.","Evet, seviyorum."] ],
         [ ["Not really, it is just money.","Pek değil, sadece para için."], ["It pays the bills.","Faturaları ödüyor."] ],
         [ ["I want to change job.","İş değiştirmek istiyorum."], ["I am thinking about it.","Düşünüyorum."] ] ] },
  { f=>[ ["Change is scary but good. I changed twice.","Değişim korkutucu ama iyi. Ben iki kez değiştirdim."],
         ["Changing career is frightening, but I have done it twice and never regretted it.","Kariyer değiştirmek ürkütücü ama iki kez yaptım ve hiç pişman olmadım."] ],
    o=>[ [ ["Really? What did you do before?","Gerçekten mi? Önce ne yapıyordun?"], ["Tell me the story.","Hikayeyi anlat."] ],
         [ ["Was it difficult?","Zor muydu?"], ["Were you afraid?","Korktun mu?"] ],
         [ ["Maybe I need courage.","Belki cesarete ihtiyacım var."], ["I am afraid of change.","Değişimden korkuyorum."] ] ] },
  { f=>[ ["Money is not everything. Time matters too.","Para her şey değil. Zaman da önemli."],
         ["A bigger salary is nice, but time and health matter far more in the end.","Yüksek maaş güzel ama sonunda zaman ve sağlık çok daha önemli."] ],
    o=>[ [ ["You are right.","Haklısın."], ["I need to remember that.","Bunu hatırlamam lazım."] ],
         [ ["But I need money too!","Ama benim de paraya ihtiyacım var!"], ["Bills do not pay themselves.","Faturalar kendi kendine ödenmiyor."] ],
         [ ["Do you work at weekends?","Hafta sonu çalışıyor musun?"], ["Do you have free time?","Boş vaktin var mı?"] ] ] },
  { f=>[ ["I do {hobby} to relax. It really helps.","Rahatlamak için {hobby} yapıyorum. Çok yardımcı oluyor."],
         ["My way of switching off is {hobby}. Without it I would go mad.","Kafayı dağıtma yöntemim {hobby}. O olmasa delirirdim."] ],
    o=>[ [ ["That sounds relaxing.","Kulağa rahatlatıcı geliyor."], ["I should try that.","Bunu denemeliyim."] ],
         [ ["I relax by watching TV.","Ben televizyon izleyerek rahatlıyorum."], ["I go for walks.","Yürüyüşe çıkıyorum."] ],
         [ ["I do not have a hobby.","Benim hobim yok."], ["I never have free time.","Hiç boş vaktim olmuyor."] ] ] },
  { f=>[ ["Everyone needs one thing just for themselves.","Herkesin sadece kendisi için bir şeye ihtiyacı var."],
         ["Everybody needs one thing that belongs only to them, not to work or family.","Herkesin sadece kendine ait, ne işe ne aileye ait olmayan bir şeye ihtiyacı var."] ],
    o=>[ [ ["That is true.","Bu doğru."], ["I will find something.","Bir şey bulacağım."] ],
         [ ["Maybe learning English is mine!","Belki benimki İngilizce öğrenmek!"], ["This is my hobby now.","Bu artık benim hobim."] ],
         [ ["What do you recommend?","Ne tavsiye edersin?"], ["Any ideas for me?","Bana bir fikrin var mı?"] ] ] },
  { f=>[ ["Right, I am going home to sleep. {phrase}","Tamam, eve uyumaya gidiyorum. {phrase}"],
         ["Anyway, I am going home to collapse on the sofa. {phrase}","Neyse, eve gidip kanepeye yığılacağım. {phrase}"] ],
    o=>[ [ ["Sleep well!","İyi uykular!"], ["Rest well, you need it.","İyi dinlen, ihtiyacın var."] ],
         [ ["See you tomorrow.","Yarın görüşürüz."], ["Same time tomorrow?","Yarın aynı saatte?"] ],
         [ ["Thanks for the chat.","Sohbet için teşekkürler."], ["That was nice, {name}.","Güzeldi {name}."] ] ] }
 ]
},
{
 id=>"weekend", title=>"Hafta sonu planı", emoji=>"🎉", cat=>"Günlük Hayat",
 intro=>"Cuma akşamı, {name} hafta sonu planı yapıyor.",
 beats=>[
  { f=>[ ["It is Friday! What are you doing this weekend?","Cuma oldu! Bu hafta sonu ne yapıyorsun?"],
         ["Finally Friday. Have you got any plans for the weekend, or is it open?","Nihayet cuma. Hafta sonu için planın var mı, yoksa boş mu?"] ],
    o=>[ [ ["Nothing special.","Özel bir şey yok."], ["I have no plans yet.","Henüz planım yok."] ],
         [ ["I am seeing my family.","Ailemi göreceğim."], ["I am visiting my parents.","Anne babamı ziyaret edeceğim."] ],
         [ ["I am working, sadly.","Ne yazık ki çalışıyorum."], ["I work on Saturday.","Cumartesi çalışıyorum."] ] ] },
  { f=>[ ["Come with me then! I am going out on Saturday.","O zaman benimle gel! Cumartesi dışarı çıkıyorum."],
         ["In that case, come with us on Saturday. There will be a few of us.","O zaman cumartesi bizimle gel. Birkaç kişi olacağız."] ],
    o=>[ [ ["Where are you going?","Nereye gidiyorsunuz?"], ["What is the plan?","Plan ne?"] ],
         [ ["Yes, I would love to!","Evet, çok isterim!"], ["Count me in!","Ben varım!"] ],
         [ ["Who else is coming?","Başka kim geliyor?"], ["Will I know anyone?","Tanıdığım biri olacak mı?"] ] ] },
  { f=>[ ["We are going to a place with live {music}.","Canlı {music} olan bir yere gidiyoruz."],
         ["There is a small place near me with live {music} on Saturdays. It is brilliant.","Yakınımda cumartesileri canlı {music} olan küçük bir yer var. Harika."] ],
    o=>[ [ ["I love that music!","O müziğe bayılırım!"], ["That sounds fun.","Kulağa eğlenceli geliyor."] ],
         [ ["I do not know that music.","O müziği bilmiyorum."], ["Is it loud?","Gürültülü mü?"] ],
         [ ["What time does it start?","Saat kaçta başlıyor?"], ["How late does it finish?","Ne kadar geç bitiyor?"] ] ] },
  { f=>[ ["Nine o'clock. Do not be late, please!","Saat dokuz. Lütfen geç kalma!"],
         ["It kicks off at nine. And please, for once, do not be fashionably late.","Dokuzda başlıyor. Ve lütfen bir kez olsun geç kalma."] ],
    o=>[ [ ["I will be there at nine.","Dokuzda orada olacağım."], ["I am never late!","Ben hiç geç kalmam!"] ],
         [ ["I might be a little late.","Biraz geç kalabilirim."], ["I finish work at eight.","İşim sekizde bitiyor."] ],
         [ ["Where do we meet?","Nerede buluşuyoruz?"], ["Send me the address.","Adresi bana gönder."] ] ] },
  { f=>[ ["On Sunday I usually do {hobby}.","Pazar günleri genelde {hobby} yaparım."],
         ["Sundays are sacred for me. That is when I do {hobby} and nothing else.","Pazarlar benim için kutsal. O gün {hobby} yaparım, başka bir şey yok."] ],
    o=>[ [ ["Every Sunday?","Her pazar mı?"], ["Do you never miss it?","Hiç kaçırmaz mısın?"] ],
         [ ["Can I come with you?","Seninle gelebilir miyim?"], ["Can I try it?","Deneyebilir miyim?"] ],
         [ ["I sleep all Sunday!","Ben bütün pazar uyurum!"], ["Sunday is my lazy day.","Pazar benim tembellik günüm."] ] ] },
  { f=>[ ["Of course you can come! It is more fun with two.","Tabii ki gelebilirsin! İki kişi daha eğlenceli."],
         ["Of course, come along. Everything is better with company anyway.","Tabii ki gel. Zaten her şey birlikte daha güzel."] ],
    o=>[ [ ["Great! What do I need?","Harika! Neye ihtiyacım var?"], ["What should I bring?","Ne getirmeliyim?"] ],
         [ ["I am not very good at it.","Bunda pek iyi değilim."], ["I have never done it.","Hiç yapmadım."] ],
         [ ["What time on Sunday?","Pazar saat kaçta?"], ["Morning or afternoon?","Sabah mı öğleden sonra mı?"] ] ] },
  { f=>[ ["Just bring yourself. I have everything.","Sadece kendini getir. Bende her şey var."],
         ["Bring nothing but yourself and a good mood. I have everything else.","Kendinden ve iyi bir keyiften başka bir şey getirme. Gerisi bende."] ],
    o=>[ [ ["Perfect. Thank you!","Mükemmel. Teşekkürler!"], ["That is easy then.","O zaman kolay."] ],
         [ ["I will bring some food.","Ben biraz yemek getiririm."], ["I will bring drinks.","İçecek getiririm."] ],
         [ ["I am excited!","Heyecanlandım!"], ["I am looking forward to it.","Sabırsızlanıyorum."] ] ] },
  { f=>[ ["What do you usually do at weekends?","Sen hafta sonları genelde ne yaparsın?"],
         ["Tell me about your weekends. What does a normal Saturday look like for you?","Hafta sonlarını anlat. Senin için normal bir cumartesi nasıl geçer?"] ],
    o=>[ [ ["I stay at home and rest.","Evde kalıp dinlenirim."], ["I clean the house.","Ev temizliği yaparım."] ],
         [ ["I meet friends.","Arkadaşlarla buluşurum."], ["I go out with my family.","Ailemle dışarı çıkarım."] ],
         [ ["I study English.","İngilizce çalışırım."], ["I watch films all day.","Bütün gün film izlerim."] ] ] },
  { f=>[ ["You need to get out more! Life is short.","Daha çok dışarı çıkmalısın! Hayat kısa."],
         ["You should get out more, honestly. The weeks disappear if you are not careful.","Cidden daha çok dışarı çıkmalısın. Dikkat etmezsen haftalar uçup gidiyor."] ],
    o=>[ [ ["You are probably right.","Muhtemelen haklısın."], ["I know, I know.","Biliyorum, biliyorum."] ],
         [ ["I am a bit shy.","Biraz utangacım."], ["I do not know many people here.","Burada çok kişi tanımıyorum."] ],
         [ ["That is why I have you!","İşte bu yüzden sen varsın!"], ["You are my social life.","Sosyal hayatım sensin."] ] ] },
  { f=>[ ["See you Saturday at nine! {phrase}","Cumartesi dokuzda görüşürüz! {phrase}"],
         ["Saturday, nine o'clock, no excuses. It is going to be a good one. {phrase}","Cumartesi, saat dokuz, bahane yok. Güzel geçecek. {phrase}"] ],
    o=>[ [ ["See you then!","O zaman görüşürüz!"], ["I will be there!","Orada olacağım!"] ],
         [ ["Message me before.","Öncesinde mesaj at."], ["Remind me on Saturday.","Cumartesi hatırlat."] ],
         [ ["Have a good Friday night!","İyi cumalar!"], ["Enjoy your evening.","İyi akşamlar."] ] ] }
 ]
},
{
 id=>"shopping", title=>"Alışverişte", emoji=>"🛒", cat=>"Günlük Hayat",
 intro=>"{name} ile alışveriş yapıyorsunuz.",
 beats=>[
  { f=>[ ["I need a few things. Come with me?","Birkaç şey lazım. Benimle gelir misin?"],
         ["I only need a few bits, but shopping alone is miserable. Come with me?","Sadece birkaç şey lazım ama tek başına alışveriş berbat. Benimle gelir misin?"] ],
    o=>[ [ ["Sure, I have time.","Tabii, vaktim var."], ["Yes, let us go.","Evet, gidelim."] ],
         [ ["What do you need to buy?","Ne alman lazım?"], ["Do you have a list?","Listen var mı?"] ],
         [ ["I need things too.","Benim de bir şeylere ihtiyacım var."], ["Good, I need bread and milk.","İyi, benim de ekmek ve süt lazım."] ] ] },
  { f=>[ ["I always forget my list at home!","Listemi hep evde unutuyorum!"],
         ["I have written a list and, naturally, left it on the kitchen table.","Liste yazdım ve tabii ki mutfak masasında unuttum."] ],
    o=>[ [ ["Try to remember!","Hatırlamaya çalış!"], ["What was on it?","Listede ne vardı?"] ],
         [ ["I keep mine on my phone.","Ben listemi telefonumda tutuyorum."], ["Use your phone next time.","Bir dahaki sefere telefonunu kullan."] ],
         [ ["We will remember together.","Beraber hatırlarız."], ["Do not worry about it.","Boş ver."] ] ] },
  { f=>[ ["Look at these prices! Everything is more expensive.","Şu fiyatlara bak! Her şey daha pahalı."],
         ["Look at this. The same shopping cost me far less last year.","Şuna bak. Aynı alışveriş geçen yıl çok daha ucuzdu."] ],
    o=>[ [ ["Yes, it is very expensive.","Evet, çok pahalı."], ["I noticed that too.","Ben de fark ettim."] ],
         [ ["Which shop is cheaper?","Hangi mağaza daha ucuz?"], ["Do you know a cheap place?","Ucuz bir yer biliyor musun?"] ],
         [ ["I buy only what I need.","Sadece ihtiyacım olanı alıyorum."], ["I never buy extra now.","Artık fazladan bir şey almıyorum."] ] ] },
  { f=>[ ["I always buy the things for {breakfast} first.","Önce hep {breakfast} için gerekenleri alırım."],
         ["My basket is always the same: everything for {breakfast}, then the rest.","Sepetim hep aynı: önce {breakfast} için her şey, sonra gerisi."] ],
    o=>[ [ ["You really love that breakfast!","O kahvaltıyı gerçekten seviyorsun!"], ["Every day the same?","Her gün aynı mı?"] ],
         [ ["I buy eggs and cheese.","Ben yumurta ve peynir alıyorum."], ["Bread and tea for me.","Bana ekmek ve çay."] ],
         [ ["Where is the bread here?","Ekmek burada nerede?"], ["Which aisle is the milk?","Süt hangi reyonda?"] ] ] },
  { f=>[ ["I need new shoes as well. What do you think of these?","Yeni ayakkabı da lazım. Bunlar hakkında ne düşünüyorsun?"],
         ["While we are here, I need shoes. Be honest, what do you think of these?","Hazır gelmişken ayakkabı lazım. Dürüst ol, bunlar nasıl?"] ],
    o=>[ [ ["They look good!","Güzel görünüyorlar!"], ["I like them.","Beğendim."] ],
         [ ["Not really my style.","Pek benim tarzım değil."], ["Try the black ones.","Siyah olanları dene."] ],
         [ ["How much are they?","Kaç para?"], ["Are they comfortable?","Rahat mı?"] ] ] },
  { f=>[ ["Too expensive. I will wait for the sale.","Çok pahalı. İndirimi bekleyeceğim."],
         ["That is far too much. I will wait for the sales in January.","Bu çok fazla. Ocaktaki indirimleri bekleyeceğim."] ],
    o=>[ [ ["Good idea. Be patient.","İyi fikir. Sabırlı ol."], ["Sales are always better.","İndirimler hep daha iyi."] ],
         [ ["But you like them a lot!","Ama onları çok beğendin!"], ["Buy them, you deserve it.","Al onları, hak ediyorsun."] ],
         [ ["I never buy full price.","Ben hiç tam fiyata almam."], ["I always look online first.","Önce hep internete bakarım."] ] ] },
  { f=>[ ["Do you shop online or in real shops?","İnternetten mi alışveriş yaparsın yoksa gerçek mağazadan mı?"],
         ["Are you an online shopper, or do you prefer actually going into shops?","İnternetten mi alışveriş yaparsın, yoksa mağazaya gitmeyi mi seversin?"] ],
    o=>[ [ ["Online, it is easier.","İnternetten, daha kolay."], ["I buy everything online.","Her şeyi internetten alıyorum."] ],
         [ ["Real shops. I like to see things.","Gerçek mağaza. Görmeyi severim."], ["I need to try clothes on.","Kıyafetleri denemem gerekiyor."] ],
         [ ["Both, it depends.","İkisi de, duruma göre."], ["Food in shops, clothes online.","Yemeği mağazadan, kıyafeti internetten."] ] ] },
  { f=>[ ["The queue is so long. We will be here forever.","Kuyruk çok uzun. Sonsuza kadar burada olacağız."],
         ["Look at that queue. We are going to be standing here for twenty minutes.","Şu kuyruğa bak. Yirmi dakika burada dikileceğiz."] ],
    o=>[ [ ["Let us use the self checkout.","Self servis kasayı kullanalım."], ["Try the other till.","Diğer kasayı dene."] ],
         [ ["It is okay, we can talk.","Sorun değil, konuşuruz."], ["I do not mind waiting.","Beklemek sorun değil."] ],
         [ ["I hate queues!","Kuyruklardan nefret ederim!"], ["This is my worst nightmare.","Bu benim en büyük kabusum."] ] ] },
  { f=>[ ["Can you carry one bag? Thank you!","Bir poşet taşıyabilir misin? Teşekkürler!"],
         ["Would you take one of these bags? I have somehow bought far too much.","Şu poşetlerden birini alır mısın? Bir şekilde çok fazla şey almışım."] ],
    o=>[ [ ["Of course, give me two.","Tabii, iki tane ver."], ["No problem at all.","Hiç sorun değil."] ],
         [ ["They are heavy!","Ağırlar!"], ["What did you buy, rocks?","Ne aldın, taş mı?"] ],
         [ ["Where is your car?","Araban nerede?"], ["How do we get home?","Eve nasıl gideceğiz?"] ] ] },
  { f=>[ ["Thanks for coming. Shopping alone is boring. {phrase}","Geldiğin için sağ ol. Tek başına alışveriş sıkıcı. {phrase}"],
         ["Thank you for coming, genuinely. Shopping alone is the worst job in the world. {phrase}","Geldiğin için cidden sağ ol. Tek başına alışveriş dünyanın en kötü işi. {phrase}"] ],
    o=>[ [ ["Any time!","Ne zaman istersen!"], ["It was fun.","Eğlenceliydi."] ],
         [ ["Now I need coffee.","Şimdi bana kahve lazım."], ["Shall we sit down somewhere?","Bir yerde oturalım mı?"] ],
         [ ["Call me next time too.","Bir dahaki sefere de beni ara."], ["See you soon!","Yakında görüşürüz!"] ] ] }
 ]
},
{
 id=>"health", title=>"Sağlık ve doktor", emoji=>"🏥", cat=>"Sağlık",
 intro=>"{name} kendini iyi hissetmiyor.",
 beats=>[
  { f=>[ ["I do not feel well today.","Bugün kendimi iyi hissetmiyorum."],
         ["I have not felt right since yesterday. Something is definitely wrong.","Dünden beri kendimi iyi hissetmiyorum. Kesin bir şey var."] ],
    o=>[ [ ["What is wrong?","Neyin var?"], ["Are you okay?","İyi misin?"] ],
         [ ["Do you have a temperature?","Ateşin var mı?"], ["Do you feel hot or cold?","Sıcak mı soğuk mu hissediyorsun?"] ],
         [ ["Sit down. I will get water.","Otur. Ben su getireyim."], ["Do you need anything?","Bir şeye ihtiyacın var mı?"] ] ] },
  { f=>[ ["I have a headache and a sore throat.","Başım ağrıyor ve boğazım yanıyor."],
         ["My head is pounding and my throat feels like sandpaper.","Başım zonkluyor ve boğazım zımpara gibi."] ],
    o=>[ [ ["You should rest.","Dinlenmelisin."], ["Go home and sleep.","Eve git ve uyu."] ],
         [ ["Did you take medicine?","İlaç aldın mı?"], ["Have you got any tablets?","Hapın var mı?"] ],
         [ ["Drink hot tea with lemon.","Limonlu sıcak çay iç."], ["Honey helps a lot.","Bal çok iyi gelir."] ] ] },
  { f=>[ ["I hate going to the doctor.","Doktora gitmekten nefret ediyorum."],
         ["I really do not want to see a doctor. I never have, even as a child.","Doktora gitmeyi hiç istemiyorum. Çocukken bile istemezdim."] ],
    o=>[ [ ["But you must go!","Ama gitmelisin!"], ["Health comes first.","Sağlık her şeyden önce gelir."] ],
         [ ["I understand. Me too.","Anlıyorum. Ben de öyle."], ["Doctors make me nervous.","Doktorlar beni geriyor."] ],
         [ ["I can come with you.","Seninle gelebilirim."], ["Do not go alone.","Yalnız gitme."] ] ] },
  { f=>[ ["Maybe you are right. I will call tomorrow.","Belki haklısın. Yarın ararım."],
         ["Fine, you win. I will phone the surgery first thing tomorrow.","Tamam, sen kazandın. Yarın ilk iş kliniği ararım."] ],
    o=>[ [ ["Good! Do not forget.","Güzel! Unutma."], ["Promise me.","Bana söz ver."] ],
         [ ["What time do they open?","Kaçta açılıyorlar?"], ["Do you need an appointment?","Randevu gerekiyor mu?"] ],
         [ ["Text me after.","Sonra bana yaz."], ["Tell me what they say.","Ne dediklerini söyle."] ] ] },
  { f=>[ ["Are you healthy? Do you do sport?","Sen sağlıklı mısın? Spor yapıyor musun?"],
         ["What about you, are you looking after yourself? Any exercise?","Peki ya sen, kendine iyi bakıyor musun? Spor var mı?"] ],
    o=>[ [ ["I walk every day.","Her gün yürüyorum."], ["I try to walk a lot.","Çok yürümeye çalışıyorum."] ],
         [ ["I go to the gym twice a week.","Haftada iki kez spor salonuna gidiyorum."], ["I run at weekends.","Hafta sonları koşuyorum."] ],
         [ ["No, I sit all day.","Hayır, bütün gün oturuyorum."], ["I should do more.","Daha fazla yapmalıyım."] ] ] },
  { f=>[ ["Sitting all day is bad. Even ten minutes helps.","Bütün gün oturmak kötü. On dakika bile fayda eder."],
         ["Sitting for hours is genuinely bad for you. Even ten minutes of walking helps.","Saatlerce oturmak cidden zararlı. On dakikalık yürüyüş bile iyi gelir."] ],
    o=>[ [ ["I will start walking.","Yürümeye başlayacağım."], ["Ten minutes I can do.","On dakikayı yapabilirim."] ],
         [ ["I am too tired after work.","İşten sonra çok yorgun oluyorum."], ["I have no energy.","Enerjim yok."] ],
         [ ["Do you exercise?","Sen spor yapıyor musun?"], ["What do you do to stay fit?","Formda kalmak için ne yapıyorsun?"] ] ] },
  { f=>[ ["I do {hobby}, and I walk to {work}.","{hobby} yapıyorum ve {work} yerine yürüyorum."],
         ["Between {hobby} and walking to {work}, I move more than I think.","{hobby} ve {work} yerine yürümek arasında sandığımdan çok hareket ediyorum."] ],
    o=>[ [ ["That is a good routine.","İyi bir rutin."], ["Small things add up.","Küçük şeyler birikiyor."] ],
         [ ["How far do you walk?","Ne kadar yürüyorsun?"], ["How long does it take?","Ne kadar sürüyor?"] ],
         [ ["I drive everywhere.","Ben her yere arabayla giderim."], ["I take the bus, always.","Hep otobüse binerim."] ] ] },
  { f=>[ ["Sleep is important too. I need eight hours.","Uyku da önemli. Bana sekiz saat lazım."],
         ["Sleep matters more than people admit. I am useless with less than eight hours.","Uyku insanların kabul ettiğinden önemli. Sekiz saatten az uyursam işe yaramam."] ],
    o=>[ [ ["I sleep six hours.","Ben altı saat uyuyorum."], ["I never sleep enough.","Hiç yeterince uyuyamıyorum."] ],
         [ ["I sleep well, luckily.","Şansıma iyi uyuyorum."], ["I sleep like a stone.","Taş gibi uyurum."] ],
         [ ["My phone keeps me awake.","Telefon beni uyutmuyor."], ["I go to bed too late.","Çok geç yatıyorum."] ] ] },
  { f=>[ ["Put the phone away one hour before bed. It works.","Yatmadan bir saat önce telefonu bırak. İşe yarıyor."],
         ["Try leaving your phone in another room an hour before bed. It genuinely works.","Yatmadan bir saat önce telefonu başka odaya bırakmayı dene. Cidden işe yarıyor."] ],
    o=>[ [ ["I will try tonight.","Bu gece deneyeceğim."], ["That is hard but okay.","Zor ama tamam."] ],
         [ ["I use my phone as an alarm.","Telefonu alarm olarak kullanıyorum."], ["Then I need a real clock.","O zaman gerçek bir saat lazım."] ],
         [ ["Do you do that?","Sen böyle yapıyor musun?"], ["Does it really help?","Gerçekten yardımcı oluyor mu?"] ] ] },
  { f=>[ ["Look after yourself. I need you healthy! {phrase}","Kendine iyi bak. Sağlıklı olmana ihtiyacım var! {phrase}"],
         ["Look after yourself properly. I would like to keep you around a while. {phrase}","Kendine düzgün bak. Seni bir süre daha yanımda tutmak isterim. {phrase}"] ],
    o=>[ [ ["You too! Get well soon.","Sen de! Geçmiş olsun."], ["Take your medicine!","İlacını iç!"] ],
         [ ["Thank you for caring.","İlgin için teşekkürler."], ["That is kind of you.","Çok naziksin."] ],
         [ ["Call me if you need anything.","Bir şeye ihtiyacın olursa ara."], ["I am here for you.","Senin için buradayım."] ] ] }
 ]
}
]
