use utf8;
[
{
 id=>"birthday", title=>"Doğum günü kutlaması", emoji=>"🎂", cat=>"Eğlence",
 intro=>"Bugün {name} için özel bir gün.",
 beats=>[
  { f=>[ ["Guess what? It is my birthday today!","Bil bakalım ne oldu? Bugün doğum günüm!"],
         ["I was not going to mention it, but it happens to be my birthday today.","Söylemeyecektim ama bugün doğum günüm."] ],
    o=>[ [ ["Happy birthday!","Doğum günün kutlu olsun!"], ["Many happy returns!","Nice yıllara!"] ],
         [ ["Why did you not tell me?","Neden bana söylemedin?"], ["I did not know!","Bilmiyordum!"] ],
         [ ["How old are you now?","Kaç yaşına girdin?"], ["Do you feel older?","Daha yaşlı hissediyor musun?"] ] ] },
  { f=>[ ["I am not telling you my age!","Yaşımı sana söylemiyorum!"],
         ["I am not answering that question. Some things stay private!","O soruyu cevaplamıyorum. Bazı şeyler özel kalır!"] ],
    o=>[ [ ["Okay, okay!","Tamam tamam!"], ["Sorry, I will not ask.","Pardon, sormayacağım."] ],
         [ ["You look young anyway.","Zaten genç görünüyorsun."], ["Age is just a number.","Yaş sadece bir sayı."] ],
         [ ["I will guess then!","O zaman tahmin edeceğim!"], ["Twenty five?","Yirmi beş?"] ] ] },
  { f=>[ ["What do you do on your birthday?","Sen doğum gününde ne yaparsın?"],
         ["How do you celebrate your birthday? Big party or a quiet evening?","Doğum gününü nasıl kutlarsın? Büyük parti mi sakin bir akşam mı?"] ],
    o=>[ [ ["Nothing special, usually.","Genelde özel bir şey yok."], ["A quiet dinner at home.","Evde sakin bir akşam yemeği."] ],
         [ ["I celebrate with my family.","Ailemle kutlarım."], ["We eat cake together.","Birlikte pasta yeriz."] ],
         [ ["I go out with friends.","Arkadaşlarla dışarı çıkarım."], ["We have a big party!","Büyük parti yaparız!"] ] ] },
  { f=>[ ["Tonight I am eating {food}. It is a tradition.","Bu akşam {food} yiyeceğim. Bu bir gelenek."],
         ["Every year on my birthday I eat {food}. My family has always done it.","Her doğum günümde {food} yerim. Ailemde hep böyle olmuştur."] ],
    o=>[ [ ["That sounds delicious!","Çok lezzetli görünüyor!"], ["Nice tradition!","Güzel gelenek!"] ],
         [ ["Can I come?","Gelebilir miyim?"], ["Am I invited?","Davetli miyim?"] ],
         [ ["We eat cake in my country.","Bizim ülkemizde pasta yeriz."], ["We have our own traditions.","Bizim de kendi geleneklerimiz var."] ] ] },
  { f=>[ ["Of course you are invited! Come at seven.","Tabii ki davetlisin! Yedide gel."],
         ["You are absolutely invited. Seven o'clock, and do not bring anything expensive.","Kesinlikle davetlisin. Saat yedide, ve pahalı bir şey getirme."] ],
    o=>[ [ ["I will be there!","Orada olacağım!"], ["Thank you for inviting me.","Davet ettiğin için sağ ol."] ],
         [ ["What present do you want?","Ne hediye istersin?"], ["What should I buy you?","Sana ne almalıyım?"] ],
         [ ["I will bring the cake!","Pastayı ben getiririm!"], ["Let me bring something.","Bir şey getireyim."] ] ] },
  { f=>[ ["No presents, please. Just come.","Hediye yok lütfen. Sadece gel."],
         ["Please, no presents. Your company is genuinely enough for me.","Lütfen hediye yok. Senin gelmen benim için gerçekten yeterli."] ],
    o=>[ [ ["Too late, I bought one!","Çok geç, aldım bile!"], ["I already have something.","Zaten bir şeyim var."] ],
         [ ["Okay, just me then.","Tamam, o zaman sadece ben."], ["As you wish!","Nasıl istersen!"] ],
         [ ["A small thing, that is all.","Küçük bir şey, o kadar."], ["Something from Turkey?","Türkiye'den bir şey?"] ] ] },
  { f=>[ ["Something from Turkey? Now I am excited!","Türkiye'den bir şey mi? Şimdi heyecanlandım!"],
         ["Something from Turkey would be wonderful. Now you have made me curious.","Türkiye'den bir şey harika olur. Şimdi merakımı uyandırdın."] ],
    o=>[ [ ["It is a surprise!","Sürpriz!"], ["You will see tonight.","Bu akşam göreceksin."] ],
         [ ["Do you like sweet things?","Tatlı sever misin?"], ["Do you drink Turkish coffee?","Türk kahvesi içer misin?"] ],
         [ ["It is small, do not expect much.","Küçük bir şey, çok bekleme."], ["I hope you like it.","Umarım beğenirsin."] ] ] },
  { f=>[ ["Birthdays make me think about time.","Doğum günleri bana zamanı düşündürüyor."],
         ["Birthdays always make me think. Another year gone, and so fast.","Doğum günleri hep düşündürür. Bir yıl daha gitti, hem de çok hızlı."] ],
    o=>[ [ ["Time goes so fast.","Zaman çok hızlı geçiyor."], ["Every year is quicker!","Her yıl daha hızlı!"] ],
         [ ["Are you happy with this year?","Bu yıldan memnun musun?"], ["Was it a good year?","İyi bir yıl mıydı?"] ],
         [ ["Do not be sad on your birthday!","Doğum gününde üzülme!"], ["Today we celebrate!","Bugün kutlama günü!"] ] ] },
  { f=>[ ["You are right! Tonight we celebrate.","Haklısın! Bu akşam kutluyoruz."],
         ["You are completely right. Enough thinking, tonight we celebrate properly.","Tamamen haklısın. Yeterince düşündüm, bu akşam adam gibi kutluyoruz."] ],
    o=>[ [ ["That is the spirit!","İşte bu!"], ["Now you are talking!","Şimdi oldu!"] ],
         [ ["Who else is coming?","Başka kim geliyor?"], ["How many people?","Kaç kişi?"] ],
         [ ["Should I dress smart?","Şık giyinmeli miyim?"], ["What should I wear?","Ne giymeliyim?"] ] ] },
  { f=>[ ["See you at seven. Thank you, really. {phrase}","Yedide görüşürüz. Gerçekten teşekkürler. {phrase}"],
         ["Seven o'clock then. And thank you, honestly, for making today nice. {phrase}","O zaman yedide. Ve cidden, bugünü güzelleştirdiğin için teşekkürler. {phrase}"] ],
    o=>[ [ ["Happy birthday again!","Doğum günün tekrar kutlu olsun!"], ["Have a wonderful day!","Harika bir gün geçir!"] ],
         [ ["See you tonight!","Bu akşam görüşürüz!"], ["I cannot wait!","Sabırsızlanıyorum!"] ],
         [ ["I am happy to know you.","Seni tanıdığıma memnunum."], ["You deserve a good day.","İyi bir günü hak ediyorsun."] ] ] }
 ]
},
{
 id=>"career", title=>"Kariyer ve gelecek işler", emoji=>"📈", cat=>"İş ve Okul",
 intro=>"{name} ile kariyer hakkında konuşuyorsunuz.",
 beats=>[
  { f=>[ ["I have some news. I had a job interview!","Haberlerim var. İş görüşmesine girdim!"],
         ["So, I have news. I had an interview last week and I have not stopped thinking about it.","Haberlerim var. Geçen hafta bir görüşmeye girdim ve o zamandan beri düşünüyorum."] ],
    o=>[ [ ["Really? How did it go?","Gerçekten mi? Nasıl geçti?"], ["Tell me everything!","Her şeyi anlat!"] ],
         [ ["What job is it?","Hangi iş?"], ["Where is it?","Nerede?"] ],
         [ ["Are you leaving {work}?","{work} yerinden ayrılıyor musun?"], ["I thought you liked your job!","İşini seviyorsun sanıyordum!"] ] ] },
  { f=>[ ["I like it, but I want something more.","Seviyorum ama daha fazlasını istiyorum."],
         ["I do like it, but after all these years I want something that pushes me.","Seviyorum ama bunca yıldan sonra beni zorlayacak bir şey istiyorum."] ],
    o=>[ [ ["I understand that.","Bunu anlıyorum."], ["That is a good reason.","İyi bir sebep."] ],
         [ ["What would you do there?","Orada ne yapacaksın?"], ["Is it a better salary?","Maaş daha mı iyi?"] ],
         [ ["Are you nervous?","Gergin misin?"], ["Are you sure about it?","Emin misin?"] ] ] },
  { f=>[ ["Very nervous! I did not sleep last night.","Çok gergin! Dün gece uyuyamadım."],
         ["Honestly, I am terrified. I lay awake most of last night thinking about it.","Açıkçası ödüm kopuyor. Dün gecenin çoğunu düşünerek uyanık geçirdim."] ],
    o=>[ [ ["That is normal.","Bu normal."], ["Everyone feels like that.","Herkes böyle hisseder."] ],
         [ ["You will be great.","Harika olacaksın."], ["They will choose you.","Seni seçecekler."] ],
         [ ["When do you find out?","Ne zaman öğreneceksin?"], ["How long do you wait?","Ne kadar bekleyeceksin?"] ] ] },
  { f=>[ ["They call me on Friday. Two more days!","Cuma arayacaklar. İki gün daha!"],
         ["They said Friday, so I have two more days of checking my phone every minute.","Cuma dediler, yani iki gün daha her dakika telefonuma bakacağım."] ],
    o=>[ [ ["I will think of you on Friday.","Cuma seni düşüneceğim."], ["Good luck!","Bol şans!"] ],
         [ ["Do not check your phone!","Telefonuna bakma!"], ["Try to relax.","Rahatlamaya çalış."] ],
         [ ["Tell me as soon as you know.","Öğrenir öğrenmez söyle."], ["Call me on Friday!","Cuma beni ara!"] ] ] },
  { f=>[ ["What about you? What is your dream job?","Peki ya sen? Hayalindeki iş ne?"],
         ["What about you? If money did not matter, what would you actually do?","Peki ya sen? Para önemli olmasaydı gerçekten ne yapardın?"] ],
    o=>[ [ ["I do not know yet.","Henüz bilmiyorum."], ["I am still thinking.","Hâlâ düşünüyorum."] ],
         [ ["I want to work abroad.","Yurt dışında çalışmak istiyorum."], ["Something with languages.","Dillerle ilgili bir şey."] ],
         [ ["I want my own business.","Kendi işimi istiyorum."], ["I want to be my own boss.","Kendi patronum olmak istiyorum."] ] ] },
  { f=>[ ["English will help you a lot with that.","İngilizce bu konuda sana çok yardımcı olacak."],
         ["English opens more doors than people realise. It is worth every hour you put in.","İngilizce insanların sandığından çok kapı açar. Harcadığın her saate değer."] ],
    o=>[ [ ["That is why I study.","Bu yüzden çalışıyorum."], ["I know, that is my plan.","Biliyorum, planım bu."] ],
         [ ["Is my English good enough?","İngilizcem yeterli mi?"], ["Am I improving?","Gelişiyor muyum?"] ],
         [ ["It takes so long!","Çok uzun sürüyor!"], ["I want to speak better.","Daha iyi konuşmak istiyorum."] ] ] },
  { f=>[ ["You speak better than last month. Really.","Geçen aydan daha iyi konuşuyorsun. Cidden."],
         ["You are noticeably better than when we met. I am not just being nice.","Tanıştığımızdan çok daha iyisin. Sadece nazik davranmıyorum."] ],
    o=>[ [ ["Do you really think so?","Gerçekten öyle mi düşünüyorsun?"], ["That means a lot.","Bu benim için çok değerli."] ],
         [ ["I still make mistakes.","Hâlâ hata yapıyorum."], ["I forget words when I speak.","Konuşurken kelimeleri unutuyorum."] ],
         [ ["Thank you for the confidence.","Güvenin için teşekkürler."], ["You are very kind.","Çok naziksin."] ] ] },
  { f=>[ ["Mistakes are fine. I make them in my own language!","Hatalar sorun değil. Ben kendi dilimde bile yapıyorum!"],
         ["Mistakes are part of it. I make mistakes in my own language every day.","Hatalar işin parçası. Ben kendi dilimde bile her gün hata yapıyorum."] ],
    o=>[ [ ["That makes me feel better!","Bu beni rahatlattı!"], ["Good point!","İyi noktaya değindin!"] ],
         [ ["Correct me when I am wrong.","Yanlış yaptığımda beni düzelt."], ["Please tell me my mistakes.","Lütfen hatalarımı söyle."] ],
         [ ["I am afraid of speaking.","Konuşmaktan korkuyorum."], ["I feel shy in English.","İngilizce konuşurken utanıyorum."] ] ] },
  { f=>[ ["Speak anyway. Confidence comes from doing it.","Yine de konuş. Özgüven yapmakla gelir."],
         ["Speak anyway, badly if necessary. Confidence only comes from doing the thing.","Yine de konuş, gerekirse kötü konuş. Özgüven ancak yaparak gelir."] ],
    o=>[ [ ["Okay, I will try.","Tamam, deneyeceğim."], ["I will speak more.","Daha çok konuşacağım."] ],
         [ ["With you it is easy.","Seninle kolay."], ["You are patient with me.","Bana karşı sabırlısın."] ],
         [ ["Let us talk every week.","Her hafta konuşalım."], ["Can we practise often?","Sık pratik yapabilir miyiz?"] ] ] },
  { f=>[ ["Every week, I promise. Now wish me luck! {phrase}","Her hafta, söz. Şimdi bana şans dile! {phrase}"],
         ["Every week, you have my word. Now wish me luck for Friday. {phrase}","Her hafta, söz veriyorum. Şimdi cuma için bana şans dile. {phrase}"] ],
    o=>[ [ ["Good luck, {name}!","Bol şans {name}!"], ["You will get it!","Alacaksın!"] ],
         [ ["Fingers crossed!","Parmaklarım çapraz!"], ["I believe in you.","Sana inanıyorum."] ],
         [ ["Message me on Friday.","Cuma bana yaz."], ["I want to hear the news!","Haberi duymak istiyorum!"] ] ] }
 ]
},
{
 id=>"family", title=>"Aile ve arkadaşlar", emoji=>"👨‍👩‍👧", cat=>"İnsanlar",
 intro=>"{name} ailesinden bahsediyor.",
 beats=>[
  { f=>[ ["I spoke to {family} on the phone today.","Bugün {family} ile telefonda konuştum."],
         ["I had a long phone call with {family} this morning. It was lovely.","Bu sabah {family} ile uzun uzun telefonda konuştum. Çok güzeldi."] ],
    o=>[ [ ["That is nice!","Bu güzel!"], ["How are they?","Onlar nasıl?"] ],
         [ ["Do you speak often?","Sık konuşuyor musunuz?"], ["How often do you call?","Ne sıklıkla arıyorsun?"] ],
         [ ["Do you live near them?","Onlara yakın mı oturuyorsun?"], ["Do you see them a lot?","Onları sık görüyor musun?"] ] ] },
  { f=>[ ["Family is everything for me.","Aile benim için her şey."],
         ["Family is the one thing I would never compromise on. Everything else can wait.","Aile asla taviz vermeyeceğim tek şey. Gerisi bekleyebilir."] ],
    o=>[ [ ["I feel the same.","Ben de aynı hissediyorum."], ["Family is important, yes.","Evet, aile önemli."] ],
         [ ["Tell me about them.","Bana onlardan bahset."], ["What are they like?","Nasıl insanlar?"] ],
         [ ["My family is big.","Benim ailem kalabalık."], ["I have a small family.","Benim ailem küçük."] ] ] },
  { f=>[ ["Do you have brothers or sisters?","Kardeşin var mı?"],
         ["Do you have any siblings? I always wonder about that with people.","Kardeşin var mı? İnsanlarda hep bunu merak ederim."] ],
    o=>[ [ ["Yes, one brother.","Evet, bir erkek kardeşim."], ["I have two sisters.","İki kız kardeşim var."] ],
         [ ["No, I am an only child.","Hayır, tek çocuğum."], ["Just me, no brothers or sisters.","Sadece ben, kardeşim yok."] ],
         [ ["I have a big family!","Kalabalık bir ailem var!"], ["Four brothers and sisters.","Dört kardeşim."] ] ] },
  { f=>[ ["Are you close to them?","Onlarla aran iyi mi?"],
         ["Are you close, or is it more of a birthdays and holidays situation?","Yakın mısınız, yoksa daha çok doğum günü ve bayram durumu mu?"] ],
    o=>[ [ ["Yes, very close.","Evet, çok yakınız."], ["We talk every day.","Her gün konuşuruz."] ],
         [ ["Not really, sadly.","Ne yazık ki pek değil."], ["We do not talk much.","Pek konuşmuyoruz."] ],
         [ ["It changes.","Değişiyor."], ["Sometimes yes, sometimes no.","Bazen evet, bazen hayır."] ] ] },
  { f=>[ ["Families are complicated everywhere.","Aileler her yerde karışıktır."],
         ["Every family is complicated. Anyone who says otherwise is hiding something.","Her aile karışıktır. Aksini söyleyen bir şey saklıyordur."] ],
    o=>[ [ ["That is true!","Bu doğru!"], ["You are right about that.","Bu konuda haklısın."] ],
         [ ["Do you argue with yours?","Seninkilerle tartışıyor musun?"], ["Any family problems?","Aile sorunu var mı?"] ],
         [ ["My family is complicated too.","Benim ailem de karışık."], ["It is not always easy.","Her zaman kolay değil."] ] ] },
  { f=>[ ["And friends? Do you have good friends here?","Peki arkadaşlar? Burada iyi arkadaşların var mı?"],
         ["What about friends? Do you have people around you, or is it quiet?","Peki arkadaşlar? Etrafında insanlar var mı, yoksa sessiz mi?"] ],
    o=>[ [ ["A few good ones.","Birkaç iyi arkadaşım var."], ["Two or three close friends.","İki üç yakın arkadaş."] ],
         [ ["Not many, honestly.","Açıkçası çok değil."], ["It is hard to make friends.","Arkadaş edinmek zor."] ],
         [ ["I have you!","Sen varsın!"], ["You are one of them.","Sen de onlardansın."] ] ] },
  { f=>[ ["Making friends as an adult is hard. Really hard.","Yetişkinken arkadaş edinmek zor. Çok zor."],
         ["Making friends after thirty is genuinely difficult. Nobody warns you about that.","Otuzdan sonra arkadaş edinmek gerçekten zor. Kimse seni bu konuda uyarmıyor."] ],
    o=>[ [ ["I agree completely.","Tamamen katılıyorum."], ["That is so true.","Çok doğru."] ],
         [ ["How did you meet your friends?","Arkadaşlarınla nasıl tanıştın?"], ["Where do you meet people?","İnsanlarla nerede tanışıyorsun?"] ],
         [ ["I met you, so it is possible!","Seninle tanıştım, demek ki mümkün!"], ["We became friends easily.","Kolayca arkadaş olduk."] ] ] },
  { f=>[ ["That is true. We talk easily, you and me.","Bu doğru. Seninle rahat konuşuyoruz."],
         ["We do talk easily, you and I. That does not happen with everyone.","Seninle rahat konuşuyoruz gerçekten. Bu herkesle olmuyor."] ],
    o=>[ [ ["I feel that too.","Ben de öyle hissediyorum."], ["It feels natural.","Doğal geliyor."] ],
         [ ["You are easy to talk to.","Seninle konuşmak kolay."], ["You listen well.","İyi dinliyorsun."] ],
         [ ["Thank you for being my friend.","Arkadaşım olduğun için teşekkürler."], ["I am glad we met.","Tanıştığımıza sevindim."] ] ] },
  { f=>[ ["Do you miss anyone? A person far away?","Birini özlüyor musun? Uzaktaki birini?"],
         ["Is there anyone you really miss? Someone far away, I mean.","Gerçekten özlediğin biri var mı? Uzaktaki biri yani."] ],
    o=>[ [ ["Yes, my family.","Evet, ailemi."], ["I miss my parents.","Anne babamı özlüyorum."] ],
         [ ["An old friend, yes.","Evet, eski bir arkadaşımı."], ["Someone from school.","Okuldan biri."] ],
         [ ["No, everyone is near me.","Hayır, herkes yakınımda."], ["I am lucky that way.","O konuda şanslıyım."] ] ] },
  { f=>[ ["Call them tonight. People do not stay forever. {phrase}","Bu akşam onları ara. İnsanlar sonsuza kadar kalmıyor. {phrase}"],
         ["Ring them tonight, not next week. People are not here forever. {phrase}","Haftaya değil, bu akşam ara. İnsanlar sonsuza kadar burada değil. {phrase}"] ],
    o=>[ [ ["You are right. I will call.","Haklısın. Arayacağım."], ["I will call tonight.","Bu akşam arayacağım."] ],
         [ ["That was deep, {name}.","Derin bir söz oldu {name}."], ["Now I feel emotional!","Şimdi duygulandım!"] ],
         [ ["Thank you for reminding me.","Hatırlattığın için sağ ol."], ["You are a good friend.","İyi bir arkadaşsın."] ] ] }
 ]
},
{
 id=>"badday", title=>"Kötü bir gün", emoji=>"🌧️", cat=>"İnsanlar",
 intro=>"{name} bugün biraz keyifsiz.",
 beats=>[
  { f=>[ ["I have had a terrible day, honestly.","Açıkçası berbat bir gün geçirdim."],
         ["Today has been one of those days where everything goes slightly wrong.","Bugün her şeyin biraz ters gittiği günlerden biriydi."] ],
    o=>[ [ ["What happened?","Ne oldu?"], ["Tell me about it.","Anlat bakalım."] ],
         [ ["I am sorry to hear that.","Bunu duyduğuma üzüldüm."], ["That is not good.","Bu hiç iyi değil."] ],
         [ ["Do you want to talk?","Konuşmak ister misin?"], ["I am here if you need me.","İhtiyacın olursa buradayım."] ] ] },
  { f=>[ ["I woke up late and arrived at {work} an hour late.","Geç kalktım ve {work} yerine bir saat geç gittim."],
         ["It started badly: I overslept, then walked into {work} a full hour late.","Kötü başladı: uyuyakaldım, sonra {work} yerine tam bir saat geç gittim."] ],
    o=>[ [ ["That is a bad start.","Kötü bir başlangıç."], ["Everyone has those mornings.","Herkesin öyle sabahları olur."] ],
         [ ["Were you late for work?","İşe geç mi kaldın?"], ["Did they say anything?","Bir şey dediler mi?"] ],
         [ ["That happened to me too.","Bu benim de başıma geldi."], ["I hate mornings like that.","Öyle sabahlardan nefret ederim."] ] ] },
  { f=>[ ["Then it rained and I had no umbrella.","Sonra yağmur yağdı ve şemsiyem yoktu."],
         ["Then it poured with rain, of course, and my umbrella was at home.","Sonra tabii ki bardaktan boşanırcasına yağdı ve şemsiyem evdeydi."] ],
    o=>[ [ ["Oh no! Poor you.","Olamaz! Vah vah."], ["That is really unlucky.","Çok şanssızlık."] ],
         [ ["Did you get very wet?","Çok ıslandın mı?"], ["Were you cold all day?","Bütün gün üşüdün mü?"] ],
         [ ["At least it is over now.","En azından şimdi bitti."], ["The day is finished.","Gün bitti."] ] ] },
  { f=>[ ["And I made a mistake at {work}. I felt stupid.","Ve {work} yerinde hata yaptım. Kendimi aptal hissettim."],
         ["Worst of all, I made a stupid mistake at {work} in front of everyone.","En kötüsü, {work} yerinde herkesin önünde aptalca bir hata yaptım."] ],
    o=>[ [ ["Everyone makes mistakes.","Herkes hata yapar."], ["Do not be hard on yourself.","Kendine yüklenme."] ],
         [ ["Was it a big mistake?","Büyük bir hata mıydı?"], ["What did people say?","İnsanlar ne dedi?"] ],
         [ ["Tomorrow nobody will remember.","Yarın kimse hatırlamayacak."], ["It will be forgotten.","Unutulacak."] ] ] },
  { f=>[ ["You are right. But it stays in my head.","Haklısın. Ama kafamdan çıkmıyor."],
         ["I know that, logically. But it keeps replaying in my head anyway.","Mantıken biliyorum. Ama yine de kafamda dönüp duruyor."] ],
    o=>[ [ ["I understand that feeling.","O hissi anlıyorum."], ["That happens to me too.","Bana da oluyor."] ],
         [ ["Try to think of something else.","Başka bir şey düşünmeye çalış."], ["Do something you enjoy.","Sevdiğin bir şey yap."] ],
         [ ["Talking helps, they say.","Konuşmak iyi gelirmiş."], ["Keep talking, I am listening.","Konuşmaya devam et, dinliyorum."] ] ] },
  { f=>[ ["Thank you for listening. Not everyone does.","Dinlediğin için sağ ol. Herkes dinlemez."],
         ["Thank you for actually listening. Most people just wait for their turn to talk.","Gerçekten dinlediğin için sağ ol. Çoğu insan sadece konuşma sırasını bekler."] ],
    o=>[ [ ["That is what friends do.","Arkadaşlar bunun için var."], ["Any time, really.","Ne zaman istersen, cidden."] ],
         [ ["You listen to me too.","Sen de beni dinliyorsun."], ["We help each other.","Birbirimize yardım ediyoruz."] ],
         [ ["Do you feel better now?","Şimdi daha iyi misin?"], ["Any better?","Biraz iyileştin mi?"] ] ] },
  { f=>[ ["A bit better, yes. What do you do on bad days?","Biraz daha iyi, evet. Sen kötü günlerde ne yaparsın?"],
         ["A little better, actually. What do you do when you have a day like this?","Aslında biraz daha iyi. Sen böyle bir gün geçirince ne yaparsın?"] ],
    o=>[ [ ["I sleep early.","Erken uyurum."], ["I go to bed and start again.","Yatarım, yeniden başlarım."] ],
         [ ["I call a friend.","Bir arkadaşımı ararım."], ["I talk to someone.","Biriyle konuşurum."] ],
         [ ["I eat something nice.","Güzel bir şeyler yerim."], ["Chocolate helps me!","Çikolata bana iyi geliyor!"] ] ] },
  { f=>[ ["Good plan. I will do {hobby} tonight.","İyi plan. Ben bu akşam {hobby} yapacağım."],
         ["That is sensible. I think I will do {hobby} tonight and forget about today.","Mantıklı. Bu akşam {hobby} yapıp bugünü unutacağım galiba."] ],
    o=>[ [ ["That sounds perfect.","Mükemmel geliyor."], ["Enjoy it.","Keyfini çıkar."] ],
         [ ["Send me a photo after.","Sonra bana fotoğraf gönder."], ["Tell me how it goes.","Nasıl geçtiğini söyle."] ],
         [ ["Tomorrow will be better.","Yarın daha iyi olacak."], ["A new day tomorrow.","Yarın yeni bir gün."] ] ] },
  { f=>[ ["Tomorrow is a new day. I like that.","Yarın yeni bir gün. Bunu sevdim."],
         ["Tomorrow is a new day, you are right. I needed to hear that today.","Yarın yeni bir gün, haklısın. Bugün bunu duymaya ihtiyacım vardı."] ],
    o=>[ [ ["We say that in Turkish too.","Biz de Türkçede böyle deriz."], ["It is true in every language.","Her dilde doğru."] ],
         [ ["Get some rest tonight.","Bu akşam biraz dinlen."], ["Sleep well, okay?","İyi uyu, tamam mı?"] ],
         [ ["Message me tomorrow.","Yarın bana yaz."], ["Tell me if it is better.","Daha iyi olursa söyle."] ] ] },
  { f=>[ ["I will. Thank you for today, really. {phrase}","Yazarım. Bugün için gerçekten teşekkürler. {phrase}"],
         ["I will message you. And thank you for today, I mean it. {phrase}","Sana yazarım. Ve bugün için teşekkürler, ciddiyim. {phrase}"] ],
    o=>[ [ ["Good night, {name}.","İyi geceler {name}."], ["Sleep well.","İyi uykular."] ],
         [ ["Call me any time.","İstediğin zaman ara."], ["I am always here.","Ben hep buradayım."] ],
         [ ["Tomorrow will be good!","Yarın güzel olacak!"], ["Take care of yourself.","Kendine iyi bak."] ] ] }
 ]
},
{
 id=>"future", title=>"Gelecek hayalleri", emoji=>"✨", cat=>"İnsanlar",
 intro=>"{name} ile geleceği konuşuyorsunuz.",
 beats=>[
  { f=>[ ["Where do you want to be in five years?","Beş yıl sonra nerede olmak istiyorsun?"],
         ["Big question for you: where do you want to be in five years time?","Sana büyük bir soru: beş yıl sonra nerede olmak istiyorsun?"] ],
    o=>[ [ ["I have no idea.","Hiçbir fikrim yok."], ["I do not plan that far.","O kadar uzağı planlamam."] ],
         [ ["In another country, maybe.","Belki başka bir ülkede."], ["Living abroad, I hope.","Umarım yurt dışında."] ],
         [ ["Doing a job I love.","Sevdiğim bir işi yaparken."], ["Happier than now.","Şimdikinden mutlu."] ] ] },
  { f=>[ ["My plan is {dream}. I think about it a lot.","Benim planım {dream}. Bunu çok düşünüyorum."],
         ["For me the answer is simple: {dream}. I think about it more than I should.","Benim için cevap basit: {dream}. Gerekenden fazla düşünüyorum."] ],
    o=>[ [ ["That is a beautiful dream.","Bu güzel bir hayal."], ["I hope you do it.","Umarım yaparsın."] ],
         [ ["Is it possible?","Mümkün mü?"], ["What do you need first?","Önce neye ihtiyacın var?"] ],
         [ ["When will you start?","Ne zaman başlayacaksın?"], ["Do you have a plan?","Bir planın var mı?"] ] ] },
  { f=>[ ["I save money every month. Slowly.","Her ay para biriktiriyorum. Yavaş yavaş."],
         ["I put a little away every month. It is slow, but it is moving.","Her ay biraz kenara koyuyorum. Yavaş ama ilerliyor."] ],
    o=>[ [ ["That is smart.","Bu akıllıca."], ["Small steps work.","Küçük adımlar işe yarar."] ],
         [ ["Saving is hard for me.","Para biriktirmek bana zor geliyor."], ["I spend too much.","Çok harcıyorum."] ],
         [ ["How much do you save?","Ne kadar biriktiriyorsun?"], ["Do you have a target?","Bir hedefin var mı?"] ] ] },
  { f=>[ ["Do you want to live in another country?","Başka bir ülkede yaşamak ister misin?"],
         ["Would you ever move abroad permanently, or is that too big a step?","Hiç temelli yurt dışına taşınır mıydın, yoksa çok mu büyük bir adım?"] ],
    o=>[ [ ["Yes, I think about it.","Evet, düşünüyorum."], ["That is my dream too.","Benim de hayalim bu."] ],
         [ ["No, I love my country.","Hayır, ülkemi seviyorum."], ["My family is here.","Ailem burada."] ],
         [ ["Maybe for a few years.","Belki birkaç yıllığına."], ["To work, not forever.","Çalışmak için, temelli değil."] ] ] },
  { f=>[ ["Which country? Tell me.","Hangi ülke? Söyle bakalım."],
         ["Which country would it be? Everyone has one in their head.","Hangi ülke olurdu? Herkesin kafasında bir tane var."] ],
    o=>[ [ ["England, maybe.","Belki İngiltere."], ["Somewhere in Europe.","Avrupa'da bir yer."] ],
         [ ["Canada or Australia.","Kanada ya da Avustralya."], ["Somewhere with nature.","Doğası olan bir yer."] ],
         [ ["I would visit {city} first!","Önce {city} gelirdim!"], ["Your city, of course!","Tabii ki senin şehrin!"] ] ] },
  { f=>[ ["Then you must come and stay with me!","O zaman gelip bende kalmalısın!"],
         ["Then it is decided. When you come, you stay with me, no arguments.","O zaman karar verildi. Geldiğinde bende kalıyorsun, tartışma yok."] ],
    o=>[ [ ["Really? Thank you!","Gerçekten mi? Teşekkürler!"], ["I would love that!","Buna bayılırım!"] ],
         [ ["I do not want to be a problem.","Sorun olmak istemem."], ["Are you sure?","Emin misin?"] ],
         [ ["Then you come to Turkey!","O zaman sen de Türkiye'ye gel!"], ["My home is yours too.","Benim evim de senin."] ] ] },
  { f=>[ ["I would love to see Turkey. Really.","Türkiye'yi görmeyi çok isterim. Cidden."],
         ["I have wanted to visit Turkey for years. The food alone would be worth it.","Yıllardır Türkiye'yi görmek istiyorum. Sadece yemekler bile buna değer."] ],
    o=>[ [ ["I will show you everything!","Sana her şeyi göstereceğim!"], ["You will love it.","Bayılacaksın."] ],
         [ ["Which city do you want to see?","Hangi şehri görmek istersin?"], ["Istanbul or the coast?","İstanbul mu sahil mi?"] ],
         [ ["Come in spring, it is perfect.","İlkbaharda gel, mükemmel olur."], ["Not in summer, too hot!","Yazın değil, çok sıcak!"] ] ] },
  { f=>[ ["It is nice to make plans. Even small ones.","Plan yapmak güzel. Küçük olsa bile."],
         ["Making plans is important, even the ones that never happen. They keep you going.","Plan yapmak önemli, hiç gerçekleşmeyenler bile. İnsanı ayakta tutuyor."] ],
    o=>[ [ ["I agree.","Katılıyorum."], ["Plans give hope.","Planlar umut veriyor."] ],
         [ ["I never plan anything!","Ben hiç plan yapmam!"], ["I live day by day.","Günü gününe yaşarım."] ],
         [ ["Let us make a real plan.","Gerçek bir plan yapalım."], ["Give me a date!","Bana bir tarih ver!"] ] ] },
  { f=>[ ["Next summer. Let us say next summer.","Gelecek yaz. Gelecek yaz diyelim."],
         ["Next summer, then. Let us say it out loud so it becomes real.","O zaman gelecek yaz. Yüksek sesle söyleyelim ki gerçek olsun."] ],
    o=>[ [ ["Next summer! Deal.","Gelecek yaz! Anlaştık."], ["It is a promise.","Söz olsun."] ],
         [ ["I will start saving.","Para biriktirmeye başlayacağım."], ["I need to save money.","Para biriktirmem lazım."] ],
         [ ["Do not forget this talk!","Bu konuşmayı unutma!"], ["I will remind you!","Sana hatırlatacağım!"] ] ] },
  { f=>[ ["I will not forget. Thank you for the dream. {phrase}","Unutmayacağım. Hayal için teşekkürler. {phrase}"],
         ["I will not forget this conversation. Thank you for the dream, honestly. {phrase}","Bu konuşmayı unutmayacağım. Hayal için cidden teşekkürler. {phrase}"] ],
    o=>[ [ ["See you next summer!","Gelecek yaz görüşürüz!"], ["It is going to happen.","Bu olacak."] ],
         [ ["Thank you for today, {name}.","Bugün için teşekkürler {name}."], ["I enjoyed this talk.","Bu sohbetten keyif aldım."] ],
         [ ["Talk to me again tomorrow.","Yarın yine konuş benimle."], ["Same time next week?","Haftaya aynı saatte?"] ] ] }
 ]
}
]
