use utf8;
# Sahne iskeleti: her "beat" bir tur.
#   f => [ [basit_en, tr], [ileri_en, tr] ]   -> arkadaşın cümlesi (seviyeye göre seçilir)
#   o => 3 cevap seçeneği, her birinin 2 farklı yazımı
# {slot} ifadeleri karaktere göre doldurulur (TR tarafında otomatik Türkçe karşılığı kullanılır).
[
{
 id=>"cafe", title=>"Kafede buluşma", emoji=>"☕", cat=>"Günlük Hayat",
 intro=>"{name} ile şehrin merkezindeki bir kafede buluştunuz.",
 beats=>[
  { f=>[ ["Hey! You are here! Sit down, sit down.","Hey! Gelmişsin! Otur, otur."],
         ["There you are! I got us a table by the window. Come and sit down.","İşte buradasın! Pencere kenarında masa tuttum. Gel otur."] ],
    o=>[ [ ["Sorry, I am a bit late.","Kusura bakma, biraz geç kaldım."], ["Sorry! The traffic was terrible.","Pardon! Trafik berbattı."] ],
         [ ["Hi {name}! Nice place.","Selam {name}! Güzel yermiş."], ["Hello! Wow, I like this café.","Merhaba! Vay, bu kafeyi sevdim."] ],
         [ ["I really needed this today.","Buna bugün gerçekten ihtiyacım vardı."], ["Perfect timing, I am so tired.","Tam zamanı, çok yorgunum."] ] ] },
  { f=>[ ["How are you today?","Bugün nasılsın?"],
         ["So, how have you been? I feel like we never talk properly.","Ee, nasıl gidiyor? Sanki hiç doğru düzgün konuşamıyoruz."] ],
    o=>[ [ ["I am fine, thanks. And you?","İyiyim, sağ ol. Sen nasılsın?"], ["Pretty good, thanks. What about you?","Gayet iyiyim, sağ ol. Ya sen?"] ],
         [ ["I am very tired this week.","Bu hafta çok yorgunum."], ["Honestly, I am exhausted.","Açıkçası bitkinim."] ],
         [ ["Not bad. Busy, but okay.","Fena değil. Yoğun ama iyiyim."], ["Same as always, you know.","Her zamanki gibi işte."] ] ] },
  { f=>[ ["I always drink {drink} here. What do you want?","Ben burada hep {drink} içerim. Sen ne istersin?"],
         ["I am having {drink} as usual. Do you know what you want to order?","Ben her zamanki gibi {drink} alıyorum. Ne söyleyeceğini biliyor musun?"] ],
    o=>[ [ ["I will have the same, please.","Ben de aynısından alayım."], ["The same for me, that sounds good.","Bana da aynısı, kulağa güzel geliyor."] ],
         [ ["Just a black coffee for me.","Bana sade bir kahve yeter."], ["I only want water, thanks.","Sadece su istiyorum, sağ ol."] ],
         [ ["What do you recommend?","Sen ne tavsiye edersin?"], ["What is good here?","Burada ne güzel?"] ] ] },
  { f=>[ ["Are you hungry? The cake here is very good.","Aç mısın? Buranın keki çok güzel."],
         ["Shall we get something to eat as well? The cake here is honestly excellent.","Bir şeyler de yiyelim mi? Buranın keki cidden çok iyi."] ],
    o=>[ [ ["Yes, please. I am hungry.","Evet lütfen. Açım."], ["Good idea, I did not have lunch.","İyi fikir, öğle yemeği yemedim."] ],
         [ ["No, thank you. I ate before.","Yok, sağ ol. Önceden yedim."], ["I am full, but thank you.","Tokum ama teşekkürler."] ],
         [ ["Maybe we can share one?","Belki birini paylaşırız?"], ["Let us share, I cannot finish a whole one.","Paylaşalım, tamamını bitiremem."] ] ] },
  { f=>[ ["I work at {work}, so I know all the cafés here.","{work} yerinde çalışıyorum, o yüzden buradaki bütün kafeleri bilirim."],
         ["Working at {work} means I have tried every café in {city} by now.","{work} yerinde çalışmak, {city} şehrindeki her kafeyi denemişim demek."] ],
    o=>[ [ ["Do you like your job?","İşini seviyor musun?"], ["Is your job hard?","İşin zor mu?"] ],
         [ ["How long have you worked there?","Ne zamandır orada çalışıyorsun?"], ["When did you start that job?","O işe ne zaman başladın?"] ],
         [ ["That sounds interesting.","Kulağa ilginç geliyor."], ["Lucky you!","Ne şanslısın!"] ] ] },
  { f=>[ ["I like it. I am {job} and the people are nice.","Seviyorum. {job} olarak çalışıyorum ve insanlar iyi."],
         ["I do enjoy it. Being {job} is tiring, but the people make it worth it.","Gerçekten seviyorum. {job} olmak yorucu ama insanlar buna değer kılıyor."] ],
    o=>[ [ ["That is nice to hear.","Bunu duymak güzel."], ["I am happy for you.","Senin adına sevindim."] ],
         [ ["What time do you start work?","İşe kaçta başlıyorsun?"], ["Do you work at weekends too?","Hafta sonu da çalışıyor musun?"] ],
         [ ["Would you like to change job one day?","Bir gün iş değiştirmek ister misin?"], ["Do you want to do this forever?","Bunu hep yapmak istiyor musun?"] ] ] },
  { f=>[ ["One day I want {dream}. That is my plan.","Bir gün {dream} istiyorum. Planım bu."],
         ["My real dream is {dream}. I think about it every single day.","Asıl hayalim {dream}. Her gün bunu düşünüyorum."] ],
    o=>[ [ ["That is a great dream!","Harika bir hayal!"], ["I hope it happens.","Umarım olur."] ],
         [ ["Is it expensive to do that?","Bunu yapmak pahalı mı?"], ["What do you need for that?","Bunun için neye ihtiyacın var?"] ],
         [ ["I can help you if you want.","İstersen sana yardım edebilirim."], ["Tell me more about it.","Bana biraz daha anlat."] ] ] },
  { f=>[ ["What about you? What did you do this week?","Peki ya sen? Bu hafta ne yaptın?"],
         ["Enough about me. Tell me what you have been up to this week.","Benden bu kadar. Anlat bakalım, bu hafta neler yaptın?"] ],
    o=>[ [ ["I worked a lot and slept a little.","Çok çalıştım, az uyudum."], ["Just work, honestly.","Açıkçası sadece iş."] ],
         [ ["I studied English every evening.","Her akşam İngilizce çalıştım."], ["I am learning English, so I practise a lot.","İngilizce öğreniyorum, o yüzden çok pratik yapıyorum."] ],
         [ ["I stayed at home and watched films.","Evde kalıp film izledim."], ["Nothing special, I relaxed.","Özel bir şey yok, dinlendim."] ] ] },
  { f=>[ ["Look outside. I love {weather}.","Dışarı bak. {weather} bayılırım."],
         ["Look at the sky. You know me, I could sit here all day when it is like this.","Gökyüzüne bak. Beni bilirsin, böyle havada bütün gün burada oturabilirim."] ],
    o=>[ [ ["Me too. It is beautiful.","Ben de. Çok güzel."], ["Yes, the weather is perfect today.","Evet, bugün hava mükemmel."] ],
         [ ["I prefer sunny weather.","Ben güneşli havayı tercih ederim."], ["I do not like this weather much.","Bu havayı pek sevmiyorum."] ],
         [ ["Shall we go for a walk after this?","Bundan sonra yürüyüşe çıkalım mı?"], ["Do you want to walk a bit later?","Sonra biraz yürümek ister misin?"] ] ] },
  { f=>[ ["Okay, I must go now. {phrase}","Tamam, artık gitmeliyim. {phrase}"],
         ["Right, I really should get going. Same time next week? {phrase}","Tamam, gerçekten çıkmalıyım. Haftaya aynı saatte? {phrase}"] ],
    o=>[ [ ["See you next week!","Haftaya görüşürüz!"], ["Yes, same time. See you!","Evet, aynı saatte. Görüşürüz!"] ],
         [ ["Thank you for the coffee.","Kahve için teşekkürler."], ["Thanks, it was really nice.","Sağ ol, çok güzeldi."] ],
         [ ["Text me when you get home.","Eve varınca mesaj at."], ["Have a good day, {name}!","İyi günler {name}!"] ] ] }
 ]
},
{
 id=>"breakfast", title=>"Kahvaltı sohbeti", emoji=>"🍳", cat=>"Günlük Hayat",
 intro=>"Sabah erken saat, {name} ile kahvaltı ediyorsunuz.",
 beats=>[
  { f=>[ ["Good morning! Did you sleep well?","Günaydın! İyi uyudun mu?"],
         ["Morning! You look like you did not sleep much. Am I right?","Günaydın! Pek uyumamış gibisin. Yanılıyor muyum?"] ],
    o=>[ [ ["Good morning! Yes, I slept well.","Günaydın! Evet, iyi uyudum."], ["Morning! I slept like a baby.","Günaydın! Mışıl mışıl uyudum."] ],
         [ ["Not really. I woke up at three.","Pek değil. Üçte uyandım."], ["No, I had a terrible night.","Hayır, berbat bir gece geçirdim."] ],
         [ ["I need coffee first.","Önce kahve lazım bana."], ["Do not talk to me before coffee!","Kahveden önce benimle konuşma!"] ] ] },
  { f=>[ ["I always eat {breakfast} in the morning.","Sabahları hep {breakfast} yerim."],
         ["I have {breakfast} nearly every morning. I am very boring like that.","Neredeyse her sabah {breakfast} yiyorum. Bu konuda çok sıkıcıyım."] ],
    o=>[ [ ["That sounds nice.","Kulağa güzel geliyor."], ["I want to try that.","Onu denemek isterim."] ],
         [ ["I usually eat eggs and bread.","Ben genelde yumurta ve ekmek yerim."], ["I eat cheese, olives and tomatoes.","Peynir, zeytin ve domates yerim."] ],
         [ ["I never eat breakfast.","Ben hiç kahvaltı yapmam."], ["I only drink tea in the morning.","Sabahları sadece çay içerim."] ] ] },
  { f=>[ ["You must eat breakfast! It is important.","Kahvaltı yapmalısın! Önemli bir şey."],
         ["You really should eat something. Breakfast makes a big difference, trust me.","Gerçekten bir şeyler yemelisin. Kahvaltı çok fark yaratır, inan bana."] ],
    o=>[ [ ["You are right. I will try.","Haklısın. Deneyeceğim."], ["Okay okay, I will eat something.","Tamam tamam, bir şeyler yerim."] ],
         [ ["I have no time in the morning.","Sabahları hiç vaktim yok."], ["I wake up too late for breakfast.","Kahvaltı için çok geç kalkıyorum."] ],
         [ ["I am not hungry in the morning.","Sabahları aç olmuyorum."], ["My stomach does not want food early.","Midem erken saatte yemek istemiyor."] ] ] },
  { f=>[ ["What time do you get up?","Saat kaçta kalkıyorsun?"],
         ["What time do you usually get up during the week?","Hafta içi genelde saat kaçta kalkıyorsun?"] ],
    o=>[ [ ["At seven o'clock.","Saat yedide."], ["Around half past six.","Altı buçuk gibi."] ],
         [ ["Very late. About eleven.","Çok geç. On bir gibi."], ["Too late, honestly.","Açıkçası fazla geç."] ],
         [ ["It depends on the day.","Güne göre değişir."], ["Early in the week, late at weekends.","Hafta içi erken, hafta sonu geç."] ] ] },
  { f=>[ ["I get up early because of {work}.","{work} yüzünden erken kalkıyorum."],
         ["I am up early because of {work}. My alarm goes off before the sun.","{work} yüzünden erken kalkıyorum. Alarmım güneşten önce çalıyor."] ],
    o=>[ [ ["That is very early!","Bu çok erken!"], ["I could never do that.","Ben bunu asla yapamam."] ],
         [ ["Do you go to bed early too?","Erken de mi yatıyorsun?"], ["When do you sleep then?","Peki ne zaman uyuyorsun?"] ],
         [ ["Are you tired all the time?","Sürekli yorgun musun?"], ["How do you have energy?","Enerjiyi nereden buluyorsun?"] ] ] },
  { f=>[ ["Coffee helps. I drink {drink} every day.","Kahve yardımcı oluyor. Her gün {drink} içerim."],
         ["Coffee is the answer. I have {drink} every single day, sometimes twice.","Cevap kahve. Her gün {drink} içerim, bazen iki kez."] ],
    o=>[ [ ["I drink tea, not coffee.","Ben çay içerim, kahve değil."], ["Turkish tea is my favourite.","En sevdiğim Türk çayı."] ],
         [ ["Is that not too much coffee?","Bu çok fazla kahve değil mi?"], ["Does it keep you awake at night?","Geceleri uyutmuyor mu?"] ],
         [ ["I drink coffee too, three cups.","Ben de kahve içerim, üç fincan."], ["Same here, I love coffee.","Ben de öyle, kahveye bayılırım."] ] ] },
  { f=>[ ["Do you cook at home or eat outside?","Evde mi pişiriyorsun yoksa dışarıda mı yiyorsun?"],
         ["Do you cook for yourself, or do you eat out most of the time?","Kendine yemek yapıyor musun, yoksa çoğunlukla dışarıda mı yiyorsun?"] ],
    o=>[ [ ["I cook at home. It is cheaper.","Evde pişiriyorum. Daha ucuz."], ["I always cook. I like cooking.","Hep pişiririm. Yemek yapmayı severim."] ],
         [ ["I eat outside a lot.","Sık sık dışarıda yerim."], ["I order food too often.","Fazla sık yemek söylüyorum."] ],
         [ ["I cannot cook at all.","Hiç yemek yapamam."], ["My cooking is terrible.","Yemeklerim berbat."] ] ] },
  { f=>[ ["My favourite food is {food}. Have you tried it?","En sevdiğim yemek {food}. Hiç denedin mi?"],
         ["If I had to choose one meal forever, it would be {food}. Have you ever tried it?","Ömrüm boyunca tek yemek seçseydim {food} olurdu. Hiç denedin mi?"] ],
    o=>[ [ ["No, but I want to.","Hayır ama denemek isterim."], ["Never. What is in it?","Hiç. İçinde ne var?"] ],
         [ ["Yes! I love it.","Evet! Bayılıyorum."], ["I tried it once, it was good.","Bir kez denedim, güzeldi."] ],
         [ ["My favourite is kebab.","Benim favorim kebap."], ["I prefer soup and bread.","Ben çorba ve ekmeği tercih ederim."] ] ] },
  { f=>[ ["Next time I will cook for you.","Bir dahaki sefere sana yemek yapacağım."],
         ["You know what? Next time come to mine and I will cook properly for you.","Bak ne diyeceğim? Bir dahaki sefere bize gel, sana adam gibi yemek yapayım."] ],
    o=>[ [ ["Really? Thank you!","Gerçekten mi? Teşekkürler!"], ["I would love that.","Buna bayılırım."] ],
         [ ["Only if I bring dessert.","Ancak tatlıyı ben getirirsem."], ["I will bring something too.","Ben de bir şeyler getiririm."] ],
         [ ["When? I am free on Sunday.","Ne zaman? Pazar günü müsaitim."], ["Give me a day and I am there.","Bir gün söyle, oradayım."] ] ] },
  { f=>[ ["Okay, I have to go to work. See you!","Tamam, işe gitmem lazım. Görüşürüz!"],
         ["Right, work is calling. Thanks for the breakfast, this was lovely.","Tamam, iş çağırıyor. Kahvaltı için sağ ol, çok güzeldi."] ],
    o=>[ [ ["Have a good day!","İyi günler!"], ["Good luck at work!","İşte kolay gelsin!"] ],
         [ ["Thanks for the breakfast.","Kahvaltı için teşekkürler."], ["That was lovely, thank you.","Çok güzeldi, teşekkür ederim."] ],
         [ ["Call me later!","Sonra beni ara!"], ["See you soon, {name}.","Yakında görüşürüz {name}."] ] ] }
 ]
},
{
 id=>"restaurant", title=>"Restoranda akşam yemeği", emoji=>"🍽️", cat=>"Günlük Hayat",
 intro=>"{name} ile akşam yemeği için bir restorandasınız.",
 beats=>[
  { f=>[ ["This restaurant is my favourite. Look at the menu.","Bu restoran benim favorim. Menüye bak."],
         ["I have been coming here for years. Take your time with the menu.","Yıllardır buraya geliyorum. Menüye rahat rahat bak."] ],
    o=>[ [ ["It looks lovely here.","Burası çok hoş görünüyor."], ["Nice place! Very warm.","Güzel yer! Çok sıcak bir havası var."] ],
         [ ["There are too many options!","Çok fazla seçenek var!"], ["I do not know what to choose.","Ne seçeceğimi bilmiyorum."] ],
         [ ["Is it expensive?","Pahalı mı?"], ["What is the price like here?","Buranın fiyatları nasıl?"] ] ] },
  { f=>[ ["Try the {food}. It is the best thing here.","{food} dene. Buranın en güzel şeyi."],
         ["Honestly, order the {food}. I would not eat anything else here.","Cidden, {food} söyle. Burada başka bir şey yemem."] ],
    o=>[ [ ["Okay, I will try it.","Tamam, onu deneyeceğim."], ["You choose for me.","Sen benim için seç."] ],
         [ ["Is it spicy?","Acı mı?"], ["Does it have meat in it?","İçinde et var mı?"] ],
         [ ["I want to try something else.","Ben başka bir şey denemek istiyorum."], ["Maybe the chicken instead.","Belki onun yerine tavuk."] ] ] },
  { f=>[ ["Do you want a starter first?","Önce başlangıç ister misin?"],
         ["Shall we get a starter to share while we wait?","Beklerken paylaşmak için bir başlangıç alalım mı?"] ],
    o=>[ [ ["Yes, soup please.","Evet, çorba lütfen."], ["Good idea, I am hungry.","İyi fikir, açım."] ],
         [ ["No, the main course is enough.","Hayır, ana yemek yeterli."], ["I will save space for dessert.","Tatlıya yer bırakacağım."] ],
         [ ["What do you usually get?","Sen genelde ne alırsın?"], ["Whatever you get, I will get.","Sen ne alırsan ben de onu alırım."] ] ] },
  { f=>[ ["Something to drink? I am having {drink}.","İçecek bir şey? Ben {drink} alıyorum."],
         ["What are you drinking? I am sticking with {drink}, as always.","Sen ne içiyorsun? Ben her zamanki gibi {drink} alıyorum."] ],
    o=>[ [ ["Just water for me, thanks.","Bana sadece su, sağ ol."], ["Water is fine.","Su yeterli."] ],
         [ ["I will have the same as you.","Ben de seninkinden alayım."], ["That sounds good, same please.","Kulağa güzel geliyor, aynısı lütfen."] ],
         [ ["Do they have fresh juice?","Taze meyve suyu var mı?"], ["I would like a cold drink.","Soğuk bir şey isterim."] ] ] },
  { f=>[ ["{family} love this place too.","{family} da burayı çok sever."],
         ["I come here with {family} quite often. It is a bit of a tradition now.","Buraya {family} ile sık sık gelirim. Artık bir gelenek oldu."] ],
    o=>[ [ ["Tell me about your family.","Bana ailenden bahset."], ["Do you see them often?","Onları sık görüyor musun?"] ],
         [ ["That is really nice.","Bu çok güzel."], ["Family time is important.","Aile zamanı önemli."] ],
         [ ["My family is far from me.","Benim ailem uzakta."], ["I miss my family a lot.","Ailemi çok özlüyorum."] ] ] },
  { f=>[ ["The food is here. It smells amazing!","Yemek geldi. Kokusu harika!"],
         ["Here we go. Look at that, it smells incredible, does it not?","İşte geldi. Şuna bak, kokusu inanılmaz değil mi?"] ],
    o=>[ [ ["It looks delicious!","Çok lezzetli görünüyor!"], ["Wow, big plate!","Vay, kocaman tabak!"] ],
         [ ["Enjoy your meal!","Afiyet olsun!"], ["Let us eat!","Hadi yiyelim!"] ],
         [ ["Can I try yours?","Seninkinden tadabilir miyim?"], ["Yours looks better!","Seninki daha güzel görünüyor!"] ] ] },
  { f=>[ ["So? Do you like it? Be honest.","Ee? Beğendin mi? Dürüst ol."],
         ["Go on then, what is the verdict? And be honest with me.","Hadi bakalım, kararın ne? Bana karşı dürüst ol."] ],
    o=>[ [ ["It is delicious! Thank you.","Çok lezzetli! Teşekkürler."], ["Really good. You were right.","Gerçekten güzel. Haklıymışsın."] ],
         [ ["It is okay, but a bit salty.","İdare eder ama biraz tuzlu."], ["Not bad, but too much oil.","Fena değil ama fazla yağlı."] ],
         [ ["I prefer the food in my country.","Ben kendi ülkemin yemeğini tercih ederim."], ["It is different from home food.","Ev yemeğinden farklı."] ] ] },
  { f=>[ ["Dessert? They make good cake here.","Tatlı? Burada güzel kek yaparlar."],
         ["Now the important question: dessert? Their cake is genuinely worth it.","Şimdi asıl soru: tatlı? Kekleri gerçekten değer."] ],
    o=>[ [ ["Yes please! I love cake.","Evet lütfen! Keke bayılırım."], ["Always room for dessert.","Tatlıya hep yer vardır."] ],
         [ ["No thanks, I am full.","Yok sağ ol, doydum."], ["I cannot eat one more bite.","Bir lokma daha yiyemem."] ],
         [ ["Let us share one.","Bir tane paylaşalım."], ["Half for me, half for you.","Yarısı bana, yarısı sana."] ] ] },
  { f=>[ ["Let me pay. You paid last time.","Bırak ben ödeyeyim. Geçen sefer sen ödedin."],
         ["Put your wallet away. It is my turn, you paid last time.","Cüzdanını kaldır. Sıra bende, geçen sefer sen ödedin."] ],
    o=>[ [ ["Thank you! Next time is on me.","Teşekkürler! Bir dahaki sefer benden."], ["Okay, but I pay next time.","Tamam ama sonraki sefer ben ödüyorum."] ],
         [ ["No, let us share the bill.","Hayır, hesabı paylaşalım."], ["Half and half is fair.","Yarı yarıya adil olur."] ],
         [ ["Are you sure?","Emin misin?"], ["That is very kind of you.","Çok naziksin."] ] ] },
  { f=>[ ["That was a good evening. {phrase}","Güzel bir akşamdı. {phrase}"],
         ["I really enjoyed tonight. We should do this more often. {phrase}","Bu akşamdan çok keyif aldım. Bunu daha sık yapmalıyız. {phrase}"] ],
    o=>[ [ ["Yes, thank you for tonight.","Evet, bu akşam için teşekkürler."], ["I had a great time.","Çok güzel vakit geçirdim."] ],
         [ ["Let us do it again soon.","Yakında tekrar yapalım."], ["Same place next month?","Gelecek ay aynı yer?"] ],
         [ ["Get home safe.","Sağ salim git."], ["Good night, {name}.","İyi geceler {name}."] ] ] }
 ]
},
{
 id=>"homemovie", title=>"Evde film gecesi", emoji=>"🎬", cat=>"Ev ve Günlük Hayat",
 intro=>"{name} ile evde film izliyorsunuz.",
 beats=>[
  { f=>[ ["Welcome! Come in, sit on the sofa.","Hoş geldin! Gel, kanepeye otur."],
         ["Come in, come in. Make yourself at home, the sofa is the comfortable one.","Gel gel. Evin gibi rahat ol, rahat olan kanepe bu."] ],
    o=>[ [ ["Thank you. Nice flat!","Teşekkürler. Güzel evmiş!"], ["Your home is lovely.","Evin çok hoş."] ],
         [ ["I brought some snacks.","Biraz atıştırmalık getirdim."], ["I brought chocolate for us.","Bize çikolata getirdim."] ],
         [ ["Should I take off my shoes?","Ayakkabılarımı çıkarayım mı?"], ["Where can I put my coat?","Montumu nereye koyabilirim?"] ] ] },
  { f=>[ ["What do you want to watch tonight?","Bu akşam ne izlemek istersin?"],
         ["Right, the big decision of the evening: what are we watching?","Tamam, akşamın büyük kararı: ne izliyoruz?"] ],
    o=>[ [ ["You choose, I do not mind.","Sen seç, benim için fark etmez."], ["Anything is fine with me.","Bana her şey uyar."] ],
         [ ["Something funny, please.","Komik bir şey lütfen."], ["I want to laugh tonight.","Bu akşam gülmek istiyorum."] ],
         [ ["Do you have any action films?","Aksiyon filmin var mı?"], ["Something exciting, please.","Heyecanlı bir şey lütfen."] ] ] },
  { f=>[ ["My favourite film is {film}. Have you seen it?","En sevdiğim film {film}. İzledin mi?"],
         ["I could watch {film} a hundred times. Have you seen it, or shall we?","{film} filmini yüz kere izleyebilirim. İzledin mi, yoksa izleyelim mi?"] ],
    o=>[ [ ["No, never. Let us watch it!","Hayır, hiç. Hadi onu izleyelim!"], ["I have not seen it. Is it good?","İzlemedim. Güzel mi?"] ],
         [ ["Yes, I love that film!","Evet, o filme bayılırım!"], ["I have seen it three times.","Üç kez izledim."] ],
         [ ["Is it long? I am tired.","Uzun mu? Yorgunum."], ["Is it in English? I need subtitles.","İngilizce mi? Altyazı lazım bana."] ] ] },
  { f=>[ ["I also watch {series}. Do you know it?","{series} dizisini de izliyorum. Biliyor musun?"],
         ["I am completely hooked on {series} at the moment. Do you watch it?","Şu an tamamen {series} dizisine takıldım. İzliyor musun?"] ],
    o=>[ [ ["I know it but I have not watched it.","Biliyorum ama izlemedim."], ["I have heard of it.","Adını duydum."] ],
         [ ["Yes! Which season are you on?","Evet! Hangi sezondasın?"], ["I love that show!","O diziye bayılıyorum!"] ],
         [ ["I do not watch series much.","Pek dizi izlemem."], ["I prefer films.","Ben filmleri tercih ederim."] ] ] },
  { f=>[ ["Popcorn? I always eat popcorn with films.","Patlamış mısır? Filmle hep patlamış mısır yerim."],
         ["I will make popcorn. A film without popcorn is not a real film.","Patlamış mısır yapayım. Mısırsız film, film değildir."] ],
    o=>[ [ ["Yes please, with salt.","Evet lütfen, tuzlu olsun."], ["Popcorn sounds perfect.","Patlamış mısır mükemmel olur."] ],
         [ ["No thanks, I just ate.","Yok sağ ol, daha yeni yedim."], ["Maybe later.","Belki sonra."] ],
         [ ["Do you have anything sweet?","Tatlı bir şeyin var mı?"], ["Can I have some water too?","Biraz da su alabilir miyim?"] ] ] },
  { f=>[ ["Wait, this part is the best. Watch!","Dur, en güzel yeri burası. İzle!"],
         ["Shh, shh, this scene coming up is the whole reason I love this.","Şşş, şşş, gelen sahne bunu sevmemin bütün sebebi."] ],
    o=>[ [ ["Okay, I am watching!","Tamam, izliyorum!"], ["Do not tell me what happens!","Ne olacağını söyleme!"] ],
         [ ["I do not understand this part.","Bu kısmı anlamadım."], ["Can you explain that?","Şunu açıklayabilir misin?"] ],
         [ ["Wow, that was good!","Vay, bu iyiydi!"], ["That surprised me!","Beni şaşırttı!"] ] ] },
  { f=>[ ["Do you watch films in English?","Filmleri İngilizce izliyor musun?"],
         ["Do you watch things in English? It helped my friends a lot with the language.","İngilizce izliyor musun? Arkadaşlarıma dil konusunda çok yardımı olmuştu."] ],
    o=>[ [ ["Yes, with subtitles.","Evet, altyazıyla."], ["I try, but it is fast.","Deniyorum ama hızlı konuşuyorlar."] ],
         [ ["No, I watch with dubbing.","Hayır, dublajlı izliyorum."], ["Only in my language.","Sadece kendi dilimde."] ],
         [ ["I understand about half.","Yaklaşık yarısını anlıyorum."], ["I understand more every month.","Her ay biraz daha anlıyorum."] ] ] },
  { f=>[ ["That is good practice. Your English is getting better.","Bu iyi bir pratik. İngilizcen gelişiyor."],
         ["Honestly, that is the best practice there is. Your English has improved a lot.","Cidden, en iyi pratik bu. İngilizcen çok gelişmiş."] ],
    o=>[ [ ["Thank you! I practise every day.","Teşekkürler! Her gün pratik yapıyorum."], ["That is nice to hear.","Bunu duymak güzel."] ],
         [ ["I still make many mistakes.","Hâlâ çok hata yapıyorum."], ["Speaking is hard for me.","Konuşmak benim için zor."] ],
         [ ["Talking with you helps a lot.","Seninle konuşmak çok yardımcı oluyor."], ["You speak slowly, thank you.","Yavaş konuşuyorsun, teşekkürler."] ] ] },
  { f=>[ ["The film finished. Did you like it?","Film bitti. Beğendin mi?"],
         ["And that is the end. So, what did you think of it?","Ve bitti. Ee, nasıl buldun?"] ],
    o=>[ [ ["I loved it!","Bayıldım!"], ["That was really good.","Gerçekten güzeldi."] ],
         [ ["It was a bit slow for me.","Bana biraz yavaş geldi."], ["The ending was strange.","Sonu tuhaftı."] ],
         [ ["I fell asleep in the middle!","Ortasında uyuyakaldım!"], ["Sorry, I missed some parts.","Pardon, bazı kısımları kaçırdım."] ] ] },
  { f=>[ ["It is late. Do you want to stay or go home?","Geç oldu. Kalmak mı istersin, eve gitmek mi?"],
         ["Look at the time. You are welcome to stay, or I can call you a taxi.","Saate bak. İstersen kal, ya da sana taksi çağırayım."] ],
    o=>[ [ ["I should go home. Thank you!","Eve gitmeliyim. Teşekkürler!"], ["I will go, it is late.","Gideyim, geç oldu."] ],
         [ ["Can you call me a taxi?","Bana taksi çağırabilir misin?"], ["How do I get home from here?","Buradan eve nasıl giderim?"] ],
         [ ["Thanks for the film night.","Film gecesi için teşekkürler."], ["Let us do this again!","Bunu tekrar yapalım!"] ] ] }
 ]
},
{
 id=>"holidayplan", title=>"Tatil planı yapmak", emoji=>"🗺️", cat=>"Tatil ve Seyahat",
 intro=>"{name} ile birlikte tatil planı yapıyorsunuz.",
 beats=>[
  { f=>[ ["I need a holiday! Do you want to travel together?","Tatile ihtiyacım var! Birlikte seyahat etmek ister misin?"],
         ["I desperately need a break. How would you feel about travelling together?","Şiddetle bir molaya ihtiyacım var. Birlikte seyahat etmeye ne dersin?"] ],
    o=>[ [ ["Yes! Great idea.","Evet! Harika fikir."], ["I would love to travel with you.","Seninle seyahat etmek isterim."] ],
         [ ["Maybe. Where do you want to go?","Belki. Nereye gitmek istersin?"], ["Depends where. Tell me more.","Nereye olduğuna bağlı. Anlat biraz."] ],
         [ ["I do not have much money.","Pek param yok."], ["Travel is expensive for me.","Seyahat benim için pahalı."] ] ] },
  { f=>[ ["I really want to go to {place}. It is my dream.","Gerçekten {place} gitmek istiyorum. Hayalim."],
         ["The place at the top of my list is {place}. I have wanted to go for years.","Listemin başındaki yer {place}. Yıllardır gitmek istiyorum."] ],
    o=>[ [ ["Why {place}?","Neden {place}?"], ["What is special about it?","Özel olan nesi var?"] ],
         [ ["That sounds amazing!","Kulağa harika geliyor!"], ["I want to go there too!","Ben de oraya gitmek istiyorum!"] ],
         [ ["Is it far from here?","Buradan uzak mı?"], ["How long is the flight?","Uçuş ne kadar sürüyor?"] ] ] },
  { f=>[ ["Last year I went to {lastHol}. It was beautiful.","Geçen yıl {lastHol} gittim. Çok güzeldi."],
         ["My last proper trip was {lastHol} and honestly it was one of the best.","Son doğru düzgün seyahatim {lastHol} idi ve cidden en iyilerindendi."] ],
    o=>[ [ ["Who did you go with?","Kiminle gittin?"], ["Did you go alone?","Yalnız mı gittin?"] ],
         [ ["What did you do there?","Orada ne yaptın?"], ["What was the best part?","En güzel yanı neydi?"] ],
         [ ["I have never been there.","Ben hiç gitmedim."], ["I would like to see photos.","Fotoğrafları görmek isterim."] ] ] },
  { f=>[ ["When can you travel? I am free in summer.","Ne zaman seyahat edebilirsin? Ben yazın müsaitim."],
         ["The main question is timing. My schedule is clearest in the summer.","Asıl soru zamanlama. Programım en çok yazın müsait."] ],
    o=>[ [ ["Summer is good for me too.","Yaz bana da uyar."], ["July or August, maybe.","Belki temmuz ya da ağustos."] ],
         [ ["I can only travel in winter.","Sadece kışın seyahat edebilirim."], ["Autumn is better for me.","Sonbahar benim için daha iyi."] ],
         [ ["I do not know yet.","Henüz bilmiyorum."], ["I need to check with work.","İşle konuşmam lazım."] ] ] },
  { f=>[ ["How many days? One week or two?","Kaç gün? Bir hafta mı iki mi?"],
         ["How long should we go for, realistically? A week feels short to me.","Gerçekçi olarak ne kadar gitmeliyiz? Bir hafta bana kısa geliyor."] ],
    o=>[ [ ["One week is enough.","Bir hafta yeter."], ["Seven days, I think.","Bence yedi gün."] ],
         [ ["Two weeks would be perfect.","İki hafta mükemmel olur."], ["The longer the better!","Ne kadar uzun o kadar iyi!"] ],
         [ ["Just a long weekend for me.","Bana uzun bir hafta sonu yeter."], ["I only have four days.","Sadece dört günüm var."] ] ] },
  { f=>[ ["Hotel or a small flat? What do you prefer?","Otel mi küçük bir daire mi? Sen neyi tercih edersin?"],
         ["Where should we stay? Personally I prefer a small flat to a big hotel.","Nerede kalalım? Şahsen büyük otel yerine küçük bir daireyi tercih ederim."] ],
    o=>[ [ ["A hotel is easier.","Otel daha kolay."], ["I like hotels with breakfast.","Kahvaltılı otelleri severim."] ],
         [ ["A flat is cheaper.","Daire daha ucuz."], ["I prefer a flat with a kitchen.","Mutfaklı bir daireyi tercih ederim."] ],
         [ ["What about a hostel?","Hostele ne dersin?"], ["Something cheap is fine.","Ucuz bir şey olsa yeter."] ] ] },
  { f=>[ ["I use {transport} here, but we will need a plane.","Burada {transport} kullanırım ama uçak gerekecek."],
         ["Around here I just use {transport}, but this time we definitely need to fly.","Burada sadece {transport} kullanırım ama bu gezi için kesin uçmamız gerek."] ],
    o=>[ [ ["I am scared of flying.","Uçmaktan korkuyorum."], ["I do not like planes.","Uçakları sevmiyorum."] ],
         [ ["Flying is fine for me.","Uçmak benim için sorun değil."], ["I love the airport!","Havaalanına bayılırım!"] ],
         [ ["Can we go by train?","Trenle gidebilir miyiz?"], ["A road trip could be fun.","Karayolu gezisi eğlenceli olabilir."] ] ] },
  { f=>[ ["What do you like on holiday? Beach or city?","Tatilde neyi seversin? Sahil mi şehir mi?"],
         ["What is your holiday style? Lying on a beach, or exploring a city all day?","Tatil tarzın nedir? Sahilde yatmak mı, bütün gün şehir gezmek mi?"] ],
    o=>[ [ ["Beach! I want to relax.","Sahil! Dinlenmek istiyorum."], ["Sun, sea and nothing else.","Güneş, deniz ve başka hiçbir şey."] ],
         [ ["City. I like museums.","Şehir. Müzeleri severim."], ["I want to walk and see everything.","Yürüyüp her şeyi görmek isterim."] ],
         [ ["Mountains and nature for me.","Bana dağlar ve doğa."], ["I like quiet places.","Sessiz yerleri severim."] ] ] },
  { f=>[ ["Okay! I will look at prices tonight.","Tamam! Bu akşam fiyatlara bakarım."],
         ["Perfect. Leave it with me, I will look at flights and prices tonight.","Mükemmel. Bana bırak, bu akşam uçuşlara ve fiyatlara bakarım."] ],
    o=>[ [ ["Great, send me the links.","Harika, bana linkleri gönder."], ["Tell me what you find.","Ne bulursan söyle."] ],
         [ ["I will look too.","Ben de bakarım."], ["Let us both search.","İkimiz de arayalım."] ],
         [ ["Do not book anything yet!","Henüz hiçbir şey ayırtma!"], ["Let me check my money first.","Önce paraya bir bakayım."] ] ] },
  { f=>[ ["This is exciting! {phrase}","Bu çok heyecan verici! {phrase}"],
         ["I am genuinely excited now. This is going to be a good one. {phrase}","Şimdi cidden heyecanlandım. Bu güzel olacak. {phrase}"] ],
    o=>[ [ ["Me too! I cannot wait.","Ben de! Sabırsızlanıyorum."], ["I am so excited!","Çok heyecanlıyım!"] ],
         [ ["Let us talk again tomorrow.","Yarın tekrar konuşalım."], ["Message me tonight.","Bu akşam mesaj at."] ],
         [ ["Thank you for planning this.","Bunu planladığın için teşekkürler."], ["You are a good friend, {name}.","İyi bir arkadaşsın {name}."] ] ] }
 ]
}
]
