use utf8;
[
{
 id=>"gym", title=>"Spor ve hareket", emoji=>"🏃", cat=>"Sağlık",
 intro=>"{name} ile spor yapmaya karar verdiniz.",
 beats=>[
  { f=>[ ["Are you ready? We start in five minutes.","Hazır mısın? Beş dakika sonra başlıyoruz."],
         ["Right, five minutes and we start. No sitting down, no excuses.","Tamam, beş dakikaya başlıyoruz. Oturmak yok, bahane yok."] ],
    o=>[ [ ["I am ready!","Hazırım!"], ["Let us do this.","Hadi yapalım."] ],
         [ ["I am already tired.","Şimdiden yoruldum."], ["Can we start slowly?","Yavaş başlayabilir miyiz?"] ],
         [ ["What are we doing today?","Bugün ne yapıyoruz?"], ["Is it hard?","Zor mu?"] ] ] },
  { f=>[ ["First we walk, then we run a little.","Önce yürüyeceğiz, sonra biraz koşacağız."],
         ["We warm up with a walk, then a gentle run. Nothing dramatic.","Yürüyüşle ısınırız, sonra hafif bir koşu. Abartı yok."] ],
    o=>[ [ ["That sounds okay.","Bu iyi görünüyor."], ["I can do that.","Bunu yapabilirim."] ],
         [ ["How long do we run?","Ne kadar koşacağız?"], ["How many kilometres?","Kaç kilometre?"] ],
         [ ["I cannot run at all.","Hiç koşamıyorum."], ["My knees hurt.","Dizlerim ağrıyor."] ] ] },
  { f=>[ ["Do not worry. Everyone starts somewhere.","Merak etme. Herkes bir yerden başlar."],
         ["Nobody starts fast. I could not run for two minutes when I began.","Kimse hızlı başlamaz. Ben başladığımda iki dakika koşamıyordum."] ],
    o=>[ [ ["Really? You?","Gerçekten mi? Sen mi?"], ["I do not believe you!","Sana inanmıyorum!"] ],
         [ ["That makes me feel better.","Bu beni rahatlattı."], ["Thank you for saying that.","Bunu söylediğin için sağ ol."] ],
         [ ["How long did it take you?","Senin ne kadar sürdü?"], ["When did you start?","Ne zaman başladın?"] ] ] },
  { f=>[ ["I go three times a week. It is a habit now.","Haftada üç kez gidiyorum. Artık alışkanlık."],
         ["Three times a week, every week. After a year it stopped being a decision.","Haftada üç kez, her hafta. Bir yıl sonra karar olmaktan çıktı."] ],
    o=>[ [ ["Three times is a lot!","Üç kez çok!"], ["I could do once a week.","Ben haftada bir yapabilirim."] ],
         [ ["Which days do you go?","Hangi günler gidiyorsun?"], ["Morning or evening?","Sabah mı akşam mı?"] ],
         [ ["Can I come with you?","Seninle gelebilir miyim?"], ["Take me next time.","Bir dahaki sefere beni de götür."] ] ] },
  { f=>[ ["Breathe! Do not hold your breath.","Nefes al! Nefesini tutma."],
         ["Breathe properly. Most people forget to breathe and then wonder why they stop.","Düzgün nefes al. Çoğu insan nefes almayı unutuyor, sonra neden durduklarına şaşırıyor."] ],
    o=>[ [ ["Okay, I am breathing!","Tamam, nefes alıyorum!"], ["Like this?","Böyle mi?"] ],
         [ ["I cannot breathe!","Nefes alamıyorum!"], ["I need a break.","Molaya ihtiyacım var."] ],
         [ ["This is harder than I thought.","Bu düşündüğümden zor."], ["How do you do this?","Bunu nasıl yapıyorsun?"] ] ] },
  { f=>[ ["Take a minute. Drink some water.","Bir dakika mola. Biraz su iç."],
         ["Take a minute, get your breath back and drink. There is no prize for suffering.","Bir dakika mola ver, nefesini topla ve su iç. Acı çekmenin ödülü yok."] ],
    o=>[ [ ["Thank you. I need it.","Teşekkürler. İhtiyacım vardı."], ["One minute is enough.","Bir dakika yeter."] ],
         [ ["I forgot my water!","Suyumu unuttum!"], ["Can I have some of yours?","Seninkinden alabilir miyim?"] ],
         [ ["I am okay, let us continue.","İyiyim, devam edelim."], ["No, I can keep going.","Hayır, devam edebilirim."] ] ] },
  { f=>[ ["What do you eat before sport?","Spordan önce ne yiyorsun?"],
         ["What is your pre workout food? Most people get this completely wrong.","Spor öncesi ne yiyorsun? Çoğu insan bunu tamamen yanlış yapıyor."] ],
    o=>[ [ ["Nothing, usually.","Genelde hiçbir şey."], ["I do not eat before.","Öncesinde yemem."] ],
         [ ["A banana, maybe.","Belki bir muz."], ["Something light.","Hafif bir şey."] ],
         [ ["What should I eat?","Ne yemeliyim?"], ["What do you eat?","Sen ne yiyorsun?"] ] ] },
  { f=>[ ["I have {breakfast}, then I train.","{breakfast} yerim, sonra antrenman yaparım."],
         ["My routine is simple: {breakfast}, wait an hour, then train.","Rutinim basit: {breakfast}, bir saat bekle, sonra antrenman."] ],
    o=>[ [ ["I will try that.","Bunu deneyeceğim."], ["That sounds sensible.","Mantıklı görünüyor."] ],
         [ ["Do you take protein?","Protein alıyor musun?"], ["Any supplements?","Takviye kullanıyor musun?"] ],
         [ ["I eat too much sugar.","Çok fazla şeker yiyorum."], ["I love chocolate too much.","Çikolatayı fazla seviyorum."] ] ] },
  { f=>[ ["Sugar is fine sometimes. Balance is the key.","Şeker bazen sorun değil. Anahtar denge."],
         ["A little sugar will not kill you. It is the everyday habits that matter.","Biraz şeker seni öldürmez. Asıl önemli olan günlük alışkanlıklar."] ],
    o=>[ [ ["I like that idea.","Bu fikri sevdim."], ["Balance, okay.","Denge, tamam."] ],
         [ ["I have no balance at all!","Bende hiç denge yok!"], ["All or nothing with me.","Bende ya hep ya hiç."] ],
         [ ["Give me one small rule.","Bana küçük bir kural ver."], ["What is your best tip?","En iyi tavsiyen ne?"] ] ] },
  { f=>[ ["Same time on Thursday? {phrase}","Perşembe aynı saatte? {phrase}"],
         ["Thursday, same time. You did well today, do not stop now. {phrase}","Perşembe, aynı saatte. Bugün iyiydin, şimdi bırakma. {phrase}"] ],
    o=>[ [ ["Yes, Thursday!","Evet, perşembe!"], ["I will be here.","Burada olacağım."] ],
         [ ["My legs will hurt tomorrow.","Yarın bacaklarım ağrıyacak."], ["I will not be able to walk!","Yürüyemeyeceğim!"] ],
         [ ["Thank you for helping me.","Bana yardım ettiğin için sağ ol."], ["You are a good trainer!","İyi bir antrenörsün!"] ] ] }
 ]
},
{
 id=>"phonecall", title=>"Telefonda hızlı sohbet", emoji=>"📱", cat=>"Günlük Hayat",
 intro=>"{name} seni aradı.",
 beats=>[
  { f=>[ ["Hi! Can you talk now?","Selam! Şimdi konuşabilir misin?"],
         ["Hey, is now a bad time? I can call back later if you are busy.","Selam, kötü bir zaman mı? Meşgulsen sonra ararım."] ],
    o=>[ [ ["Yes, I can talk.","Evet, konuşabilirim."], ["Sure, what is up?","Tabii, ne oldu?"] ],
         [ ["I have five minutes.","Beş dakikam var."], ["Be quick, I am at work.","Çabuk ol, işteyim."] ],
         [ ["Can you call me later?","Beni sonra arayabilir misin?"], ["I am busy right now.","Şu an meşgulüm."] ] ] },
  { f=>[ ["I just wanted to hear your voice.","Sadece sesini duymak istedim."],
         ["No reason really, I just wanted to hear your voice. Is that strange?","Aslında bir sebebi yok, sadece sesini duymak istedim. Tuhaf mı?"] ],
    o=>[ [ ["That is so nice!","Bu çok tatlı!"], ["I missed you too.","Ben de seni özledim."] ],
         [ ["Is everything okay?","Her şey yolunda mı?"], ["Are you sure nothing is wrong?","Bir şey olmadığına emin misin?"] ],
         [ ["You made my day.","Günümü güzelleştirdin."], ["Thanks for calling.","Aradığın için sağ ol."] ] ] },
  { f=>[ ["The line is bad. Can you hear me?","Hat kötü. Beni duyabiliyor musun?"],
         ["You are breaking up a bit. Can you hear me now, or shall I move?","Ses kesiliyor biraz. Şimdi duyabiliyor musun, yoksa yer mi değiştireyim?"] ],
    o=>[ [ ["Now I can hear you.","Şimdi duyabiliyorum."], ["That is better.","Şimdi daha iyi."] ],
         [ ["Sorry, say that again?","Pardon, tekrar söyler misin?"], ["I did not hear you.","Seni duyamadım."] ],
         [ ["Speak a bit louder.","Biraz daha yüksek sesle konuş."], ["Speak slowly, please.","Yavaş konuş lütfen."] ] ] },
  { f=>[ ["Sorry, my English is fast on the phone.","Pardon, telefonda İngilizcem hızlı oluyor."],
         ["Sorry, I know I speak quickly on the phone. Stop me if I go too fast.","Pardon, telefonda hızlı konuştuğumu biliyorum. Çok hızlanırsam durdur."] ],
    o=>[ [ ["Phone calls are hard for me.","Telefon görüşmeleri bana zor geliyor."], ["I understand better face to face.","Yüz yüze daha iyi anlıyorum."] ],
         [ ["It is fine, keep going.","Sorun değil, devam et."], ["I understand most of it.","Çoğunu anlıyorum."] ],
         [ ["Can you repeat the last part?","Son kısmı tekrarlar mısın?"], ["What does that word mean?","O kelime ne demek?"] ] ] },
  { f=>[ ["Anyway, what are you doing tonight?","Neyse, bu akşam ne yapıyorsun?"],
         ["Anyway, the real reason I rang: what are you doing tonight?","Neyse, asıl arama sebebim: bu akşam ne yapıyorsun?"] ],
    o=>[ [ ["Nothing much.","Pek bir şey yok."], ["Just staying home.","Sadece evde kalacağım."] ],
         [ ["I am seeing friends.","Arkadaşlarla buluşacağım."], ["I have plans, sorry.","Planım var, kusura bakma."] ],
         [ ["Why? What is happening?","Neden? Ne var?"], ["Do you have an idea?","Bir fikrin mi var?"] ] ] },
  { f=>[ ["Come to mine. We can watch {series}.","Bize gel. {series} izleyebiliriz."],
         ["Come round to mine. We can put {series} on and order some food.","Bize gel. {series} açarız, bir şeyler de söyleriz."] ],
    o=>[ [ ["Great, what time?","Harika, saat kaçta?"], ["I will come after eight.","Sekizden sonra gelirim."] ],
         [ ["I am too tired tonight.","Bu akşam çok yorgunum."], ["Maybe tomorrow instead?","Belki onun yerine yarın?"] ],
         [ ["Shall I bring anything?","Bir şey getireyim mi?"], ["Do you want me to bring food?","Yemek getirmemi ister misin?"] ] ] },
  { f=>[ ["Just bring yourself. And maybe chocolate.","Sadece kendini getir. Belki bir de çikolata."],
         ["Bring nothing. Well, chocolate would not be refused, obviously.","Hiçbir şey getirme. Yani çikolata reddedilmez tabii."] ],
    o=>[ [ ["Chocolate it is!","Çikolata olsun!"], ["I know what you like.","Ne sevdiğini biliyorum."] ],
         [ ["I will bring drinks too.","İçecek de getiririm."], ["I will bring dessert.","Tatlı getiririm."] ],
         [ ["You always want chocolate!","Hep çikolata istiyorsun!"], ["Typical you.","Tam sana göre."] ] ] },
  { f=>[ ["Oh, someone is at the door. One second.","Kapıda biri var. Bir saniye."],
         ["Hold on, there is someone at the door. Give me two seconds.","Bekle, kapıda biri var. Bana iki saniye ver."] ],
    o=>[ [ ["Okay, I will wait.","Tamam, beklerim."], ["Take your time.","Acele etme."] ],
         [ ["Who is it?","Kim o?"], ["Are you expecting someone?","Birini mi bekliyordun?"] ],
         [ ["Call me back later.","Sonra beni ara."], ["Go, I will hang up.","Git, ben kapatıyorum."] ] ] },
  { f=>[ ["Sorry! It was the postman. Where were we?","Pardon! Postacıymış. Nerede kalmıştık?"],
         ["Sorry about that, just a delivery. Right, where were we?","Kusura bakma, kargoymuş. Tamam, nerede kalmıştık?"] ],
    o=>[ [ ["Tonight, at your place.","Bu akşam, sende."], ["We said eight o'clock.","Sekiz demiştik."] ],
         [ ["A parcel? What did you buy?","Kargo mu? Ne aldın?"], ["Something nice?","Güzel bir şey mi?"] ],
         [ ["I forgot too!","Ben de unuttum!"], ["We were talking about chocolate.","Çikolatadan bahsediyorduk."] ] ] },
  { f=>[ ["Okay, see you tonight. Bye! {phrase}","Tamam, akşam görüşürüz. Hoşça kal! {phrase}"],
         ["Right, I will let you go. See you at eight, do not be late. {phrase}","Tamam, seni bırakayım. Sekizde görüşürüz, geç kalma. {phrase}"] ],
    o=>[ [ ["See you later!","Sonra görüşürüz!"], ["Bye, {name}!","Hoşça kal {name}!"] ],
         [ ["Send me your address.","Adresini gönder."], ["Text me the details.","Detayları yaz."] ],
         [ ["Thanks for calling!","Aradığın için teşekkürler!"], ["Talk soon.","Yakında konuşuruz."] ] ] }
 ]
},
{
 id=>"home", title=>"Ev işleri ve komşular", emoji=>"🏠", cat=>"Ev ve Günlük Hayat",
 intro=>"{name} evinde, ev işleriyle uğraşıyor.",
 beats=>[
  { f=>[ ["Sorry, the house is a mess today!","Kusura bakma, ev bugün dağınık!"],
         ["Excuse the mess. I have been meaning to tidy up for about three weeks.","Dağınıklığa bakma. Üç haftadır toplayacağım diyorum."] ],
    o=>[ [ ["It looks fine to me!","Bana gayet iyi görünüyor!"], ["Do not worry about it.","Boş ver."] ],
         [ ["My house is worse.","Benim evim daha kötü."], ["You should see mine!","Bir de benimkini gör!"] ],
         [ ["Can I help you tidy?","Toplamana yardım edeyim mi?"], ["Give me a job to do.","Bana bir iş ver."] ] ] },
  { f=>[ ["I hate cleaning. Especially the kitchen.","Temizlikten nefret ediyorum. Özellikle mutfaktan."],
         ["Cleaning is my least favourite thing on earth, especially the kitchen.","Temizlik dünyada en sevmediğim şey, özellikle de mutfak."] ],
    o=>[ [ ["Me too. It never ends.","Ben de. Hiç bitmiyor."], ["Same, I hate it.","Aynı, nefret ederim."] ],
         [ ["I like cleaning, actually.","Aslında temizliği severim."], ["It relaxes me.","Beni rahatlatıyor."] ],
         [ ["Put music on. It helps!","Müzik aç. Yardımcı oluyor!"], ["Do it with a podcast.","Podcast dinleyerek yap."] ] ] },
  { f=>[ ["Good idea. I will put {music} on.","İyi fikir. {music} açayım."],
         ["That is a good idea, actually. {music} makes everything faster.","Aslında iyi fikir. {music} her şeyi hızlandırıyor."] ],
    o=>[ [ ["I like that music.","O müziği severim."], ["Turn it up!","Sesi aç!"] ],
         [ ["I do not know it.","Onu bilmiyorum."], ["Is it new?","Yeni mi?"] ],
         [ ["Then let us start!","O zaman başlayalım!"], ["I will do the dishes.","Ben bulaşıkları yaparım."] ] ] },
  { f=>[ ["Careful, {pet} is behind you!","Dikkat et, {pet} arkanda!"],
         ["Watch your feet, {pet} follows me around the whole house.","Ayağına dikkat, {pet} beni bütün evde takip ediyor."] ],
    o=>[ [ ["So cute!","Çok tatlı!"], ["Can I say hello?","Selam verebilir miyim?"] ],
         [ ["I love animals.","Hayvanları severim."], ["I have one at home too.","Benim de evde bir tane var."] ],
         [ ["I am a bit scared of animals.","Hayvanlardan biraz korkuyorum."], ["Is it friendly?","Uysal mı?"] ] ] },
  { f=>[ ["My neighbour is very noisy at night.","Komşum geceleri çok gürültücü."],
         ["The neighbour upstairs plays music until two in the morning. Every weekend.","Üst kattaki komşu sabahın ikisine kadar müzik açıyor. Her hafta sonu."] ],
    o=>[ [ ["Did you talk to them?","Onlarla konuştun mu?"], ["Have you said anything?","Bir şey söyledin mi?"] ],
         [ ["That is annoying!","Bu çok can sıkıcı!"], ["I could not live with that.","Ben buna dayanamazdım."] ],
         [ ["My neighbours are quiet.","Benim komşularım sessiz."], ["I am lucky with mine.","Ben komşu konusunda şanslıyım."] ] ] },
  { f=>[ ["I do not want problems, so I say nothing.","Sorun istemiyorum, o yüzden bir şey söylemiyorum."],
         ["I keep quiet because I do not want a war with someone I live next to.","Sessiz kalıyorum çünkü yan kapıdaki biriyle savaş istemiyorum."] ],
    o=>[ [ ["I understand you.","Seni anlıyorum."], ["That is difficult.","Zor bir durum."] ],
         [ ["You should say something nicely.","Kibarca bir şey söylemelisin."], ["Talk to them politely.","Onlarla nazikçe konuş."] ],
         [ ["Buy some earplugs!","Kulak tıkacı al!"], ["Play your music louder!","Sen müziğini daha çok aç!"] ] ] },
  { f=>[ ["Do you live alone or with people?","Yalnız mı yaşıyorsun yoksa birileriyle mi?"],
         ["Do you live on your own, or do you share with someone?","Tek başına mı yaşıyorsun, yoksa biriyle mi paylaşıyorsun?"] ],
    o=>[ [ ["I live alone.","Yalnız yaşıyorum."], ["Just me and my things.","Sadece ben ve eşyalarım."] ],
         [ ["I live with my family.","Ailemle yaşıyorum."], ["With my parents, still.","Hâlâ anne babamla."] ],
         [ ["I share a flat.","Ev paylaşıyorum."], ["I have a flatmate.","Ev arkadaşım var."] ] ] },
  { f=>[ ["I live with {family}. It is never quiet!","{family} ile yaşıyorum. Hiç sessiz olmuyor!"],
         ["I share the place with {family}, so silence is not really an option here.","Burayı {family} ile paylaşıyorum, yani sessizlik pek mümkün değil."] ],
    o=>[ [ ["That sounds nice.","Kulağa güzel geliyor."], ["I like a full house.","Kalabalık evi severim."] ],
         [ ["Do you argue sometimes?","Bazen tartışıyor musunuz?"], ["Is it difficult?","Zor mu?"] ],
         [ ["I need silence to sleep.","Uyumak için sessizlik lazım bana."], ["I could not do that.","Ben bunu yapamazdım."] ] ] },
  { f=>[ ["Okay, the kitchen is clean. Tea?","Tamam, mutfak temiz. Çay?"],
         ["There, kitchen done. I think we have earned a cup of tea.","İşte, mutfak tamam. Bence bir çayı hak ettik."] ],
    o=>[ [ ["Yes please!","Evet lütfen!"], ["I would love a tea.","Bir çay çok iyi olur."] ],
         [ ["Coffee for me, please.","Bana kahve lütfen."], ["Do you have coffee?","Kahven var mı?"] ],
         [ ["Just water, thanks.","Sadece su, sağ ol."], ["Nothing for me, thanks.","Bana bir şey istemem, sağ ol."] ] ] },
  { f=>[ ["Thanks for helping. You are a real friend. {phrase}","Yardım ettiğin için sağ ol. Gerçek bir arkadaşsın. {phrase}"],
         ["Honestly, thank you for helping. That would have taken me all day alone. {phrase}","Cidden yardımın için sağ ol. Tek başıma bütün günümü alırdı. {phrase}"] ],
    o=>[ [ ["Any time!","Ne zaman istersen!"], ["It was nothing.","Bir şey değil."] ],
         [ ["Now you help me next week!","Şimdi haftaya sen bana yardım et!"], ["Your turn next time.","Sıra sende bir dahakine."] ],
         [ ["I enjoyed it, honestly.","Açıkçası keyif aldım."], ["Cleaning with music is fine!","Müzikle temizlik iyiymiş!"] ] ] }
 ]
},
{
 id=>"musicnight", title=>"Müzik ve konser", emoji=>"🎵", cat=>"Eğlence",
 intro=>"{name} müzikten ve bir konserden bahsediyor.",
 beats=>[
  { f=>[ ["I have two tickets for a concert. Interested?","Bir konser için iki biletim var. İlgilenir misin?"],
         ["A friend cancelled, so I have a spare concert ticket. Do you fancy it?","Bir arkadaş iptal etti, elimde fazladan konser bileti var. İster misin?"] ],
    o=>[ [ ["Yes! Who is playing?","Evet! Kim çalıyor?"], ["Definitely! When is it?","Kesinlikle! Ne zaman?"] ],
         [ ["Maybe. What kind of music?","Belki. Ne tür müzik?"], ["Tell me more first.","Önce biraz anlat."] ],
         [ ["I do not like crowds.","Kalabalığı sevmiyorum."], ["Concerts are too loud for me.","Konserler bana çok gürültülü geliyor."] ] ] },
  { f=>[ ["It is {music}. That is my favourite.","{music} çalıyorlar. Benim favorim."],
         ["It is a {music} night. That is the sound I grew up with.","{music} gecesi. Bu benim büyürken dinlediğim müzik."] ],
    o=>[ [ ["I like that too!","Ben de severim!"], ["Good music!","Güzel müzik!"] ],
         [ ["I have never heard it live.","Canlı hiç dinlemedim."], ["Is it good live?","Canlı güzel mi?"] ],
         [ ["I prefer other music.","Ben başka müzikleri tercih ederim."], ["Not really my thing.","Pek benlik değil."] ] ] },
  { f=>[ ["What music do you listen to?","Sen ne müzik dinliyorsun?"],
         ["What is on your playlist at the moment? I am always looking for new things.","Şu an listende ne var? Hep yeni bir şeyler arıyorum."] ],
    o=>[ [ ["I listen to Turkish pop.","Türk pop müziği dinliyorum."], ["Turkish music, mostly.","Çoğunlukla Türkçe müzik."] ],
         [ ["Rock is my favourite.","Favorim rock."], ["I love old songs.","Eski şarkıları severim."] ],
         [ ["Everything, really.","Aslında her şey."], ["It depends on my mood.","Ruh halime göre değişir."] ] ] },
  { f=>[ ["Send me a song! I want to hear it.","Bana bir şarkı gönder! Dinlemek istiyorum."],
         ["Send me one song from your country. I would genuinely like to hear it.","Bana ülkenden bir şarkı gönder. Cidden dinlemek isterim."] ],
    o=>[ [ ["Okay, I will send one now.","Tamam, şimdi bir tane göndereyim."], ["I know the perfect song.","Mükemmel bir şarkı biliyorum."] ],
         [ ["Do you understand the words?","Sözleri anlıyor musun?"], ["It is in Turkish, is that okay?","Türkçe, olur mu?"] ],
         [ ["What is your favourite song?","Senin en sevdiğin şarkı ne?"], ["Send me one too.","Sen de bana bir tane gönder."] ] ] },
  { f=>[ ["Music is good for learning languages, you know.","Müzik dil öğrenmek için iyidir, biliyor musun?"],
         ["Songs are one of the best ways to learn a language. The words stay in your head.","Şarkılar dil öğrenmenin en iyi yollarından. Kelimeler kafada kalıyor."] ],
    o=>[ [ ["That is true!","Bu doğru!"], ["I learn words from songs.","Şarkılardan kelime öğreniyorum."] ],
         [ ["But they sing so fast!","Ama çok hızlı söylüyorlar!"], ["I cannot understand the words.","Sözleri anlayamıyorum."] ],
         [ ["Which song should I start with?","Hangi şarkıyla başlamalıyım?"], ["Give me an easy one.","Bana kolay bir tane ver."] ] ] },
  { f=>[ ["Read the words while you listen. It really works.","Dinlerken sözleri oku. Cidden işe yarıyor."],
         ["Listen with the lyrics in front of you. After three times you will know it.","Sözler önünde olsun, öyle dinle. Üç kere sonra ezberlersin."] ],
    o=>[ [ ["I will try that today.","Bugün deneyeceğim."], ["Good tip, thank you.","İyi tavsiye, teşekkürler."] ],
         [ ["I already do that.","Zaten öyle yapıyorum."], ["That is how I learn.","Ben böyle öğreniyorum."] ],
         [ ["Where do I find the words?","Sözleri nerede bulurum?"], ["Which app is good?","Hangi uygulama iyi?"] ] ] },
  { f=>[ ["Do you play an instrument?","Bir enstrüman çalıyor musun?"],
         ["Do you play anything yourself? I always wanted to learn properly.","Kendin bir şey çalıyor musun? Hep doğru düzgün öğrenmek istemişimdir."] ],
    o=>[ [ ["No, but I want to learn.","Hayır ama öğrenmek istiyorum."], ["I wish I could.","Keşke çalabilsem."] ],
         [ ["I play a little guitar.","Biraz gitar çalıyorum."], ["I played piano at school.","Okulda piyano çalardım."] ],
         [ ["I only sing in the shower!","Sadece duşta şarkı söylerim!"], ["I have no talent at all.","Hiç yeteneğim yok."] ] ] },
  { f=>[ ["The concert starts at eight. Meet me outside.","Konser sekizde başlıyor. Dışarıda buluşalım."],
         ["Doors open at seven, band at eight. Meet me outside the main entrance.","Kapılar yedide, grup sekizde. Ana girişin önünde buluşalım."] ],
    o=>[ [ ["Okay, see you at seven.","Tamam, yedide görüşürüz."], ["I will be outside.","Dışarıda olacağım."] ],
         [ ["How do I get there?","Oraya nasıl gelirim?"], ["Which station is it near?","Hangi istasyona yakın?"] ],
         [ ["What should I wear?","Ne giymeliyim?"], ["Is it inside or outside?","İçeride mi dışarıda mı?"] ] ] },
  { f=>[ ["That was amazing! My ears are still ringing.","Harikaydı! Kulaklarım hâlâ çınlıyor."],
         ["What a night. My ears are ringing and I have lost my voice completely.","Ne geceydi. Kulaklarım çınlıyor ve sesim tamamen gitti."] ],
    o=>[ [ ["I loved it!","Bayıldım!"], ["Best night in months!","Aylardır en güzel gece!"] ],
         [ ["It was very loud!","Çok gürültülüydü!"], ["I am tired now.","Şimdi yoruldum."] ],
         [ ["Let us go again!","Yine gidelim!"], ["When is the next one?","Bir sonraki ne zaman?"] ] ] },
  { f=>[ ["I am so glad you came. {phrase}","Geldiğine çok sevindim. {phrase}"],
         ["I am really glad you came tonight. It would not have been the same alone. {phrase}","Bu gece geldiğine çok sevindim. Yalnız aynı olmazdı. {phrase}"] ],
    o=>[ [ ["Thank you for the ticket!","Bilet için teşekkürler!"], ["I am glad too.","Ben de sevindim."] ],
         [ ["Next one is on me.","Bir sonraki benden."], ["I will buy the tickets next time.","Sonraki sefer biletleri ben alırım."] ],
         [ ["Get home safe.","Sağ salim git."], ["Good night, {name}!","İyi geceler {name}!"] ] ] }
 ]
},
{
 id=>"booktv", title=>"Kitap ve dizi tavsiyesi", emoji=>"📖", cat=>"Eğlence",
 intro=>"{name} ile kitap ve dizi konuşuyorsunuz.",
 beats=>[
  { f=>[ ["I finished a great book yesterday.","Dün harika bir kitap bitirdim."],
         ["I finished a brilliant book last night and now I do not know what to read.","Dün gece muhteşem bir kitap bitirdim ve şimdi ne okuyacağımı bilmiyorum."] ],
    o=>[ [ ["What was it about?","Neyle ilgiliydi?"], ["Tell me about it.","Anlat bakalım."] ],
         [ ["Do you read a lot?","Çok okur musun?"], ["How many books a year?","Yılda kaç kitap?"] ],
         [ ["I do not read much.","Pek okumam."], ["I have no time to read.","Okumaya vaktim yok."] ] ] },
  { f=>[ ["I read every night before sleeping.","Her gece uyumadan önce okurum."],
         ["Twenty minutes before bed, every night. It is the only quiet time I get.","Her gece yatmadan yirmi dakika. Tek sessiz vaktim o."] ],
    o=>[ [ ["That is a nice habit.","Güzel bir alışkanlık."], ["I should do that.","Ben de öyle yapmalıyım."] ],
         [ ["I fall asleep after one page!","Bir sayfada uyuyakalıyorum!"], ["Books make me sleepy.","Kitaplar beni uyutuyor."] ],
         [ ["I read on my phone.","Telefonumdan okuyorum."], ["I prefer audiobooks.","Sesli kitapları tercih ederim."] ] ] },
  { f=>[ ["Try reading in English. Start with easy books.","İngilizce okumayı dene. Kolay kitaplarla başla."],
         ["You should try reading in English. Start with something written for children, honestly.","İngilizce okumayı denemelisin. Cidden çocuk kitaplarıyla başla."] ],
    o=>[ [ ["Children's books? Really?","Çocuk kitapları mı? Gerçekten mi?"], ["Is that not too easy?","Çok kolay olmaz mı?"] ],
         [ ["Good idea. Which one?","İyi fikir. Hangisi?"], ["Recommend me one.","Bana bir tane öner."] ],
         [ ["I tried and it was hard.","Denedim, zordu."], ["I stopped after ten pages.","On sayfada bıraktım."] ] ] },
  { f=>[ ["Easy is good! You must enjoy it, not suffer.","Kolay iyidir! Keyif almalısın, acı çekmemelisin."],
         ["Easy is exactly right. If you are suffering, you will stop. Enjoyment keeps you going.","Kolay tam olarak doğru. Acı çekiyorsan bırakırsın. Devam ettiren şey keyiftir."] ],
    o=>[ [ ["That makes sense.","Mantıklı."], ["I never thought of that.","Bunu hiç düşünmemiştim."] ],
         [ ["Okay, I will find an easy book.","Tamam, kolay bir kitap bulacağım."], ["Where can I buy one?","Nereden alabilirim?"] ],
         [ ["Can you lend me one?","Bana bir tane ödünç verir misin?"], ["Do you have any at home?","Evde var mı?"] ] ] },
  { f=>[ ["Of course! I will bring one on Friday.","Tabii ki! Cuma bir tane getiririm."],
         ["Of course I will lend you one. I will bring a couple on Friday, you choose.","Tabii ki ödünç veririm. Cuma birkaç tane getiririm, sen seçersin."] ],
    o=>[ [ ["Thank you so much!","Çok teşekkür ederim!"], ["That is really kind.","Çok naziksin."] ],
         [ ["I will look after it.","Ona iyi bakacağım."], ["I will give it back soon.","Yakında geri veririm."] ],
         [ ["Do not choose a long one!","Uzun bir tane seçme!"], ["Something short, please.","Kısa bir şey lütfen."] ] ] },
  { f=>[ ["What about series? Are you watching anything?","Peki diziler? Bir şey izliyor musun?"],
         ["What about television? Are you in the middle of anything at the moment?","Peki televizyon? Şu an ortasında olduğun bir şey var mı?"] ],
    o=>[ [ ["I am watching a Turkish series.","Bir Türk dizisi izliyorum."], ["Yes, a crime series.","Evet, bir polisiye."] ],
         [ ["Nothing right now.","Şu an hiçbir şey."], ["I finished everything!","Her şeyi bitirdim!"] ],
         [ ["Recommend me something.","Bana bir şey öner."], ["What should I watch?","Ne izlemeliyim?"] ] ] },
  { f=>[ ["Watch {series}. I promise you will like it.","{series} izle. Beğeneceğine söz veriyorum."],
         ["Watch {series}. Give it two episodes and you will not be able to stop.","{series} izle. İki bölüm ver, sonra duramazsın."] ],
    o=>[ [ ["Okay, I will start tonight.","Tamam, bu akşam başlarım."], ["I have heard good things.","Güzel şeyler duydum."] ],
         [ ["How many seasons?","Kaç sezon?"], ["Is it finished?","Bitti mi?"] ],
         [ ["Is it scary? I do not like scary.","Korkunç mu? Korkuncu sevmem."], ["Is it sad?","Üzücü mü?"] ] ] },
  { f=>[ ["Watch it in English with English subtitles.","İngilizce altyazıyla İngilizce izle."],
         ["Watch it in English with English subtitles, not your own language. Big difference.","Kendi dilinle değil, İngilizce altyazıyla İngilizce izle. Büyük fark."] ],
    o=>[ [ ["That is difficult but okay.","Zor ama tamam."], ["I will try it.","Deneyeceğim."] ],
         [ ["Why English subtitles?","Neden İngilizce altyazı?"], ["Does that really help?","Gerçekten yardımcı oluyor mu?"] ],
         [ ["I always use my language.","Ben hep kendi dilimi kullanıyorum."], ["It is easier that way.","Öyle daha kolay."] ] ] },
  { f=>[ ["You hear the word and see it. Your brain remembers.","Kelimeyi duyup görüyorsun. Beynin hatırlıyor."],
         ["You hear the word and see it written at the same time. That is when it sticks.","Kelimeyi aynı anda hem duyuyor hem yazılı görüyorsun. İşte o zaman aklında kalıyor."] ],
    o=>[ [ ["That is clever.","Bu akıllıca."], ["I understand now.","Şimdi anladım."] ],
         [ ["How long until it works?","Ne kadar sürede işe yarar?"], ["When will I see progress?","Ne zaman ilerleme görürüm?"] ],
         [ ["Thanks for the tip!","Tavsiye için sağ ol!"], ["You always help me.","Bana hep yardım ediyorsun."] ] ] },
  { f=>[ ["Tell me next week what you thought. {phrase}","Haftaya ne düşündüğünü söyle. {phrase}"],
         ["Report back next week and tell me honestly what you thought. {phrase}","Haftaya bana rapor ver ve dürüstçe ne düşündüğünü söyle. {phrase}"] ],
    o=>[ [ ["I will tell you everything!","Sana her şeyi anlatacağım!"], ["I promise.","Söz veriyorum."] ],
         [ ["What if I do not like it?","Ya beğenmezsem?"], ["Can I stop if it is boring?","Sıkıcıysa bırakabilir miyim?"] ],
         [ ["Thanks for the recommendation.","Tavsiye için teşekkürler."], ["See you next week!","Haftaya görüşürüz!"] ] ] }
 ]
}
]
